### ISSUE TITLE
Convert all interface icons to support other resolutions 

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#105]
We need to convert all interface icons to other resolutions to support different displays resolutions. We mainly need to convert them to: 32x32, 16x16 and 12x12

(Are there other resolutions we should consider?)

**Comment by alex-spataru** [comment]
I think that the most viable way is to use vector icons (e.g. SVG) instead of PNG, which will render the icons resolution-independent.

**Comment by nuttyartist** [comment]
mm... that might be good. Can we do that in Qt? Can it show an .svg icon the same way as a .png?
If so, I think for the simple icons, that might be a good approach, but for a bit more complex ones, maybe vector resizing may not look good or accurate and we should export them as different .png's.

**Comment by theshadowx** [comment]
Well I tried to use svg, but it didn't work well. As I think internally the svg is converted to png and do not look good.

**Comment by nuttyartist** [comment]
@theshadowx ah, ok. Then, .png it is.

**Comment by theshadowx** [comment]
@nuttyartist maybe I've done something not correct, try to use from svg from your side and  see if it working correctly.

**Comment by nuttyartist** [comment]
@theshadowx Alrighty, I've changed the milestone to the Next Next Release because it would fit with supporting HiDipi issue on that milestone.

**Comment by nuttyartist** [comment]
With the transition to font icons this issue can be closed now.
