### ISSUE TITLE
notes can't use sogoupinyin input

### ISSUE THREAD

**Issue by bugeb** [nuttyartist/notes#108]
Background: I use notes_0.9.0_amd64.deb  on ubuntu.

Problem: I can't use my sogoupinyin input on notes. the probem is qt  need fcitx support, because notes depend on qt .

Solution: sudo apt-get install fcitx-frontend-qt5, and reboot.

notes is a good software, I like it and look forward to notes 1.0 version.

reference:  https://bugs.launchpad.net/ubuntu-sdk-ide/+bug/1534492

**Comment by nuttyartist** [comment]
Is there something we can do built-in? Or should it be on Qt side?
Glad to hear you like it.

**Comment by nuttyartist** [comment]
Closing for lack of response.
