### ISSUE TITLE
Searching for multiple words rather than a single phrase

### ISSUE THREAD

**Issue by JungleJim2** [nuttyartist/notes#110]
I want to be able to search for multiple words in a note, not just a phrase. This is especially useful when I cannot remember a phrase to search for, but can remember multiple words in the note.

**Comment by nuttyartist** [comment]
That's interesting. We plan to implement a "Smart Search" feature in the future - it will be like Google for your Notes. Your proposal will surely be considered into that.

**Comment by nuttyartist** [comment]
Moved to #200.
