### ISSUE TITLE
How to install the app from source?

### ISSUE THREAD

**Issue by sgondala** [nuttyartist/notes#113]
I want to contribute to the app. For that, I need to install the app from source. How would I do it? I use Linux and I tried running make_deb.sh but it didn't work.

**Comment by theshadowx** [comment]
you should install Qt (min version 5.6)  https://www.qt.io/download-open-source/#section-2

fork the repository.
then > git clone from your repository

In QtCreator
open the project file src/Notes.pro

compile & run

**Comment by theshadowx** [comment]
If you want to chat about the app or have more question, join us --> https://gitter.im/nuttyartist/notes
