### ISSUE TITLE
Distraction free mode

### ISSUE THREAD

**Issue by sgondala** [nuttyartist/notes#118]
We could have a distraction free mode like in many editors out there. Here's an example in sublime text.

Helps people to focus only on their writing and nothing else
![distraction free](https://cloud.githubusercontent.com/assets/6552560/23260571/76de03fe-f9f8-11e6-8ff8-7278f9f3d492.png)

**Comment by theshadowx** [comment]
this can be done with the pull request #117 ; make window fullscreen and collapse the note list view

**Comment by nuttyartist** [comment]
Yes, we plan to do something like this. We call it "Writing mode". you can read about it in the Wiki (number 5): https://github.com/nuttyartist/notes/wiki/Design
