### ISSUE TITLE
Windows 10 binary doesn't run

### ISSUE THREAD

**Issue by geoffschoeman** [nuttyartist/notes#121]
The current download will not run on a fresh install of Windows 10. 

I receive this error:
The program can't start because MSVCP120.dll is missing from your computer. Try reinstalling the program to fix this problem.

I tried reinstalling and installing Visual studio 12 which was recommended by a StackOverflow post. I already have the latest VS installed. Same error.

**Comment by theshadowx** [comment]
you don't need to install visual studio, you should just install the runtime
https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by nuttyartist** [comment]
Are we not including these files?

**Comment by theshadowx** [comment]
the script in AppVeyor include them in the installer, but the old 0.9.0 installer doesn't include them.

```
if %compiler%==msvc2015 copy "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\redist\\x86\\Microsoft.VC140.CRT\\msvcp140.dll" .
        1 file(s) copied.
if %compiler%==msvc2015 copy "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\redist\\x86\\Microsoft.VC140.CRT\\vcruntime140.dll" .
        1 file(s) copied.
```

the installer in artifact tab include these dll, and doesn't runtime to be installed

**Comment by nuttyartist** [comment]
@theshadowx oh ok.

**Comment by nuttyartist** [comment]
@theshadowx So the version on the dev will work on a fresh install of Windows, right?

**Comment by theshadowx** [comment]
if you use the installer generated by AppVeyor, I think it will work.

By the way, AppVeyor, generate 3 kinds of installers : 
- visual studio 2015 32bit   Qt5.6 / Qt5.7
- visual studio 2015 64bit  Qt5.6 / Qt5.7
- mingw 32bit                    Qt5.6 / Qt5.7

I think I will add Qt5.8 as I've just noticed that they have just added in AppVeyor.

the ones compiled with visual studio they include the vc runtime

the ones compiled with mingw mingw compiler lib

I think they will work in a fresh install, But it should be confirmed.

I will add a line in AppVeyor script to launch the executable.

**Comment by geoffschoeman** [comment]
Thanks, that worked
