### ISSUE TITLE
Error when compiling from source

### ISSUE THREAD

**Issue by leonklingele** [nuttyartist/notes#122]
What I did

```sh
$ git clone .. ; cd ..
$ qmake
$ make
cd src/ && /usr/local/bin/qmake /path/to/notes/src/Notes.pro -o Makefile.Notes
WARNING: /path/to/notes/src/Notes.pro:96: Unescaped backslashes are deprecated.
Project MESSAGE: Warning: unknown QT: gui-private
cd src/ && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.Notes
make[1]: *** No rule to make target `../bin/Notes.app/Contents/Resources/images\notes_icon.icns', needed by `all'.  Stop.
make: *** [sub-src-Notes-pro-make_default-ordered] Error 2
```

**Comment by nuttyartist** [comment]
I think I've faced this problem once too. Make sure that your project path (or Qt path) doesn't have spaces in it.

**Comment by theshadowx** [comment]
I'll try to set a MacOs test in Travis. by the way could you replace "\" with "/" in the icon path : 

https://github.com/nuttyartist/notes/blob/dev/src/Notes.pro#L96

and try to recompile.

Also it's better to go to src folder and compile from there, to not waste compilation time in tests.

**Comment by leonklingele** [comment]
@nuttyartist I have no spaces in said paths

**Comment by nuttyartist** [comment]
@leonklingele Have you tried @theshadowx suggestion?

**Comment by theshadowx** [comment]
@leonklingele My mistake I wanna said to replace  "\\" with "/"

**Comment by leonklingele** [comment]
Fixed by updating to Qt version 5.8.0 (QMake version 3.1).
Sorry! 😩

**Comment by nuttyartist** [comment]
Glad you find a solution. :+1:

**Comment by theshadowx** [comment]
@leonklingele which Qt version was used that generated the error ?
