### ISSUE TITLE
Font color of TextEdit is changing when writing from the start of a note.

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#125]
The font color of TextEdit is changing when clicking on a start of a note and starting to type. It changes the color to Regular Black.

**Comment by theshadowx** [comment]
I think I have fixed this issue in this commit https://github.com/theshadowx/notes/commit/e301cea61e2d184f70a19963fe4d0d05b515bc65

**Comment by nuttyartist** [comment]
mm.. Will check it out.

**Comment by nuttyartist** [comment]
Still the same for me.

**Comment by theshadowx** [comment]
weird because when I changed the color in this line: 
https://github.com/theshadowx/notes/blob/dev/src/mainwindow.ui#L50

to red for example, and do the same operation you showed in the video, the color doesn't change.

**Comment by nuttyartist** [comment]
@theshadowx You're right. I just checked and couldn't reproduce the problem. I'll close this for now and if I would get encountered with this again I will reopen the issue.
