### ISSUE TITLE
Make window shadow wider, while keeping it blurry

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#128]
The shadow of the window should be bigger, wider, but without losing the blurriness effect - it shouldn't be solid, but rather very blurry as it gets farther way from the window. This will turn out to be the best effect of depth.

**Comment by nuttyartist** [comment]
@theshadowx I can't evaluate how good it is because of picture quality, but maybe we can take inspiration from his code? Is it good?
http://stackoverflow.com/questions/23718827/qt-shadow-around-window/23752747#23752747

**Comment by theshadowx** [comment]
I'll take a look

**Comment by nuttyartist** [comment]
#295 Solved this on Mac and Windows by using native windowing. #295 On Linux reverted the custom shadow drawing to let the window manager draw the frameless window. On the distributions I checked: Ubuntu, Elementary OS, ZorinOS - the window was rendered well with a nice shadow. Some distros might not do this well, this is why we still have the option to use native window. So, closing this.
