### ISSUE TITLE
Create automatic packaging for .deb, .rpm, snap and flatpack

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#13]
We want to create the packages through a simple 'run that script and it will create your packages' kind of way. For .deb, .rpm and snap.

- [x] .deb script
- [x] .snap script
- [ ] .rpm script
- [ ] .flatpack script
- [x] Main Automatic Script

**Comment by theshadowx** [comment]
here is an interesting project that do packaging for linux OSes

https://github.com/probonopd/AppImageKit

**Comment by nuttyartist** [comment]
Oh yeah, I heard of it, it's a very cool thing.

The main drawback I can see is that after downloading the appimage people needs to allow it to be executable, which require, on most of the distros right-clicking ->properties->allow to execute (something like that) but on some distros it's different (eOS), or they need to use the command line.
Both of the options are not as end-user friendly as just clicking on a .deb file and just install.

Second thing is that using .deb, .rpm and snap,and uploading them to the official repository will allow our app to be discovered by people using software center etc...

A solution for the first claim might be to put a nice explanation on the website on the download page.
Also automatic updates are very important, and I saw they have a nice support for that one, which is good.

What will be a good indicator for choosing between all of the options is the end result of what the user will experience. If in the end, it will be easy and intuitive for him to download and install, and without a hassle get automatic updates, then that's could tell it's a good thing. It should also be easy and intuitive and automatic for us - the developers to package and iterate the app.

**Comment by alex-spataru** [comment]
Well, for one of my projects I wrote scripts to generate _.deb_ and _.snap_ packages. Unfortunately, I am clueless about how to generate _.rpm_ packages.

You can find the deploy scripts [here](https://github.com/WinT-3794/QDriverStation/tree/master/etc/deploy/linux).

**Comment by nuttyartist** [comment]
@dplanella is already working on a snap packaging [here](https://github.com/dplanella/notes/tree/snappy/packaging/linux/snap). Maybe you can contribute there if you see areas you can help.

We have a *debian* folder, can you write a script to package it?

The goal is to have one main script to be run, that will make all the different packages automatically by running their own scripts. So when the specific scripts will be ready we'll create the main script.

**Comment by alex-spataru** [comment]
Yes, I will create a new pull request with the debian package script.

**Comment by alex-spataru** [comment]
@nuttyartist Done!

**Comment by nuttyartist** [comment]
@dplanella doesn't seem to progress on the .snap script.

@alex-spataru Can you take on what he's [done](https://github.com/dplanella/notes/tree/snappy/packaging/linux/snap) and finish it? And then create the `main script` that will build both the .deb and .snap?

**Comment by alex-spataru** [comment]
@nuttyartist I will take a look at the snap configuration and update the packaging scripts.

**Comment by nuttyartist** [comment]
Great! Thanks.

**Comment by dplanella** [comment]
@nuttyartist @alex-spataru I had a go at snapping 0.9, which worked, but I'm encountering theming issues. This is not related to Notes itself, but to the fact that a proper theming interface for snaps is still in the works. There has been some progress this week on that, but I've not tested it yet. I'd wanted to wait to submit a PR until everything is working correctly. The latest code is here: https://github.com/dplanella/notes/tree/snappy

That contains a make target (`make snap`) that automatically generates the snap and bumps its version based on the git revision of the code used to build it.

**Comment by nuttyartist** [comment]
@dplanella Oh ok. I probably should have asked you about the state before. So @alex-spataru we'll wait for everything to work as it's should, and after @dplanella would send a PR we'll work on the main script.

**Comment by alex-spataru** [comment]
@nuttyartist @dplanella Thanks for the information! Ping me if I can help with the packaging.

**Comment by nuttyartist** [comment]
@williamjmorenor Are you going to take the steering wheel and help with creating a .rpm and .flatpack packages, so other people could use Notes?

**Comment by williamjmorenor** [comment]
I wil work can work in the rpm packaging of this app, then will look at flatpackagin.

**Comment by nuttyartist** [comment]
@williamjmorenor Sounds good.

**Comment by nuttyartist** [comment]
Hey @williamjmorenor, how's the progress on the rpm?

**Comment by nuttyartist** [comment]
I see there is no progress on rpm and flatpack. Fortunately, snap supports other major Linux distros such as Fedora that use rpm, and flatpack and snap mostly have the same goal, so as we already have snap, we'll drop them and not waste energy on them. If some people would like to contribute for that, they're welcome, but it's no longer an open issue.

@alex-spataru Can you create the package_all.sh script that just calls the .deb and .snap scripts? I'm lacking any knowledge in creating script files and thought it would be fairly easy for you.

**Comment by alex-spataru** [comment]
Yes, I will make a pull request with the new packaging script.

**Comment by nuttyartist** [comment]
thanks (: @alex-spataru

**Comment by probonopd** [comment]
Wrote an AppImage recipe for Notes:
https://github.com/probonopd/AppImages/blob/master/recipes/meta/Notes.yml
It uses the deb from the Releases page and repackages it as an AppImage.

Try it here:
https://bintray.com/probono/AppImages/Notes#files

Some fine-tuning might be needed. Let me know how it works for you.
Would you be interested in providing an official one?

**Comment by nuttyartist** [comment]
Looks good,

If you're committed to being available and generate an app image for every release, we're on it. I can't update the website right now, because, with the tool I'm using I can only publish whole of the changes I've made to the website one at the time, so because I've been changing things for version 1.0.0, only when 1.0.0 is out, you can create an app image for it, and I will upload it (:

Thanks @probonopd

**Comment by probonopd** [comment]
Sure I can do that. If you ping me after each release ;-)

Since it's only one bash file and one tiny yml file (linked above), so if you mirror these two files and run them on after each release, then you could easily do it yourself. Version numbers are not hardcoded, so it should work for each new release automatically.

**Comment by probonopd** [comment]
The PR above will package the build artefacts from Travis CI as an AppImage and upload them to transfer.sh, where they will be stored for 14 days.
