### ISSUE TITLE
Links to other Notes and headers inside a note

### ISSUE THREAD

**Issue by edrlima** [nuttyartist/notes#131]
I would like to see a way to make links or a reference to other notes inside a note.

**Comment by nuttyartist** [comment]
Hey @edrlima,

We certainly want to make that feature in future versions. We would probably work on that alongside the rich text feature where when you select a text, a popup will be opened with a link option.

Thanks for the request we'll add it to our features list.

**Comment by bjorn** [comment]
For future reference, this became issue #431.
