### ISSUE TITLE
AppImage package doesn't show icon in system tray

### ISSUE THREAD

**Issue by theshadowx** [nuttyartist/notes#132]
@probonopd When double clicking the package generated, there is no icon shown in the systray, also the there is no entry icon added to applications menu.

OS: Ubuntu 14.04 
I used the package : https://transfer.sh/OSnK3/notes_0.8.0-git9bb43e0_amd64.AppImage

here is the log 
https://travis-ci.org/theshadowx/notes/jobs/232218472#L881

**Comment by probonopd** [comment]
`linuxdeployqt` does not offer desktop integration, like installing a desktop file into the menu. You could either use the optional `appimaged` daemon to do that, or use a script like https://github.com/probonopd/AppImageKit/blob/master/desktopintegration inside the AppImage.

**Comment by guihkx** [comment]
I'm going through some old issues, and I don't think this one is applicable anymore:

>there is no icon shown in the systray

Based on my tests on GNOME 43 and KDE 5.26, the tray icon is displayed just fine with our development AppImage build (but also with the 2.0.0 release).

>also the there is no entry icon added to applications menu.

The link for the `desktopintegration` script posted by @probonopd was removed and, in my understanding, the only current solution for desktop integration within AppImages, is based on a daemon that should be installed separately (and by the user?):

- https://github.com/probonopd/go-appimage/blob/master/src/appimaged/README.md#appimaged
- https://github.com/TheAssassin/AppImageLauncher#appimagelauncher

So I think we can close this one, @nuttyartist.

**Comment by nuttyartist** [comment]
👍
