### ISSUE TITLE
Make Window Buttons optional

### ISSUE THREAD

**Issue by DevWurm** [nuttyartist/notes#133]
Please make the Window Buttons (Close, Minimize, Maximize) optional and make it possible to use the native window control elements. This would fit better into my OS design

**Comment by nuttyartist** [comment]
We aspire to have a consistent design over all of the platforms we're running on, and so, we're going to keep pursuing our current methods while on each iteration we'll try to refine it and make it look better on specific os's (Windows and Mac will look much better on the next release). May I ask what OS are you using?

**Comment by DevWurm** [comment]
I use a themed Ubuntu ;)
I think the window itself (including the buttons) should look consistent across the OS. Thats why it would be great to disable the ones of the application and use the native ones instead.
