### ISSUE TITLE
Searches Text Highlight

### ISSUE THREAD

**Issue by lovebdsobuj** [nuttyartist/notes#134]
Searches word highlight from note text. Press (Enter/Return) key on search field to find next word.
and Showing line number, how would be?
![notes_future_mockup_modern](https://cloud.githubusercontent.com/assets/10352682/26457038/a8843ee8-4190-11e7-9109-b084f3a9e277.png)

**Comment by nuttyartist** [comment]
We already plan to highlight found searched words (look here https://github.com/nuttyartist/notes/issues/81), but I'm not sure we'll go with the line numbers.

**Comment by lovebdsobuj** [comment]
I'm sorry. I didn't search this thing before post.
