### ISSUE TITLE
App can't connect to db

### ISSUE THREAD

**Issue by theshadowx** [nuttyartist/notes#137]
During the first launch of the app, it tries to connect to database while the file is not being created.

**Comment by nuttyartist** [comment]
Is it? And, is it a problem?

**Comment by theshadowx** [comment]
the issue is that the notes won't be saved. when the user launch the app for the first time.

**Comment by nuttyartist** [comment]
I didn't experience that. The notes seem to be saved after closing the first launch.

**Comment by theshadowx** [comment]
but the issue is that the db file is not created.

This behavior happens just at the first start meaning that the second launch of the app the database file is created. I don't know why this happen. I have tested the app in a docker image : 

![selection_307](https://user-images.githubusercontent.com/976569/27003699-3f9779c4-4deb-11e7-8f2d-ccb4a46b95d6.jpg)

**Comment by theshadowx** [comment]
I think now it is fixed.

![selection_308](https://user-images.githubusercontent.com/976569/27003753-2d74055e-4dec-11e7-827e-fbbec3817cf5.jpg)

**Comment by nuttyartist** [comment]
I don't see the problem at all. Look at the video I sent in Gitter.

**Comment by nuttyartist** [comment]
Yes, working well now.
