### ISSUE TITLE
Stretching in Unity DE

### ISSUE THREAD

**Issue by theshadowx** [nuttyartist/notes#150]
Stretching doesn't work well in Ubuntu 14.04.5

**Comment by nuttyartist** [comment]
On all packages? Have you tried using a different version of Qt?

**Comment by theshadowx** [comment]
I have tried just deb package for trusty:

https://transfer.sh/TGA3P/notes_0.9.0_amd64-trusty.deb

I'll check with other packages, but I don't think it's a matter of which package was used.

**Comment by nuttyartist** [comment]
ok. So maybe it's a problem related to the specific Qt version?

**Comment by theshadowx** [comment]
I think the source of the problem comes from the algorithm used to update the size the window.
as the Unity DE isn't shaped as gnome2 or gnome3.

**Comment by nuttyartist** [comment]
Aren't we implementing our own stretch mechanism; with the same code across all distros?

**Comment by theshadowx** [comment]
yes but Unity has some a left side bar which I think was not considered in the algorithm. I need to check for that

**Comment by nuttyartist** [comment]
Ok.

**Comment by nuttyartist** [comment]
Fixed now, right?
