### ISSUE TITLE
Update snap to 1.0

### ISSUE THREAD

**Issue by Ads20000** [nuttyartist/notes#152]
Please can you update the snap for Notes? If you use [build.snapcraft.io](build.snapcraft.io) in future then it would build `edge` releases from this repository automatically and then all you'd have to do is promote to the snap built when a release is tagged to `stable` (maybe passing it through `candidate` and `beta` briefly to check it works!)

Alternatively just keep doing it manually (though if you could set up automatic builds of the GitHub repository to `edge` that would be cool!), but please update the snap when new releases are made!
[OMG! Ubuntu! referencing the out-of-date snap and the current requirement to get Notes 1.0 from source.](http://www.omgubuntu.co.uk/2017/08/mac-inspired-notes-app-update)
[uApp Explorer listing for the snap showing that it's still at 0.9](https://uappexplorer.com/snap/ubuntu/notes)

**Comment by nuttyartist** [comment]
Oh no, the release isn't ready yet!
Didn't though someone will catch that release here on Github and think that's it without any installers.

Don't worry @Ads20000, just wait for the new release to finalize and everything should be in place, including a new .snap package on the site.

**Comment by Ads20000** [comment]
The release was made yesterday? I'm no programmer but maybe consider releasing a release candidate in future instead of a release if it's not ready? E.g. you could pre-release 1.1 as `1.1-rc` and then release it as `1.1` when it's all ready? :)

**Comment by nuttyartist** [comment]
It's ready, just need to upload the installers and update the site. But you right about one thing I wasn't organized enough and should've done everything in the same batch. You could expect better handling with releases in the future!

**Comment by theshadowx** [comment]
@Ads20000 the build.snapcraft.io needs that the snapcraft.yaml be in the root path or in a snap folder in the root. The tree of this repository doesn't satisfy these conditions, that's why we haven't yet used the website which is still in beta. I'm waiting that they provide a way to select the folder that contains the yaml file. I have mentioned that in the issue  https://github.com/canonical-websites/build.snapcraft.io/issues/440
