### ISSUE TITLE
Systray Toggle Option

### ISSUE THREAD

**Issue by sdmunozsierra** [nuttyartist/notes#153]
Hi, 

Excellent work so far! I really like your application as far as usefulness and simplicity. I would like to ask if you can add an option for toggling the systray icon, as I have a dedicated desktop just for it. For the moment I will be using an older version which works well for me. 
In return if you need any help with Spanish translations or Arch Linux testing feel free to let me know! 

Thanks,
Sergio

**Comment by theshadowx** [comment]
what do you mean by toggling the systray icon ?

**Comment by sdmunozsierra** [comment]
Toggling as do not show the Systray icon at all, because even if I have it open all the time it still shows the icon.

This is the dedicated desktop where I have the application.
![Image of Desktop](http://imgur.com/LyJEDSu)

This is the right side of the status bar and it still shows the icon.
![Image of Bar](http://imgur.com/ZYu2NmF)

**Comment by sdmunozsierra** [comment]
Sorry here are the images again:

Dedicated desktop:
![2017-aug-13_16 14 04](https://user-images.githubusercontent.com/17910108/29253719-04de638a-8075-11e7-8e88-41a7543158be.png)

Notification Bar:
![2017-aug-13_16 16 04](https://user-images.githubusercontent.com/17910108/29253730-13c5076e-8075-11e7-9582-e45bfa61e7a0.png)

**Comment by theshadowx** [comment]
As you have a customized window manager, It will be hard to satisfy your demand.
isn't possible to tell window manager to not show the the icon in a systray for a specific application.

On the other hand, if close the app (clicking on the red button) the application is going to be hidden but not quitted, in this case the  icon in systray will help to show the app (it's true that there is a shortcut that make the app to be shown).

**Comment by sdmunozsierra** [comment]
Oh I see so the icon in the systray will always show when the app is closed by the red button. So now my last question is, does the systray icon shows when it is open? Like a persistent icon?

**Comment by theshadowx** [comment]
yes it's a persistent icon.

**Comment by sdmunozsierra** [comment]
Ok perfect! Thank you very much! 
I will be on the lookout for future releases and anything related with arch and translations feel free to hit me up.
