### ISSUE TITLE
Please provide AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [nuttyartist/notes#156]
Right now an AppImage is uploaded to transfer.sh for each build. But for users this is a bit inconvenient, since they need to look up the transfer.sh download URL in each Travis CI build log. Hardly anyone will look for it there.

Hence it would be nice if for releases and possibly also for continuous builds, the AppImage could be downloaded to the GitHub Releases page as well.

Personally I am using https://github.com/probonopd/uploadtool for this. Could easily be adapted to your needs.

Reference:
https://github.com/AppImage/AppImageHub/issues/15

**Comment by theshadowx** [comment]
Of course we will upload all the installers and in the release section.

**Comment by nuttyartist** [comment]
Hi @probonopd,

Like @theshadowx said, when we'll release the new version, we'll make the AppImage available to download from the Github releases and from our website. We do not plan yet to make continuous builds (every minor version) of our AppImage available on our Github repo, yet they will still be available from travis.

You may want to consider using the .deb package (of the new version) that will supports automatic updates. Of course, with every major version, we'll supply AppImage available to download from Github and our site.

Thanks.

**Comment by probonopd** [comment]
Thanks @nuttyartist, looking forward to it.
By the way, using AppImageUpdate you can set up automatic binary delta updates for AppImages, if you embed the necessary update information.

https://github.com/AppImage/AppImageSpec/blob/master/draft.md#github-releases

**Comment by nuttyartist** [comment]
We'll definitely put that on our wish list for future releases and try to implement that for our AppImage users. Thanks, @probonopd.
