### ISSUE TITLE
AUR package 1.0.0 --> md5sums-checksum fails

### ISSUE THREAD

**Issue by theshadowx** [nuttyartist/notes#157]
Hi @gkbrk, Could you please update the AUR package for 1.0.0 as we (I) have modified the source code and released it as 1.0.0 just after you made the package in AUR repo. 

As result : md5sums-checksum is failing.

Thanks.

**Comment by gkbrk** [comment]
Done!

**Comment by theshadowx** [comment]
wonderful, thanks a lot.

**Comment by theshadowx** [comment]
@konstantingoretzki, could you please check if the package installation works correctly.

**Comment by theshadowx** [comment]
From @konstantingoretzki (in gitter)
> @theshadowx Works! Thanks a lot ;)
