### ISSUE TITLE
Random feedback 

### ISSUE THREAD

**Issue by itrema** [nuttyartist/notes#158]
![ali](https://user-images.githubusercontent.com/20866926/29606031-3b90cf56-87ed-11e7-9e3f-ef703c8cb0d4.PNG)

**Comment by nuttyartist** [comment]
Thanks a lot for your feedback!

- We aren't supporting auto-correction yet. Definitely something we'll consider for future releases.
- There isn't a mobile version of Notes yet (iOS or Android), but we plan to make one as soon as we can (likely when iOS and Android developers join our team).
- Can you send a screenshot of how the "more" button looks like when you click on it? I want to see if it's different than what we intended it to be.
- We'll improve the color contrast when selecting text, thanks!

Also, it seems like the notes in your list are not aligned as they should. This is probably a bug. What version of Windows are you using (7, 8, 10)?

Again, thanks a lot for the feedback, it's greatly appreciated. We always listen carefully to our users and strive to improve Notes so they could have the best experience possible.

**Comment by itrema** [comment]
Sure, check the png attached
Using Windows 10 (work laptop)
Going to try it on my macbook pro tonight
You're welcome, that was an instant feedback , getting back to you later on if I notice something else
Good luck to you all !

![ali](https://user-images.githubusercontent.com/20866926/29607666-3732d346-87f2-11e7-9e66-18d884fc560d.PNG)

**Comment by nuttyartist** [comment]
Alrighty, thanks.
We'll make sure to work fix the bug and taking into account your feedback for the issues.

**Comment by nuttyartist** [comment]
Hey @itrema, we're trying to solve the problem of notes not being aligned well, but we need to collect more details. Can you tell us please what is your display resolution?
