### ISSUE TITLE
No shadows on the window

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#16]
Some operating systems don't support native shadows on frameless windows. This is really important because shadows give a sense of depth and differentiate the window from other windows. 
Good guys: **Linux DE's:** Unity, Deepin **Windows:** Windows 10 **Mac:** Yosemite
Bad guys: **Linux DE's:** Elementary OS,  KDE, Gnome, Linux Mint **Windows:** Windows 7, Windows 8

**Comment by voldyman** [comment]
Did you try using `Qt::ToolTip` instead of `Qt::FramelessWindowHint`?

**Comment by voldyman** [comment]
Oops, scratch that, it introduces more problems than it solves

**Comment by nuttyartist** [comment]
Haha @voldyman yes, as you said it's an indirect solution that just create problems.
I am quite sure the problem lay on the side of the window managers and the way they treat the FramelessWindowHint. I already tried to contact elementary OS (that use Mutter, window manager that other distros use) developers and I wait for a response. I hope other os's developers will contact me, and maybe I would try to contact them sometime.

**Comment by nuttyartist** [comment]
As I said earlier, the solution to this lays on the side of the window manager, so only the operating system developers can solve that bug.

After contacting with ElementaryOS people, the problem is solved on their next release - Loki, as a result of a fix on the upstream window manager - Mutter, so other os's that uses Mutter would benefit.

I hope other window managers will solve that issue.
