### ISSUE TITLE
1 report of Notes crashing on Windows, not reproduced

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#165]
Got an email from someone running Notes on Windows who reported having 455 notes. He reported having version 0.9.0 installed, and when installing version 1.0.0 and running it the app crashed. 

He said: 

> With some experimenting, I determined that the Trash.ini file was causing the crash. Once deleted, before launching new version, everything worked properly. Hope this helps, if you have not already run into this.

OS version: Windows 8.1.

![image](https://user-images.githubusercontent.com/16375940/30038589-14efcf50-91cf-11e7-83a0-a1413167c538.png)

**Comment by theshadowx** [comment]
if so it should be related to the migration.

**Comment by nuttyartist** [comment]
It's really weird, I didn't have this problem and a friend of mine didn't report that too. I want to check with my full list of notes and we should do further testing on that.

**Comment by nuttyartist** [comment]
I've just tried to migrate my older Notes.ini into the new version, and everything went successfully. Still don't know where that bug is coming from.

**Comment by theshadowx** [comment]
Could you ask the email sender to come here and tell us more about what was done, so we can reproduce the issue.

**Comment by nuttyartist** [comment]
I've contacted him.

By the way, in our emails he said: 

> With some experimenting, I determined that the Trash.ini file was causing the crash. Once deleted, before launching new version, everything worked properly. Hope this helps, if you have not already run into this.

**Comment by nuttyartist** [comment]
There are no other reports for this issue, so I would assume it's not as prevailing as other critical issues.

**Comment by nuttyartist** [comment]
Closing for now. I will open this if more people report the same issue.
