### ISSUE TITLE
Don't show the "What's new" box in the Updater if there's no new update.

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#172]

**Comment by theshadowx** [comment]
it should show the text of the release.

**Comment by nuttyartist** [comment]
You mean of the currently installed version? If so, I think this should be done like how it's done on iOS, when a new version comes out we have the option to show the recent release history. So, for example a new update comes out:

```
What's new:

Version 1.1.0 released
* New feature.
* Bug fixed.

Changelog:

Version 1.0.5:

* improvment
* fixes
```

Something like that...

**Comment by theshadowx** [comment]
ya a changelog

**Comment by nuttyartist** [comment]
So we should have a changelog when a new release comes out. When there's no new update the "What's new" doesn't need to be shown.

**Comment by theshadowx** [comment]
nothing will be shown

**Comment by nuttyartist** [comment]
What do you mean?

**Comment by theshadowx** [comment]
When there is no update, What's new should be hidden.

**Comment by nuttyartist** [comment]
Yes, indeed.

**Comment by nuttyartist** [comment]
This is not an issue anymore. I think it's good that the user has access to the change log. We can reopen this if we think otherwise. Closing.
