### ISSUE TITLE
Window should be draggable only from the top part of the window.

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#173]
My opinion is that a Window should be draggable only from the top part of the Window from y:0 to lineEdit:y. This is the expected behavior on most operating systems and not from any point in the app.

**Comment by dread-uo** [comment]
This seems resolved. Is it?

**Comment by nuttyartist** [comment]
No. Currently, you can drag the window from any location on the app that is free of widgets (like the space between text-editor and the text itself.) We want it so the window would be draggable only from the top. It should be really easy to do. That's why it has a "good first issue" label.
