### ISSUE TITLE
Aesthetic changes

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#177]
List of aesthetic changes to be made (I'll work on that and send a PR):

- [x] Change buttons colors to reflect better the states they're in (hovered, pressed, released).
- [x] Revert back to old editor background (?)
- [x] Add Qt::WA_MacShowFocusRect, 0 to lineEdit (this disable the not-in-style focus rectangle in lineEdie on MAC).
- [x] Custom textEdit and lineEdit color when selecting text. 
- [x] Don't change font size when clicking a note? EDIT: Decided to keep the way it is - thinning the note text when selected, to make the selection more clear.

**Comment by nuttyartist** [comment]
- Removed the hovered state of buttons.
- Reverted to old textEdit background, I think it's more beautiful and less boring. Plus it focuses on the text more.
- Added Qt::WA_MacShowFocusRect attribute to lineEdit.
- Made custom selection-background-color for textEdit and lineEdit.

**Comment by bjorn** [comment]
@nuttyartist Given that you appear to have already made these adjustments 3 years ago, what is preventing these changes from going in now rather than waiting for 2.0.0?

**Comment by nuttyartist** [comment]
Oopsi, I don't know why it's in 2.0.0. I removed it from there. This issue seems to be solved. I remember I reverted back the decision to change the font size (to be thinner) when clicking on a note. But I would like to revert it back again (keep it the same size). Also, Qt::WA_MacShowFocusRect doesn't seem to be effective anymore.
