### ISSUE TITLE
TextEdit's scrollBar not close to the right when visible

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#18]
TextEdit's scrollBar not close to the right when visible (because of text padding).
Good guys: **Linux DE's:** Unity
Bad guys: **Linux DE's:** Elementary OS,  KDE, Gnome, Deepin, Linux Mint **Windows:** Windows 7, Windows 8, Windows 10 **Mac:** Yosemite

**Comment by nuttyartist** [comment]
This issue doesn't happen on Ubuntu Unity. So it's probably the way that other os's taking care of the textEdit's padding. Can we solve that on our side? Qt side? Or can it only get solved by the os developers?

**Comment by nuttyartist** [comment]
This issue should get solved on the side of the window manager, so only the operating system developers can solve that bug.

**Comment by theshadowx** [comment]
Could you add a screenshot.

**Comment by nuttyartist** [comment]
Sure:

![screenshot](https://cloud.githubusercontent.com/assets/16375940/20301621/b1b7bb66-ab2c-11e6-98e2-410e773339f6.png)

**Comment by theshadowx** [comment]
I think the right margin should be reduced, to let the scrollbar to be on the far right;

**Comment by nuttyartist** [comment]
The right margin of the text should be aligned with the trashButton (the way it's now), but it shouldn't take the scrollBar with it. I think that on Ubuntu Unity this problem doesn't happen.

**Comment by theshadowx** [comment]
is this still an issue ?

**Comment by nuttyartist** [comment]
@theshadowx Yes, it is.

**Comment by nuttyartist** [comment]
Solved in #283, yet not merged yet...

**Comment by nuttyartist** [comment]
Solved in #295 by creating `CustomDocument` class and setting `setViewportMargins`.
