### ISSUE TITLE
Systray icon is hardcoded and can`t be changed using a icon theme

### ISSUE THREAD

**Issue by rafrsr** [nuttyartist/notes#182]
See the following pint screen:

![image](https://user-images.githubusercontent.com/7094012/31722376-e866783e-b3e9-11e7-8603-cc93ac503c86.png)

The systray icon does not match with current theme, currently I'm using the icon theme "La Capitaine". The app icon in applications list is already changed but not the systray icon.

![image](https://user-images.githubusercontent.com/7094012/31722808-0a1abbd8-b3eb-11e7-86b6-33073ce3cd0c.png)

Should allow the use some icon like 'notes-panel.svg' to control the appearance using a symbolic icon inside each theme.

**Comment by nuttyartist** [comment]
Hi @rafrsr, isn't the symbolic linking something you do on your own OS?
We don't plan to tailor our icon for each operating system, although we do want to create more resolutions for our Icon which might help it look better in your situation.

**Comment by rafrsr** [comment]
What I mean is that there are applications (shutter, enpass, dropbox ...), that your icon can be overwritten using an icon theme like Papirus etc... is this possible with this application? what name should the icon have in the theme?

**Comment by nuttyartist** [comment]
mmm... I think you should look into the Desktop.ini files of these apps and see whats in there. Maybe that would tell you how to change the Notes Desktop file accordingly.

**Comment by rafrsr** [comment]
Desktop.ini??, I'm working on linux, ubuntu 17.10

**Comment by nuttyartist** [comment]
I'm sorry, I meant .dektop files. They should be in /usr/share/applications/. You should try open them with your favorite text editor.

**Comment by rafrsr** [comment]
I had already changed it with "Icon=notes" and the icon is updated in the applications menu but not in the tray.

**Comment by nuttyartist** [comment]
Oh ok, got you now. Currently, it seems like we have to hardcode the icon for it to be displayed in the system tray using our cross-platform framework Qt. Doing things specifically for some os's, like Linux, is quite a dirty of a work.

**Comment by varlesh** [comment]
It's popular solution - use system icons if available and built-in as fallback.
For example:
`QIcon icon = QIcon::fromTheme("notes-tray", QIcon(":images/notes_system_tray_icon.png"));`

**Comment by nuttyartist** [comment]
@varlesh This is usually the way to go on Linux systems indeed. I'll create a new issue for that, thanks!
