### ISSUE TITLE
Checked symbol in checkbox is not visible unless the element is hover on Mac

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#183]
On Mac, I see the '✓' icon only when I hover over the menu, but it should be shown also when I don't hover and highlight the menu.  More info about the bug and partial solutions can be found here #181.
![31583183-8a545010-b19e-11e7-852a-d4b576625cb7](https://user-images.githubusercontent.com/16375940/31850261-082e219c-b658-11e7-9a61-279157a08845.gif)

**Comment by bjorn** [comment]
Just noting that this is related to the following stylesheet, according to comments at #181.

https://github.com/nuttyartist/notes/blob/858f617d5cb769fd0564688a7d01a0cb5a066769/src/mainwindow.cpp#L929-L932

**Comment by nuttyartist** [comment]
Yes, these few lines are problematic. Can you please create a PR where you comment out these lines so we let the pop up be drawn natively?

https://github.com/nuttyartist/notes/blob/858f617d5cb769fd0564688a7d01a0cb5a066769/src/mainwindow.cpp#L928-L936

**Comment by nuttyartist** [comment]
Solved #273 by reverting to drawing native pop-up.
