### ISSUE TITLE
libEGL.dll, libGLESV2.dll,opengl32sw.dll are not necessary part when you pack the code

### ISSUE THREAD

**Issue by Ctipsy** [nuttyartist/notes#190]
If you are  executing windeployqt command to generate  the relevant dependent libraries.
_________________________________________________________________________________________________________
opengl32sw.dll is needed when the user's computer system doesn't support the DirectX.
libEGL.dll，libGLESV2.dll is needed when the use's computer doesn't install Graphics drivers.

Both of these situations are extreme.
You can use the command below to  compress your setup package,The three dll files add up to 22.3M(my pc is win10 64bit)
windeployqt  –no-angle  & –no-opengl-sw

**Comment by nuttyartist** [comment]
In the title of the issue, you said the DLL's aren't necessary, but in the description you said they're necessary. Do you mean to say that they're necessary but only a limited amount of users *actually* need them?

We prefer to go on the safer side, we want to make sure that our app could be used even with a completely clean install of Windows.

**Comment by Ctipsy** [comment]
> Do you mean to say that they're necessary but only a limited amount of users actually need them?
Yes, I mean that.

> we want to make sure that our app could be used even with a completely clean install of Windows.
All right, then just keep the three dlls @nuttyartist

**Comment by nuttyartist** [comment]
> All right, then just keep the three dlls @nuttyartist

👍 Closing.
