### ISSUE TITLE
Automatic startup

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#195]
We should implement that Notes would run when the system is running on startup. This way people could jot down their thoughts (ideally, when working) just by pressing the "Super Key" + "N".

**Comment by bjorn** [comment]
So, this was actually implemented in 3978e47d245ff84bbb708fe78722a09617cac99b, but the issue didn't close because that commit referenced #193 instead of #195.

But, later on autostart was disabled for macOS in #232, though without stating the problem it was fixing. @theshadowx, can you shed some light on this?

**Comment by theshadowx** [comment]
@bjorn The QAutostart is not supported in mac, as mentioned in readme: https://github.com/b00f/qautostart

The reason is that the compilation fails as QProcess doesn't work in mac.

**Comment by bjorn** [comment]
@theshadowx Ah, I was confused because the code did seem to handle macOS. But, it can't be that in general `QProcess` is not working on Mac. I'm using it in Tiled as well to run custom commands set up by the user and it does also work on macOS.

**Comment by theshadowx** [comment]
I have forked QAutostart and added in qautostart.cpp
```
include <QProcess> 
```

It did compile https://github.com/theshadowx/notes/runs/471152271?check_suite_focus=true. I don't Mac machine so I don't know if the functionality is working.

**Comment by bjorn** [comment]
> I have forked QAutostart and added in qautostart.cpp

I don't really understand, `#include <QProcess>` [is already there](https://github.com/b00f/qautostart/blob/3bcab269a6a8ba4a4824d73bbf8d9b87dd62cd18/src/qautostart.cpp#L29
). I'll see if I can find some time to test the functionality.

**Comment by theshadowx** [comment]
Indeed, maybe ```include <QProcess>``` should be at the end. As when I just commented ifdef guard and compile with github ci, it failed :

**Comment by nuttyartist** [comment]
I can test it if needed, @theshadowx. Let me know the artifact link.

**Comment by theshadowx** [comment]
Use this branch from my repo https://github.com/theshadowx/notes/tree/qprocess_mac

**Comment by nuttyartist** [comment]
Didn't find any artifacts: https://github.com/theshadowx/notes/actions/runs/45817715

**Comment by theshadowx** [comment]
> Didn't find any artifacts: https://github.com/theshadowx/notes/actions/runs/45817715

You should compile it in your machine

**Comment by nuttyartist** [comment]
Aw oops, haha sorry. Will do and report later.

**Comment by bjorn** [comment]
@theshadowx Ah, the bug was already fixed in qautostart (see https://github.com/b00f/qautostart/commit/1c99161e0746fdee1c78fcf5f9c69ecf87e152ec), but we need to update our submodule since it still points at an older commit!

**Comment by nuttyartist** [comment]
@theshadowx I just tested your branch and when I click on "Start automatically" from the 3 dots menu, it shows this pop up (probably because of new securities methods macOS is using:
![Screen Shot 2020-02-29 at 10 21 43 AM](https://user-images.githubusercontent.com/16375940/75604137-67447280-5ade-11ea-9303-f66f6030f75a.png)
But then I check in Login Items (where applications that start at login are to be found) and Notes isn't added there.
