### ISSUE TITLE
Bug related highlighting search text

### ISSUE THREAD

**Issue by b00f** [nuttyartist/notes#202]
![screenshot from 2018-03-06 16-04-26](https://user-images.githubusercontent.com/8073510/37020796-12dc4d7e-2158-11e8-867d-318c23684951.png)
How to produce it:
1- search for a text
2- got to text and put cursor on it
3- press Alt+tab to switch the window
4- back to notes 
5- all text are highlighted!

**Comment by nuttyartist** [comment]
I don't encounter this bug. On what OS are you getting this?

**Comment by b00f** [comment]
I fixed it. I could generate it in my PC (ubuntu 16.04)
