### ISSUE TITLE
Git sync between instances and platforms

### ISSUE THREAD

**Issue by mlanner** [nuttyartist/notes#206]
Given the cross-platform nature of Notes and the fact that notes generally are of "lightweight" nature, having a backend like Git to "sync" to would be incredibly useful. An option to pick between different Git servers, Github, Gitlab or simple standalone, would be great. It would then also be possible to set up multiple repos and share them among teams.

**Comment by theshadowx** [comment]
Hi @mlanner , you mean the notes (documents) to be stored through git and then just to specify a server which will sync between the local notes and those in the server.

**Comment by mlanner** [comment]
@theshadowx Yes, that's correct. Basically, the directory selected for Notes will become a Git directory if the app is configured with it. Then, for any outstanding changes, show a badge or something in the GUI to indicate notes not committed/pushed. A "save" command could be used to do the commit and push. If the user has checked a box "automatically commit and push without Git commit message", it would simply do the push without a Git comment.

**Comment by nuttyartist** [comment]
We have no plans on supporting Git sync. Our plan for automatic-sync is to make it as simple and intuitive for the user as it can be. Something like how Simplenote does syncing.

**Comment by mlanner** [comment]
@nuttyartist Got it. I think the key with sync is that users have an option to use a sync server under their own control. There are times when public cloud services aren't an option. 

@shadowx Might be a moot point, but something along the lines of what SparkleShare does generally works well for distributed users.

**Comment by nuttyartist** [comment]
@mlanner I get that some power users would want to host their own servers, but our target with Notes from the very start was that people from all backgrounds would be able to use it without fiddling around with it at all. All they need to do is just use it. Unfortunately, we can't satisfy all people, so some compromises will need to be taken. Hopefully, we're doing the right thing, driven by the very core of our product foundation.
