### ISSUE TITLE
Conflicting licenses?

### ISSUE THREAD

**Issue by nathreed** [nuttyartist/notes#21]
It seems that three source files (main.cpp, mainwindow.cpp, and mainwindow.h are licensed under the Mozilla Public License (as it says at the top of each respective file), but the project is licensed under the GNU LGPL. Is this intentional?

**Comment by nuttyartist** [comment]
It isn't. Thanks for noticing. I was wondering what would be a better option (And still).
As for now, I think we would go with LGPL. We also need to add the license to every source file.

You are welcome to share your thoughts about a suitable license.
I have wanted a license that says people can take the source code, and when they *change* the source code they need to put the changes back to the project, but anything they *add* doesn't need to be put back. Also, people can use it however they want, commercial or whatever, as long as they share their changes (not what they added on top of the source).

**Comment by nathreed** [comment]
I think the LGPL or the Mozilla license would be fine for the entire project. The GPL/LGPL does state that even new components need to be under the same license, so if you don't necessarily want contribution of additions, you might want a different license. The Mozilla license seems to allow combining of the licensed code with code licensed under a different (even proprietary) license, so if your definition of *add* is adding new files to the project, that sounds like those could be licensed differently by the author without having to be contributed back. It does seem like the Mozilla license is close enough to what you want. Note that I am not a lawyer, so my interpretation of the license terms may not be correct or have enough detail.

According to https://help.github.com/articles/open-source-licensing/, you don't need to put the license at the top of every file, you just need to make your intentions clear, which the LICENSE file in the project root does.

**Comment by nuttyartist** [comment]
Great info. I looked at this page http://choosealicense.com/licenses/ and I think Mozilla will do.
I will change the LICENSE file and close this issue.

**Comment by nathreed** [comment]
You might also want to change the COPYING file in packaging/linux/deb/notes-0.8.0 to the Mozilla license as it is still the LGPL.

**Comment by nuttyartist** [comment]
Right. Fixed that.

**Comment by AyushExel** [comment]
Hey, just noticed this project. I want to use this as a base and add some NLP capabilities. I intend to publish everything on GitHub, nothing commercial. Can I do that under the current license? I got confused by this:

>  and when they change the source code they need to put the changes back to the project, but anything they add doesn't need to be put back
