### ISSUE TITLE
Note is not moved top when going back from search

### ISSUE THREAD

**Issue by theshadowx** [nuttyartist/notes#210]
While searching, if there is just one note as result, and later been modified, when going back to normal mode, this note is not moved to the top.

**Comment by nuttyartist** [comment]
I can't seem to reproduce this. Would you mind uploading a video?

**Comment by theshadowx** [comment]
here are the steps:
search something that will find just one item in the notelist.
modify it.
clear the search.
you'll notice that this note is note first in the list.

**Comment by nuttyartist** [comment]
I still can't succeed in reproducing this. When I try to modify the note while in search mode -- when I click the note -- I immediately get into normal mode, and then when I'm modifying the note, it's working properly and the note goes to the top of the list.

**Comment by nuttyartist** [comment]
Reproducible.
