### ISSUE TITLE
ctrl+delete shortcut

### ISSUE THREAD

**Issue by jmoiron** [nuttyartist/notes#214]
ctrl+delete is "delete the next word" basically everywhere (certainly, on linux) except this app, so occasionally I will muscle-memory delete a few entire notes seemingly permanently by accident instead of deleting a few words.

**Comment by theshadowx** [comment]
The solution for this is to add option that the user can configure his/her own shortcut.

**Comment by jmoiron** [comment]
The database in the path i described is completely empty.  Last modified date is Mar 18 month.  There is no data in it.  Is there another path for `notes.db`?

**Comment by theshadowx** [comment]
what are the files you have in ~/.config/Awesomeness/

**Comment by nuttyartist** [comment]
I think we can change the shortcut to `ctrl+shift+delete`, what do you think @jmoiron @theshadowx?

The location where the database is stored is in ~/.config/Awesomeness/ like @theshadowx said, you can view and edit the content using an app that can view and edit sql databases. Sorry for your inconvenience, we'll have a Trash folder presented in our app on our next release.

**Comment by stevenkampen** [comment]
Can we get instructions on restoring them? Just lost two full pages.

**Comment by stevenkampen** [comment]
@nuttyartist Thanks, but I found them! (`~/snap/notes/4/.config/Awesomeness/Notes.ini`).

**Comment by nuttyartist** [comment]
Great! @stevenkampen

**Comment by theshadowx** [comment]
it's weird that you have Notes.ini (old version)
@jmoiron unfortunately we have some issue concerning the snap installer in the repo, so we can't add the most recent version of Notes in it.

so it's better to grab the latest snap version from https://github.com/nuttyartist/notes/releases section

**Comment by ShanikaEdiriweera** [comment]
I agree with this issue. Same happened to me today. I think ctrl+delete shortcut should be removed because in common text editors ctrl+delete would delete the following word. So the users are used to that functionality. :)

**Comment by nuttyartist** [comment]
@ShanikaEdiriweera Heard loud and clear, we'll change this shortcut. Maybe to ctrl+shift+delete? Nonetheless, in the future version, we'll have a Trash folder to easily restore your deleted notes.

**Comment by nuttyartist** [comment]
Let's move the general discussion here @Waqar144, @theshadowx. I believe that users should be able to use Notes solely using the keyboard if people want to. This is why I wanted to have a shortcut for deleting notes. But Ctrl+delete is to easy and therefore dangerous for notes deletions (although we never delete a note, just put it in a currently invisible trash folder), so this is why it's better to implement ctrl+shift+delete.

Regarding the implementation, you are welcome to discuss it at the PR.

**Comment by Waqar144** [comment]
`Ctrl+Shift+del` wouldn't work on windows (and maybe on some linux distros too) or any other OS where that is being used as a global shortcut.

**Comment by nuttyartist** [comment]
Ahh ok. I think we need to have a shortcut with a combination of 3 keys so not to make it easy to delete your notes by mistake. What do you think? Ctrl+A+D? Ctrl+D+E?

**Comment by Waqar144** [comment]
`Ctrl + Del` is a very common shortcut in editors so that's why people ended up accidentally deleting their notes. `Ctrl + A +D`, can work but its making it more difficult than necessary(when a user does want to delete a note/multiple notes). IMO, `Ctrl + D` should be okay because it's not a common shortcut and its hard to accidentally press that.

**Comment by theshadowx** [comment]
as @jmoiron  proposed, I think fn+D won't create any issue throughout the OSes.
And also add option to let the user to set their own shortcuts.

**Comment by Waqar144** [comment]
> And also add option to let the user to set their own shortcuts.

I think a separate issue/PR would be a better for that. It will take a while to write it + i don't know what the UI design for it should be like.

**Comment by nuttyartist** [comment]
Okay, I'm siding by your proposed Ctrl+D option. @Waqar144 Can you implement that in #235?

And like @Waqar144 we need to first think about how to incorporate that in the UI. @theshadowx you can open a new issue about it and we can discuss it there. I think it will be a welcome feature (I know I used oppose over customizability, but if done right I might be down for some).

**Comment by nuttyartist** [comment]
Done on #235.
