### ISSUE TITLE
desktop file does not pass desktop-file-validate on Ubuntu trusty

### ISSUE THREAD

**Issue by probonopd** [nuttyartist/notes#218]
desktop file does not pass desktop-file-validate on Ubuntu trusty:

```
/tmp/.mount_appimaxeF66B/notes.desktop: error: value "1.0.0" for key "Version" in group "Desktop Entry" is not a known version
/tmp/.mount_appimaxeF66B/notes.desktop: warning: value "Utility;Application;" for key "Categories" in group "Desktop Entry" contains a deprecated value "Application"
```

References:
* https://travis-ci.org/AppImage/appimage.github.io/builds/397914644#L559
* https://github.com/AppImage/appimage.github.io/pull/662

**Comment by theshadowx** [comment]
https://askubuntu.com/questions/827361/error-value-5-1-2-for-key-version-in-group-desktop-entry-is-not-a-known-v

> Version of the Desktop Entry Specification that the desktop entry conforms with. Entries that confirm with this version of the specification should use 1.0. Note that the version field is not required to be present.

**Comment by probonopd** [comment]
1.0 would be ok, but 1.0.0 is not. But as the field is not required, we can also just omit it.

**Comment by theshadowx** [comment]
yes, I just quoted the passage talking about the version in https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html
