### ISSUE TITLE
notebooks

### ISSUE THREAD

**Issue by allaga** [nuttyartist/notes#22]
hey :)

in the future there will be a separate notebook, such as "Plans", "Events" and others?

**Comment by nuttyartist** [comment]
Yes. It will be called folders. This feature can be found in the future list of features on the website, yet for right now, we want to tackle the current feature/issues related to the 1.0.0 version, so I will close this issue and create all the issues related to the future features when the time is right.

Folders is a feature I'm really excited to have in Notes. We gonna get there, doing things the right way.
