### ISSUE TITLE
All my notes were deleted

### ISSUE THREAD

**Issue by gabolucuy** [nuttyartist/notes#222]
Today when I opened the app I found out that all my notes are gone. According to ubuntu software the app was updated the 15 of july with this version: "0.9.0~gitb6e3b34", I use ubuntu 16. Please help me! I have very important info in my notes.

**Comment by gabolucuy** [comment]
Just find out the folder, restored it and everythig ok, if i could i would delete the issue but I can only closed it. Sorry.

**Comment by nuttyartist** [comment]
Glad you worked it out. We are trying our best to release a new version of Notes with Trash folder and put an end to this problem for many of our users.

**Comment by yusufbarisk** [comment]
Where did you find the folder? What is the name of the folder you found it?

**Comment by nuttyartist** [comment]
Hey @yusufbarisk!
You can find it at:

**Windows** : C:\Users\user\AppData\Roaming\Awesomeness
**Linux**       : /home/user/.config/Awesomeness/ or /home/snap/notes/x1/.config/Awesomeness (using snap)
**Mac**         : /home/.config/Awesomeness/
