### ISSUE TITLE
Should we drop support for .deb, .rpm, .snap and only support AppImage for Linux?

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#224]
That's a question I've been asking myself for quite a time. It will be much easier to maintain one Linux package than four, each with his own building needs and testing. AppImage could help us solve this. Of course, it will make sense to support Automatic Updates #170 and we'll need to solve some issues first #132.

What do you think?

**Comment by theshadowx** [comment]
I think it's better to keep them, as appImage is not an official package. So if a linux distribution wanted to include this app. we'll have already a process generating this package.

you have chosen the only package that is not official in any linux distribution ;)

**Comment by nuttyartist** [comment]
Yes, I know it's not official, but maybe it should be the new standard. Do you know if AppImage works on all/most distributions? Also, what's your opinion about the package itself, do you think it's good?

And is your opinion about not supporting it because it's not official, is it because it won't be able to live inside the popular distributions App Stores? That's also an important thing to consider.

**Comment by theshadowx** [comment]
In general, the scripts to generate this packages, it's done just once and never looked into it again, unless there is a big modification happened.

it's good to use AppImage or Flatpak as experimentation, but as long the linux distributions haven't agreed on one type of package. We are obliged to use support all of them.

**Comment by nuttyartist** [comment]
Staying with .deb, .rpm, .snap, etc... Closing.
