### ISSUE TITLE
possibility of reducing the list of notes

### ISSUE THREAD

**Issue by raingart** [nuttyartist/notes#226]
possibility of reducing the list of notes, like in [Nvpy](https://github.com/cpbotha/nvpy)

![screenshot from 2018-11-08 12-21-19](https://user-images.githubusercontent.com/13064767/48192580-dda0ec80-e350-11e8-841e-85364df95235.png)
![screenshot from 2018-11-08 12-21-31](https://user-images.githubusercontent.com/13064767/48192582-dda0ec80-e350-11e8-85bd-b3f35ee68220.png)

**Comment by nuttyartist** [comment]
Thanks for your suggestion @raingart.

Why would you want this feature?

**Comment by raingart** [comment]
@nuttyartist with a large number of notes, they need to scroll and I'm too lazy

**Comment by nuttyartist** [comment]
Gotcha. I think I like this idea. I'll be sure to take a good look at and give users the option to choose their notes "Display Density" - so we'll have an option between "Default" (current), "Compact" (your suggestion), "Comfortable" (larger white space). I'll create a new issue for this. Thanks!
