### ISSUE TITLE
Buttons icons not displayed on Linux

### ISSUE THREAD

**Issue by meradoou** [nuttyartist/notes#24]
Icons are not showing in buttons on some Linux machines.

A collection of the machines reported that issue:

- Archlinux  64bits / Plasma 5.5
- Ubuntu 15.10, 64-bit

**Comment by nuttyartist** [comment]
That's an issue I got from a bunch of people.
I'm gonna change the title and info to be general Linux.

**Comment by meradoou** [comment]
ok

**Comment by theshadowx** [comment]
this issue exists because the icon is loaded using its absolute path:

```
:/images/magnifyingGlass.png
```

This will look for the icon in the system / folder

the solution is to use relative path:

```
:images/magnifyingGlass.png
```

**Comment by nuttyartist** [comment]
Ah. I will check this out tomorrow. Thanks.

**Comment by theshadowx** [comment]
Have a look at the modification I made in [dev branch](https://github.com/theshadowx/notes/tree/dev)

**Comment by nuttyartist** [comment]
Wow, nice amount of commits. I have tried running your dev branch and saw some problems:

- Notes first line not eliding quite well.- it looks like the length isn't changing according to the size of note button.
- Notes buttons don't look like they should - when hovered there shouldn't be 'whitepsace' between notes and the separate lines should get hidden.
- When pressing the notes something wierd happens with the highlighting of them.
- ScrollBar don't look right.
- Some other problems

But looking at your code there are a lot of interesting things. I really like what you did with layouting the notes layout with the scrollArea and other welcomed changed to the code.

Can you make your branch version look and feel of the original program (with your welcomed changes to the code you made)? Nevertheless, I will look into all the commits you have made and merge them carefully into the master. It would ease the process a bit if your branch would look and feel like the original.

Thanks for contributing.

**Comment by theshadowx** [comment]
yes I've noticed some of these issues.

Could you create [gitter](https://gitter.im/) room linked to this repository in order to discuss without using issues section

**Comment by nuttyartist** [comment]
Yes. Invited you.

**Comment by theshadowx** [comment]
I'm in

**Comment by gkbrk** [comment]
I don't have this issue on Archlinux 64-bits / i3.

**Comment by peterchibunna** [comment]
Can you build an update or help me to build, so I can be doing the testing. I love this app but it freezes more than a lot. Where's the location of notes so we can make a back up and not lose the notes?

**Comment by nuttyartist** [comment]
> Can you build an update or help me to build, so I can be doing the testing. I love this app but it freezes more than a lot. Where's the location of notes so we can make a backup and not lose the notes?

You packed up a lot of things right there.
Let me see if I understand you correctly. You want to test/use the app but it freezes a lot, so you want to know the location of where the notes are stored?

- Could you elaborate more on the way the app freezes for you by creating a new issue?
- The notes location are stored in Linux in: /home/user/.config/Awesomeness/
On Windows they are in: C:\Users\user\AppData\Roaming\Awesomeness

**Comment by peterchibunna** [comment]
Thank you for your response. I need to know how to build/package the app from this source. I also needed to know the location of the notes in any case things go awry on my system when I'm packaging [after you've taught me].

**Comment by nuttyartist** [comment]
The easiest way to **build** the app is to download and install QtCreator from here: http://www.qt.io/download-open-source/
Packaging to .deb is a bit complicated to explain for now because we don't use automatic scripts (yet), so I won't describe it here.

I don't quite understand what you are trying/want to do.
Let's not spam this issue anymore.
You (and others) welcome to chat in our gitter room:
https://gitter.im/nuttyartist/notes
