### ISSUE TITLE
Can't locate Travis generated packages, for 1.5.0 release

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#248]
For some reason, I can't find the links to where Travis upload the generated packages. For example for the AppImage package: https://travis-ci.org/nuttyartist/notes/jobs/643738967

@Waqar144, @theshadowx, @bjorn Can you help?

I want to release version 1.5.0 today/tomorrow.

**Comment by theshadowx** [comment]
If I recall correctly, the package will be generated only when dev branch is merged the the master one. Need to be checked !

**Comment by nuttyartist** [comment]
Is it a requirement of Travis? Can we change that?

**Comment by bjorn** [comment]
> If I recall correctly, the package will be generated only when dev branch is merged the the master one. Need to be checked !

[According to this section](https://github.com/nuttyartist/notes/blob/bdc6dbf17a2c9a7ea36fee6956ef4b7c617a5729/.travis.yml#L79-L103) the builds are always uploaded, just with different names depending on whether it's building the `master` branch or another branch.

However, after successful upload transfer.sh is supposed to output the URL, and instead the log reads "Could not save metadata" three times. This appears to be a problem at Transfer.sh, see the error in their server-side code here:

https://github.com/dutchcoders/transfer.sh/blob/b90bd685e75bb77563e3749dcf0729a8aabb7bb3/server/handlers.go#L322-L324

I'm not sure what triggers this, but I guess [setting up an alternative deployment method](https://docs.travis-ci.com/user/deployment) would be a solution if you want to release fast. For example, why not [upload directly to GitHub](https://docs.travis-ci.com/user/deployment/releases/)?

**Comment by nuttyartist** [comment]
@bjorn Will it upload directly to Github releases on every commit? I used to see these repos with an alarming number of release versions. If we can avoid this clutter, the better. Or maybe you're not talking about this? There's also this "Github Workflow" thing, but I don't know how straightforward it is to move from Travis to this.

**Comment by bjorn** [comment]
> Will it upload directly to Github releases on every commit?

Only if you tell it to, but generally you'll set up this deploy rule to deploy only for tags. That's what this part in the deploy section does:
```yml
  on:
    tags: true
```

> There's also this "Github Workflow" thing, but I don't know how straightforward it is to move from Travis to this.

Yes, you could also set up GitHub Actions, but adding the deploy rule on the existing Travis CI setup should be a lot easier / faster. If you [install the Travis command line client](https://github.com/travis-ci/travis.rb#installation) then you can use that to [setup the initial deploy section](https://docs.travis-ci.com/user/deployment/releases/#using-travis-ci-client-to-populate-initial-deployment-configuration).

**Comment by nuttyartist** [comment]
> but generally you'll set up this deploy rule to deploy only for tags.

That should be good. Can you take care of this? I've no idea how to do that. (I invited you to be a collaborator).

**Comment by bjorn** [comment]
I've noticed we can also automatically [upload the snap to the Snap Store](https://docs.travis-ci.com/user/deployment/snaps/) from Travis CI. I see currently the snap is still at version "0.9.0~gitb6e3b34 2017-05-17". Why wasn't at least 1.0 uploaded there?

We should probably try to set it up such that tags go to `stable` channel and commits to `dev` branch to go the `edge` channel.

**Comment by nuttyartist** [comment]
Good catch. I think we forgot updating there.  It'll be good to upload directly to Snap Store.

> We should probably try to set it up such that tags go to stable channel and commits to dev branch to go the edge channel.

When you say channel, where do you take about? Or you're just talking generally? If so, I agree.

**Comment by bjorn** [comment]
> When you say channel, where do you take about? Or you're just talking generally? If so, I agree.

No I'm talking about [snap channels](https://snapcraft.io/docs/channels), where `stable` and `edge` are called risk levels apparently.

**Comment by theshadowx** [comment]
Hi @bjorn , the issue is that we weren't the ones that uploaded the snap to the snapstore, but @dplanella, unfortunately we are not admins of that account thus we can't update the package.

**Comment by Waqar144** [comment]
> Hi @bjorn , the issue is that we weren't the ones that first uploaded the snap to the snapstore, but @dplanella, unfortunately we are not admins of that account thus we can't update the package.

That's rather unfortunate. Maybe @dplanella is still around to help with this.

**Comment by nuttyartist** [comment]
@theshadowx Oh right, I thought we're talking about AppImage for some reason hah. We gotta do something about that. I tried contacting him but to no avail. I'm gonna try contacting him again while filing a dispute for the ownership of the name "notes" in the store.

**Comment by nuttyartist** [comment]
Now that the ownership for notes on the snap store was transferred to us, we can set up uploading the snap automatically using Travis. Whatever info you need for that, @bjorn, let me know.

**Comment by bjorn** [comment]
@nuttyartist I'll let you know when I have some time again, but until then you could at least release 1.0.0 there. :-)

**Comment by nuttyartist** [comment]
Indeed. Great 👍

**Comment by theshadowx** [comment]
I have updated travis script, but there is an issue concerning snapcraft.yml: the current state of the file doesn't include libraries for sqlite, I'm trying to fix it.

**Comment by nuttyartist** [comment]
I'm gonna close this issue and open one related to snap.
