### ISSUE TITLE
Snap Store registration request

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#251]
As requested from our email conversation from Snap Store representative, in order to verify my identity, I created this issue and ask @dplanella if it's ok to transfer the ownership of the app name "notes" to our hands, so we can keep on updating our app as we wish, independently.

Thanks (:

**Comment by dplanella** [comment]
Thanks for reaching out. From previous conversations, I can verify @nuttyartist's identity as the "notes" developer, to whom the ownership of the app name "notes" should be transferred to.

Please let me know if there's anything I can do on my end.

**Comment by nuttyartist** [comment]
Thank you, @dplanella! Glad we managed to solve this :)
