### ISSUE TITLE
undefined symbol: FT_Done_MM_Var

### ISSUE THREAD

**Issue by s0kil** [nuttyartist/notes#252]
Getting this error:
```
$ ./notes_1.0.0_amd64.AppImage
./notes_1.0.0_amd64.AppImage: symbol lookup error: /lib/x86_64-linux-gnu/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var
```

I have tried extracting the appimage as shown [here](https://github.com/prusa3d/PrusaControl/issues/115), and as mentioned in that issue -

> not bundling libfreetype in the AppImage will resolve this issue.

**Comment by bjorn** [comment]
Notes 1.0.0 was released on Aug 16, 2017, quite a while before fix https://github.com/AppImage/pkg2appimage/commit/9082bbe3b924b656d8675da64a69c6b2b32ac7b4 was made.

Work is currently ongoing to make a Notes 1.5 release, which will use the latest `linuxdeployqt` to create the AppImage, so it should take care of this issue automatically.

**Comment by theshadowx** [comment]
I have got this issue, you should use Xenial version, this is due to linuxdeployqt is not updated : 
https://github.com/probonopd/linuxdeployqt/issues/340

**Comment by s0kil** [comment]
I was not sure if the Xenial version would work with 19.10 (Eoan Ermine), but it does thank you @theshadowx

**Comment by theshadowx** [comment]
I have tested with Bionic and it worked. I'm going to try it right now

**Comment by theshadowx** [comment]
it worked : https://transfer.sh/u1WY4/notes_1.0.0-git859ac15_amd64.AppImage

**Comment by nuttyartist** [comment]
Thanks, @theshadowx! @s0kil Did it solve the issue?

We're on the verge of finishing up a much more up-to-date release - 1.5.0 soon. (:

**Comment by s0kil** [comment]
@nuttyartist Yes, the Xenial version works without a problem.

**Comment by nuttyartist** [comment]
@s0kil Great, closing...
