### ISSUE TITLE
Use a submodule for QSimpleUpdater

### ISSUE THREAD

**Issue by bjorn** [nuttyartist/notes#253]
It looks like https://github.com/nuttyartist/notes/tree/dev/3rdParty/QSimpleUpdater should really be a submodule pointing to https://github.com/alex-spataru/QSimpleUpdater. This would make future updates easier.

Likely we'd also benefit from the changes made to the library in the past three years.

@alex-spataru Would you be available to make this change?

**Comment by theshadowx** [comment]
I think it would be better that @nuttyartist fork the QSimpleUpdater , and from there to be submoduled,   so that if there is modifications specific to notes, it would be easy to apply them, what do you think @bjorn ?

**Comment by bjorn** [comment]
I would only do that if there are any modifications that we couldn't upstream.

**Comment by nuttyartist** [comment]
@bjorn We already such modifications, like UI and text changes. I think it makes sense to do as @theshadowx proposed unless you think the repo is flexible enough for our needs.

**Comment by bjorn** [comment]
@nuttyartist I'll try to run a diff to see what changes those were.
