### ISSUE TITLE
Problem generating snap package

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#257]
As mentioned in #248, there still some problems generating snap packages using Travis.

**Comment by nuttyartist** [comment]
@theshadowx @bjorn We still don't have snap artifacts for v1.5.0?

**Comment by theshadowx** [comment]
I have been able to make snap works correctly, I will upadre the .pro file also as snap folder will be moved to the root folder. Here is the branch specific to the snap modifications. It's not up to date, I'll update it this evening:
https://github.com/theshadowx/notes/tree/snapcraft

**Comment by nuttyartist** [comment]
Awesome, then we'll continue to release v1.5.0.

**Comment by theshadowx** [comment]
I think this should be closed

**Comment by nuttyartist** [comment]
Okay, is it fixed? I can't see a link for the snap in https://travis-ci.org/github/nuttyartist/notes/jobs/662820085, but I guess it's because the release isn't tagged yet?

**Comment by theshadowx** [comment]
The package is generated at the bottom : https://transfer.sh/e8xr4/notes_1.0.0-git5ca3205_amd64.snap

**Comment by bjorn** [comment]
Unfortunately the link is already giving 404 error. However, indeed the original issue described in https://github.com/nuttyartist/notes/issues/248#issuecomment-588522356 that prompted the opening of this issue was fixed by #259, so we can close this.
