### ISSUE TITLE
User report inability to migrate his old notes to new version.

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#265]
A user reported that his old notes didn't migrate to the new version of Notes here: https://www.get-notes.com/single-post#comment-4858696357. I tried to walk him through solving it but didn't succeed. 

@theshadowx do you have suggestions as to how solve this problem?

**Comment by theshadowx** [comment]
I need his notes to check why there is an issue, or sample of his notes.

**Comment by nuttyartist** [comment]
Okay, I let him know. Waiting for his response.

His description of the problem:

> Firstly I would like to thank you all for developing this app in Ubuntu. I love it. 
>
> I have recently updated Notes to yhe latest version 1.0.0 (earlier version was 0.9.0). After the update, the new version does not restore my old notes. On opening the local Notes folder ( /home/user/.config/Awesomeness/ ) I see the older notes are saved as "oldNotes.ini" and a new file "Notes.db" is created.
>
> Following the suggestion as received while discussing the same issue in "Notes Blog" webpage, I replaced the "Notes.db" file with "Notes.ini".  On doing so, still the new version does not restore the old notes. I find  that the latest version does not read files with ".ini" extension.
>
> Is it possible to restore them in new version? Please suggest. 
>
> P.S. For now, I am continuing with the older version. I do like to update to latest version to avail the new features.

**Comment by theshadowx** [comment]
Can you ask to open Notes from terminal and send the message shown there.
Also was snap used or deb package ?

**Comment by tan10vir** [comment]
> I need his notes to check why there is an issue, or sample of his notes.

Attached is a sample of "Notes.ini" 
[Notes.ini.txt](https://github.com/nuttyartist/notes/files/4439538/Notes.ini.txt)

As ".ini" files cannot be uploaded here, so just added a ".txt" extension to the file. Please drop the extension when you use it.

**Comment by tan10vir** [comment]
> Can you ask to open Notes from terminal and send the message shown there.
it starts from terminal with no error. 

> Also was snap used or deb package ?
I am using deb package.

**Comment by theshadowx** [comment]
@tan10vir  it is working correctly

**Comment by tan10vir** [comment]
> @tan10vir it is working correctly
> ![Notes_005](https://user-images.githubusercontent.com/976569/78837759-9fe43f80-79ec-11ea-9f75-e41c0c7caae5.jpg)
Nice! 
I will try again, why is it not working in my machine.

**Comment by tan10vir** [comment]
@theshadowx I am stil facing the issue. Could you please tell me how did you get it to work correctly?

**Comment by theshadowx** [comment]
With the sample notes.ini you sent me ?
Have you used the deb from the release section ?

**Comment by tan10vir** [comment]
Yes, I am using the deb version. I have freshly installed the notes app (Downloaded the 17.10 Deb package).  I have done the same thing: copied notes.ini to the local folder and started the app. 

Opening it from the terminal, I do get the following message 
````
Database: connection ok
QSqlQuery::value: not positioned on a valid record
QSqlDatabasePrivate::database: requested database does not belong to the calling thread.
QSqlQuery::exec: database not open
QSqlDatabasePrivate::database: requested database does not belong to the calling thread.
````
After closing the app, I had to force stop the app in terminal too.

**Comment by theshadowx** [comment]
> Yes, I am using the deb version. I have freshly installed the notes app (Downloaded the 17.10 Deb package).  I have done the same thing: copied notes.ini to the local folder and started the app. 
> 
> Opening it from the terminal, I do get the following message 
> ````
> Database: connection ok
> QSqlQuery::value: not positioned on a valid record
> QSqlDatabasePrivate::database: requested database does not belong to the calling thread.
> QSqlQuery::exec: database not open
> QSqlDatabasePrivate::database: requested database does not belong to the calling thread.
> ````


This is what I was looking for.
You are using Qt version not suitable for 1.0.0, I think you are using version > 5.8
We have fixed this issue, but not yet released.

The solution is to use snap and move the notes.ini to the folder mentioned in readme.

**Comment by tan10vir** [comment]
> > Opening it from the terminal, I do get the following message
> > ```
> > Database: connection ok
> > QSqlQuery::value: not positioned on a valid record
> > QSqlDatabasePrivate::database: requested database does not belong to the calling thread.
> > QSqlQuery::exec: database not open
> > QSqlDatabasePrivate::database: requested database does not belong to the calling thread.
> > ```
> 
> This is what I was looking for.
> You are using Qt version not suitable for 1.0.0, I think you are using version > 5.8
> We have fixed this issue, but not yet released.
> 
> The solution is to use snap and move the notes.ini to the folder mentioned in readme.

Okay. Thanks a lot. 
I will wait for next version.  :) 
Thanks.

**Comment by nuttyartist** [comment]
@theshadowx Thanks a lot for figuring this out!

@tan10vir Like @theshadowx said you can move notes.ini to/home/snap/notes/x1/.config/Awesomeness (create the folder if it does not exist), and install the snap version from https://www.get-notes.com/linux-download. Or wait for the next version.

I'll close this for now.
