### ISSUE TITLE
Unable to zoom/change font size.

### ISSUE THREAD

**Issue by vaibhavahuja** [nuttyartist/notes#272]
Currently I feel that the font size is too low. I am unable to find an option to change the font size, and also am unable to zoom.
How can I do that?

**Comment by nuttyartist** [comment]
Hey @vaibhavahuja!

Are you talking about the font of the editor (where you write your notes) or where your list of notes is displayed?

Currently, we don't support increasing the font size in the editor, but it's something we are aiming to implement in future versions.

**Comment by vaibhavahuja** [comment]
I was talking about "where I write the notes"

> Currently, we don't support increasing the font size in the editor, but it's something we are aiming to implement in future versions.
Okay

**Comment by bjorn** [comment]
@nuttyartist Why close the issue, especially given that you said we want to do this in the future?

**Comment by Waqar144** [comment]
Also this is a very straightforward and simple thing to implement. Shouldn't take more than a couple of hours. I vote to mark this as good-first

**Comment by nuttyartist** [comment]
> @nuttyartist Why close the issue, especially given that you said we want to do this in the future?

@bjorn Just because I thought it should be part of an issue when we work on the "A button".

From the [wiki](https://github.com/nuttyartist/notes/wiki/Vision):
> 4. The 'A' button (Which we may change to a different icon) will open a pop up with these options:
> 
> - Increase/decrease font size
> - Toggle Focus Mode, which will let the user focus only on the current sentence and fade away other sentences (By Whitening/greying out their colors).
> - Toggle Typewriter Mode, which will make the current text appear always and only in the middle (like a typewriter).
> - Dark theme or Regular theme.

.
> Also this is a very straightforward and simple thing to implement. Shouldn't take more than a couple of hours. I vote to mark this as good-first

@Waqar144 Indeed, very simple to implement, but since it should be done in a proper UI as I wrote above, where there's a button that open-up a little pop-up with different options, it might not be as straightforward for first-time contributors.

**Comment by bjorn** [comment]
@nuttyartist Ah, so it's already covered elsewhere, thanks!
