### ISSUE TITLE
User report error when exporting and importing notes. Video included.

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#275]
For some reason, a user reported an error keep to arise while he tries to export and import his notes.
Here's a video: https://www.loom.com/share/c83fa2c480474db0a0820b3b0576d163

What can be the problem?

**Comment by Waqar144** [comment]
Seems like the file didn't have any notes:


https://github.com/nuttyartist/notes/blob/b17fe903311d3b6cbe618f4f4ac8afa22827865c/src/mainwindow.cpp#L1625-L1635

However, I am wondering why is there a `try / catch`

**Comment by nuttyartist** [comment]
Yes, that's what I assumed. That error is probably in the exporting. Because in the videos he shows he creates some notes.

But for me, exporting and importing works fine. @Waqar144 Have you tried exporting yourself and the file was empty?

**Comment by Waqar144** [comment]
> But for me, exporting and importing works fine. @Waqar144 Have you tried exporting yourself and the file was empty?

I did, but don't remember the outcome. I will try again to see what happens.

**Comment by nuttyartist** [comment]
Different user (#282 ) reports exporting and importing works now (after upgrading to version 1.5.0). Closing this till we get new reports.
