### ISSUE TITLE
Change margins when using native window frame

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#277]
Since switching to native window frame will reduce the margins at the top of the application, we shall reduce the margins around the text editor (left and right).

Comparison (via @bjorn):

![87253615-ef6b5900-c47c-11ea-85bd-bfc8c073cc59](https://user-images.githubusercontent.com/16375940/91201445-1c13c100-e709-11ea-81c3-3ed758c81479.png)
![87436075-d8e40f80-c5ec-11ea-9f39-7f55bbd2fdf7](https://user-images.githubusercontent.com/16375940/91201448-1ddd8480-e709-11ea-9244-5731f8424287.png)

**Comment by nuttyartist** [comment]
Not needed anymore. Closing.

**Comment by bjorn** [comment]
Just wondering, is it done or did you decide the existing behavior was fine?

**Comment by nuttyartist** [comment]
> Just wondering, is it done or did you decide the existing behavior was fine?

After #295, margins are set intelligently, based on [the width of textEdit (if the width is less than 800)](https://github.com/nuttyartist/notes/blob/dev/src/mainwindow.cpp#L3423-L3434), otherwise we pad the text (set margins) [just to put it in the middle of textEdit](https://github.com/nuttyartist/notes/blob/dev/src/mainwindow.cpp#L808-L829).
