### ISSUE TITLE
Clicking on native close button quits the app on Windows rather than hiding it

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#278]
Clicking on the red closing button on Windows quits the app, where it should just hide it (should keep on running using the system tray). It seems like the problem is upstream due to a newer version of Qt since I didn't find a change in the source code to lead to this and version 1.0.0 on the website works as expected. But we might solve this using a different code?

**Comment by nuttyartist** [comment]
Nevermind, I mistakenly used the native window closed button. Whoops.

**Comment by bjorn** [comment]
Hmm, but I guess it shouldn't matter which button you click? If you use the native window frame, the close button should probably still just hide the window.

**Comment by nuttyartist** [comment]
The close button of the native window provided by Windows? Really?

**Comment by bjorn** [comment]
Well, it's up to you I guess. I'm not sure if Notes has a good reason to stay active in the background. I guess the user can also click the try icon to hide the window, so maybe it's better that the close button actually closes (but then I think the same should happen by the custom close button).

**Comment by nuttyartist** [comment]
I don't think the same should happen, it is much faster to press Super+N to summon Notes right when an idea hit you.

> Well, it's up to you I guess.

Do you mean we can set the native close button to not quit the app but just hide it?

**Comment by bjorn** [comment]
> Do you mean we can set the native close button to not quit the app but just hide it?

Yes. When the user clicks that button, the window gets a close event. By default this closes the window and since it is the last window, quits the app. We could override this and hide the window instead.

**Comment by nuttyartist** [comment]
Oh, ok then! I'm reopening this issue.

**Comment by nuttyartist** [comment]
We should hide the app upon closing the window not quit it. Quitting will be possible through right-clicking the system tray or through the 3 dots button inside the app.
