### ISSUE TITLE
Can't see AppImage generated by Travis

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#279]
@theshadowx, @bjorn, @Waqar144  Do you know why Travis doesn't generate an artifact link for AppImage (actually, for all other packages also, but it seems like Github takes care of .deb and .snap).

https://travis-ci.org/github/nuttyartist/notes/jobs/723438922

**Comment by nuttyartist** [comment]
Also, @bjorn, @Waqar144 please let me know if it's okay to put your name and picture on the website contributors section! (:

**Comment by bjorn** [comment]
@nuttyartist Regarding the AppImage, it seems there's a somewhat unfortunate mismatch between
```
- if [ "$QT_BASE" == "appimage" ]; then
      mv Notes-*.AppImage notes_${NOTES_VERSION}_amd64.AppImage;
```
and
```
  file:
    - Notes-*.AppImage
```
(the file that was supposed to deploy to GitHub was renamed to something that doesn't match this pattern)

Depending on what we want, we should either adjust the pattern or change the `mv` into a `cp`.

> Also, @bjorn, @Waqar144 please let me know if it's okay to put your name and picture on the website contributors section! (:

Of course I'm fine with this, thanks!

**Comment by Waqar144** [comment]
> Also, @bjorn, @Waqar144 please let me know if it's okay to put your name and picture on the website contributors section! (:

Sure thing! :)

**Comment by nuttyartist** [comment]
Cool just updated the website (:

@bjorn, So because `notes_${NOTES_VERSION}_amd64.AppImage` is different than `Notes-*.AppImage`?

If so, feel free to change it to what you deem right. Preferably what is consistent with our other packaging flow.

**Comment by bjorn** [comment]
@nuttyartist I committed 4840afcf0ea87f9b9eecc849ef3e4ec2e36894d7, but to get it to push to GitHub releases I guess you'd have to re-tag. Not sure what the consequences of that will be. Alternatively, we could get it to upload somewhere else (transfer.sh doesn't appear to work after all) and you can manually put it on GitHub releases this time.

**Comment by nuttyartist** [comment]
> Alternatively, we could get it to upload somewhere else (transfer.sh doesn't appear to work after all) and you can manually put it on GitHub releases this time. 

Sounds good if possible. Otherwise, I'll re-tag as v1.5.1.

**Comment by bjorn** [comment]
> Sounds good if possible. Otherwise, I'll re-tag as v1.5.1.

Since nothing changed I'd just re-tag as v1.5.0.

**Comment by nuttyartist** [comment]
> Since nothing changed I'd just re-tag as v1.5.0.

I already linked the generated packages links to the website, will re-tagging it delete them?

**Comment by bjorn** [comment]
> I already linked the generated packages links to the website, will re-tagging it delete them?

Hmm, well I tried to force-push the tag to the latest commit in order to re-target it, which seems to have worked without losing the published release notes and files. However, it does not seem to have triggered a new build on Travis CI...

It seems there are also some build failures on Travis CI related to the PR #263. :-(

**Comment by nuttyartist** [comment]
So what can we do? Should we create a new tag? Or do we need to solve the build failures first, and then try a re-tag?

**Comment by guihkx** [comment]
@nuttyartist I believe this one can be closed, as it's not applicable anymore?

**Comment by nuttyartist** [comment]
Yep 👍
