### ISSUE TITLE
Sync with ownCloud (Notes) [$25]

### ISSUE THREAD

**Issue by jancborchardt** [nuttyartist/notes#28]
Quite awesome to see this desktop app @nuttyartist! Reading through the contribution document (and design reasoning) it’s very similar to how we designed the [ownCoud Notes app](https://github.com/owncloud/notes):
![](https://www.bitblokes.de/wp-content/uploads/2016/02/owncloud-notes2.jpg)

It also supports markdown with nice inline styling (see this older screenshot):
![](https://cloud.githubusercontent.com/assets/925062/8617889/a5e2238e-2708-11e5-95f3-a21329c10c69.png)
And there’s already very cool apps for [Android](https://play.google.com/store/apps/details?id=it.niedermann.owncloud.notes) and [iOS](https://itunes.apple.com/us/app/cloudnotes-owncloud-notes/id813973264?mt=8)

What would be very cool now is to sync it to a well designed desktop app like this one! :)
ownCloud speaks WebDAV for files (and notes are in the »Notes« subfolder) and there’s also an API for the Notes app: https://github.com/owncloud/notes/wiki/Api-0.2 – is that still current @BernhardPosselt @Henni?

**Comment by nuttyartist** [comment]
Hi @jancborchardt,
I'm trying to understand a few things.

Do you intend on making Notes sync by default with your existing app? 
Or are you suggesting that we use your infrastructure to build a sync service of our own? 

I can't seem to find the connection between your web app (and mobile apps), your infrastructure for making sync capabilities for notes (If I understand that correctly), and the relation to our own Notes app.

It would be helpful if you elaborate on what each thing is, and then the connection between them.

Thanks

**Comment by jancborchardt** [comment]
@nuttyartist essentially ownCloud is a WebDAV server. We do not have »infrastructure«, but ownCloud is open source software, widely deployed and there’s a bunch of providers and big users.

Your Notes app currently does not do any syncing, and enabling people to connect their ownCloud will instantly make sync available to a looot of people without you needing to care about any backend. Also, these people get mobile apps basically for free as well.

And for us, your Notes app is a great looking desktop client for our Notes app. We could do that either by the Notes app using the API / WebDAV, or by the app checking for an existing ownCloud desktop client and then checking for the Notes subfolder. Of course the first solution would make a bit more sense since it doesn’t rely on the ownCloud sync client being installed.

Do you know what I mean?

**Comment by jancborchardt** [comment]
@nuttyartist I just received the Gitter invite, but I’m probably not the best person to talk to about this as I’m mainly the designer. :) Best come join our #owncloud-dev IRC channel (on freenode), where @Henni (as Rekhyt), @BernhardPosselt and @LukasReschke also hang out.

**Comment by nuttyartist** [comment]
The result of our discussion is that the best thing for Notes might be to fork Owncloud Notes and create our own server for syncing. We will open a new issue about syncing when we'll start working on future version of Notes and get more into the details and discuss more thoroughly about it.
So I'm closing this issue.

**Comment by jancborchardt** [comment]
Hm, that’s a bit unfortunate I guess since it will vastly overcomplicate things for any user. Why fork ownCloud Notes? It’s an ownCloud app already, and ownCloud is installed in so many places. Also it just uses WebDAV, so if you implement WebDAV for syncing you get so many servers for free. No need to do yet another protocol.
But yeah, your choice.

**Comment by nuttyartist** [comment]
By forking, I don't mean creating another ownCloud Notes, but to use its technology in order to create something different in our way. And I don't know yet about protocol and stuff, we'll get technical when the time comes, but I do know that I want to have a central server that would just work at syncing notes for users (like simplenote). So it's not at all about complicating things, but the complete opposite. And there is also the reason of how we see things that're unaligned to how you see things, I don't think we have a shared vision, and I want to have the ability to create things freely in our own way.
When we'll start working on syncing we'll look into all the available options, so things are not closed like this issue yet (:

**Comment by jancborchardt** [comment]
Aah ok, I understand. Thanks for the clarification. : )
