### ISSUE TITLE
User report error while importing notes

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#282]
> Hello
> I have recently upgraded to version 1.5 and I am trying to import some old notes that where saved to an .nbk file by version 1. When I try to do that, a message pops up saying to select a valid notes export file, and the old notes are not imported.
> Is there anything I can do to get my old notes back?
>
> also: This is a great app, thank you for making it available for everyone.
> I am using Ubuntu 18.04

Screen capture: 
[screen-capture.mp4.zip](https://github.com/nuttyartist/notes/files/5296691/screen-capture.mp4.zip)

How can we assist him?

**Comment by Waqar144** [comment]
Not 100%, but we probably can't. The notes backup file doesn't look valid (only 9kb) meaning the notes weren't backed up correctly in the first place.

**Comment by nuttyartist** [comment]
@Waqar144 Why are you assuming it's not valid - only because it's 9kb?

I'll try to see if he can share the backup if it doesn't contain sensitive/personal information.

**Comment by Waqar144** [comment]
> @Waqar144 Why are you assuming it's not valid - only because it's 9kb?

That and the error. The export could have gone wrong, which may have resulted in an incomplete / invalid backup file.

**Comment by nuttyartist** [comment]
Okay, I'll see what information I can get from him to better examine this. For me exporting and importing works well.

**Comment by nuttyartist** [comment]
The user was kind enough o share his notes.

[notes.nbk.zip](https://github.com/nuttyartist/notes/files/5311037/notes.nbk.zip)

I got the same error while trying to import. @Waqar144 Do you think can detect where the error is coming from?

**Comment by Waqar144** [comment]
Its can be an incorrect export or some other reason like the file getting tampered etc. Anyways, I recovered the text that was in the file.

**Comment by nuttyartist** [comment]
@Waqar144 How did you do it? I managed to do so but didn't get a clean result.

@theshadowx maybe you can shed some light on a problematic structure of the file or something?

**Comment by Waqar144** [comment]
> @Waqar144 How did you do it? I managed to do so but didn't get a clean result.

Just pull out all the printable characters and you get the data back.

**Comment by nuttyartist** [comment]
@Waqar144 Ok.

It is strange because two people reported this problem already (https://github.com/nuttyartist/notes/issues/275).

**Comment by nuttyartist** [comment]
The user reports exporting and importing works now (after upgrading to version 1.5.0). Closing this till we get new reports.
