### ISSUE TITLE
Show sidebar

### ISSUE THREAD

**Issue by allan-mlpe** [nuttyartist/notes#285]
Hello everyone,

I'm facing some troubles to get the sidebar (containing the list of notes) again after hiding it somehow :eyes: 

Is there any shortcut to display it again? I've tried the shortcuts listed [here](https://www.get-notes.com/), but with no success...

I'm using Ubuntu 20.04.1. Notes version: `0.9.0~gitb6e3b34`.

Thanks in advance!

**Comment by nuttyartist** [comment]
I need to update the website! Sorry for that. You can use `Ctrl + J` on Windows or `Command + J` on Mac.
Also, from the 3 dots menu on the upper right corner of the app, you can choose View->Show notes list.

**Comment by allan-mlpe** [comment]
Thank you so much for your reply!

On Linux Ubuntu `Ctrl + J` didn't work, however I could to get it again placing the mouse cursor on the left edge until a `<-->` symbol appears. So when I click, hold and move to the right, the sidebar is displayed again!

Also, I think my version doesn't have the three dots menu, it looks like this:
![Captura de tela de 2021-01-26 09-19-33](https://user-images.githubusercontent.com/10046404/105844235-a9f52000-5fb7-11eb-92d5-8672fdda4102.png)

**Comment by nuttyartist** [comment]
Ah! You are using an old version of our app. Indeed, pushing it to the right should work! You can get the latest version on our [website](https://www.get-notes.com/) if you'd like.

**Comment by copperwiring** [comment]
@nuttyartist I just resolved the same issue because I had an older version. If I update the app will my previous notes be lost?

**Comment by nuttyartist** [comment]
@copperwiring They should not! But just in case, make sure to backup your database, copy the notes.db/notes.ini stored in:

Windows : C:\Users\user\AppData\Roaming\Awesomeness
Linux       : /home/user/.config/Awesomeness/ or /home/snap/notes/x1/.config/Awesomeness (using snap)
Mac         : /home/user/.config/Awesomeness/

**Comment by copperwiring** [comment]
Thanks, @nuttyartist !
