### ISSUE TITLE
Ability to disable markdown

### ISSUE THREAD

**Issue by tanabi** [nuttyartist/notes#287]
Hey there;

I'm not sure how feasible this is, but if there were a settings check box, command line argument, or environment var (or really any method) of turning off Markdown I would be happy.

My reason: I use notes extensively, and about 75% of the time it is just literal notes.  Like stuff I'd put on a post it note, nothing with any formatting, and this works fine.

About 25% of the time I'm actually storing *code* snips.  And those snips often have markdown characters in them.  I never use markdown for any purpose in a note and never will; while I could try using markdown code blocks, in my use case it would be simpler to just always treat the text as text.

Sometimes apps are smarter than they need to be :)  However if this is a massive effort or not feasible, then feel free to note it and close this issue.  Obviously I can work around it in a number of ways, it's just a nice to have.

**Comment by nuttyartist** [comment]
Hi, @tanabi! Sure, I think it is a good idea! We can put it under View -> Markdown. It should be easy.

**Comment by tanabi** [comment]
Cool!  Thank you :)

**Comment by nuttyartist** [comment]
Done in #291
