### ISSUE TITLE
Allow changing database path, and synchronization across devices

### ISSUE THREAD

**Issue by vlasky** [nuttyartist/notes#289]
Hello,

Thank you for creating notes! I am a daily user and I think it's great!

One thing missing is the ability to have my collection of notes accessible from my various PCs (home and office).

I currently use [Syncthing](https://syncthing.net/) under Windows to create a shared folder between several of them.

I would love for notes to have a setting that specifies a custom location for the notes.db file, so I can point it to my Syncthing shared folder.

Notes should also detect when the notes.db file is modified externally (i.e. after the shared folder is synchronized with a remote PC) and then refresh itself.

I'm sure this would be a popular feature.

**Comment by nuttyartist** [comment]
Hi, @vlasky!

While I was reluctant in the past to do such a thing, it makes sense to allow people this option. 
I'm adding this to our to-do list.

> Notes should also detect when the notes.db file is modified externally (i.e. after the shared folder is synchronized with a remote PC) and then refresh itself.

I think this should be the hardest part. Checking for conflicts and how to handle them.

**Comment by theshadowx** [comment]
@vlasky here is how you can do it with dropbox : 
https://github.com/nuttyartist/notes/issues/109#issuecomment-276342071

**Comment by nuttyartist** [comment]
Yes, just be aware that Notes will not check and handle conflicts (say when the same notes changed offline on one device later changed on the other device, when later synced online there gonna be conflicts).

**Comment by nuttyartist** [comment]
Done in #302.
