### ISSUE TITLE
Help needed implementing Themes (ie, Dark mode) on notesList model/view

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#292]
Having introduced themes in #295, I'm having a problem updating the color of the notes list (noteView) when the user chooses a different theme (ie, Dark). I guess I'm not sure what's the proper way of updating the delegate/model.

I didn't touch C++ for a while so I'm a bit rusty.

Can someone help with this?
@akud82, @bjorn , @theshadowx, @Waqar144

**Comment by akud82** [comment]
It's important to emit the dataChanged() signal. 
Delegate doesn't know that you change color and you need to emit event to force repaint.

**Comment by nuttyartist** [comment]
I tried this (in mainwindow.cpp): 

```emit m_noteModel->dataChanged(m_proxyModel->index(0,0), m_proxyModel->index(m_proxyModel->rowCount()-1, 0));```

But it doesn't work. I gotta say I have not much clue about the Model/View methodology.

**Comment by nuttyartist** [comment]
Done in #302.
