### ISSUE TITLE
Please develop text encoding file for ubutu text editor. so, that exported file can be open with simple text editor .

### ISSUE THREAD

**Issue by sanjeetpal007** [nuttyartist/notes#298]
Multiple notes content can be shown with multiple tabs in text editor.

**Comment by cacoch** [comment]
Me neither. But could be possible edit notes in external editor like vim. btw, notes looks great. excellent  job.

**Comment by nuttyartist** [comment]
Thanks, I'm closing this as it seems the content of this issue is covered in two separate issues already.
