### ISSUE TITLE
Debian missing qt/sqlite driver, notes dont save or load

### ISSUE THREAD

**Issue by someodd** [nuttyartist/notes#299]
First off, I love this software. Absolutely perfect for spur-of-the-moment notes. Great job!

I've noticed this problem on/off where I'll do a fresh install of Debian, install the `deb` and it won't save any notes/won't load the `notes.db` I transferred/migrated from an older system. I had to do another transfer just yesterday and I decided to launch Notes from the terminal and noticed it complaining about not having loaded/access to any qt/sqlite drivers and that it wasn't connecting to the database. Part of the error was `QSqlDatabase: QSQLITE driver not loaded`. After a little bit of research I found out I could install the driver it was complaining about with ` sudo apt install libqt5sql5-sqlite`. Now it works fine, it connects to `notes.db`, with all of my notes migrated.

I am using Debian testing (bookworm/sid). I installed using `sudo apt install ./notes_1.5.0_amd64-bionic.deb` (as well as having tried `dpkg`).

**Comment by nuttyartist** [comment]
Hi! Thanks for your kind words. I'm glad you solved your issue. What OS version you were using?

Thanks for reporting the issue.

**Comment by theshadowx** [comment]
might be missing in the dependencies list : 
https://github.com/nuttyartist/notes/blob/dev/packaging/linux/debian/control#L13
`Depends: libqt5widgets5 (>= 5.2), libqt5gui5 (>= 5.2), libqt5network5 (>= 5.2), libqt5sql5 (>= 5.2), libqt5core5a (>= 5.2), sqlite3, ${misc:Depends}, ${shlibs:Depends}`

**Comment by someodd** [comment]
@nuttyartist I am using Debian unstable (sid/bookworm).

Thank you @theshadowx for pointing that out. I went ahead and added the dependency to the place you mentioned (I created a PR: #300). `libqt5sql5-sqlite` isn't actually a dependency of [libqt5sql5](https://packages.debian.org/bullseye/libqt5sql5), just recommended by it.

**Comment by nuttyartist** [comment]
@theshadowx Thanks for helping out.
