### ISSUE TITLE
Confirmation on deletion

### ISSUE THREAD

**Issue by xtthew** [nuttyartist/notes#305]
I just accidently deleted one of the notes I was using for work. I didn't realize pressing Ctrl+D would delete the open note, and while I was trying to duplicate an object in Inkscape using Ctrl+D I discovered that I didn't switch apps and deleted the note I was working with.

Although I remember roughly 80% of what was in the note, I can see this being a major issue in other scenarios. Either adding a confirmation on deletion or a cached backup of the notes for restoration could help avoid this scenario.

**Comment by tanabi** [comment]
Your notes aren't really deleted I don't think, they move to another table.

On linux, `sqlite3 ~/.config/Awesomeness/notes.db` and you can `select * from deleted_notes` to see your deleted notes.  `.schema` will show you the DB tables and what you can query.

**Comment by xtthew** [comment]
Awesome, that helps. I was able to use an online SQLite browser to get my deleted note back.

I still think it would be good to have the option to restore a note from the interface - or even avoid accidental deletion of a note.

**Comment by nuttyartist** [comment]
> 

Great. The next version (already in dev) is going to have a Trash folder.
