### ISSUE TITLE
build error with 2.0 on archlinux

### ISSUE THREAD

**Issue by bl00dy1837** [nuttyartist/notes#307]
when I try to build version 2.0 on archlinux. Don't know if it is a problem of QSimpleUpdater or of the notes function. Version 1.5 does build without problems.

../../QSimpleUpdater/src/Downloader.cpp: In member function ‘void Downloader::metaDataChanged()’:
../../QSimpleUpdater/src/Downloader.cpp:344:32: error: variable ‘QRegularExpression regExp’ has initializer but incomplete type
  344 |       QRegularExpression regExp( "(.*)filename=\"(?<filename>.*)\"" );
      |                                ^
../../QSimpleUpdater/src/Downloader.cpp:345:31: error: variable ‘QRegularExpressionMatch match’ has initializer but incomplete type
  345 |       QRegularExpressionMatch match = regExp.match( contentDisposition );

**Comment by nuttyartist** [comment]
Hmm, I'm not sure why. Maybe someone else can shed some light on this?

**Comment by mamantoha** [comment]
No error on Manjaro so far.
![image](https://user-images.githubusercontent.com/61285/189373596-a547f1c1-c27b-4c69-9e45-19c54a37d5bf.png)

**Comment by nuttyartist** [comment]
@bl00dy1837 Is it still a problem? it seems to be working for other people on AUR: https://aur.archlinux.org/packages/notes

**Comment by bl00dy1837** [comment]
With the git package it's working now. With the tar.gz release I have the same problem. But works for me now. thanks
