### ISSUE TITLE
make uninstall after compiling attempts to remove /usr/bin

### ISSUE THREAD

**Issue by darthdubu** [nuttyartist/notes#308]
Not sure if this is intended behavior but god forbid this actually went through and deleted /usr/bin it would be really really bad.

![image](https://user-images.githubusercontent.com/63337938/189361428-7b6b8756-ccdd-4329-a062-fec441a4c389.png)

**Comment by darthdubu** [comment]
Yeah i figured that probably isn't supposed to happen. I'm using Void Linux.

**Comment by guihkx** [comment]
There seem to be a misconception here: The sole purpose of `rmdir`, as explained by its [own description](https://man.archlinux.org/man/core/coreutils/rmdir.1.en#DESCRIPTION), is to only remove *empty* directories.

So even if `make uninstall` tries to `rmdir /usr/bin`, it's totally fine.

That's probably done to deal with the leftover directory created when you invoke `make install` with [`DESTDIR`](https://www.gnu.org/software/make/manual/html_node/DESTDIR.html) set.

Nevertheless, this is not applicable after the switch to CMake (as [`make uninstall` targets are not supported](https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake)), so I'll close this.
