### ISSUE TITLE
Consider changing the Aa button to a gear icon to better reflect settings of the editor

### ISSUE THREAD

**Issue by johnblommers** [nuttyartist/notes#309]
Notes advertises dark, light and sepia themes.

However there is no menu item or keyboard shortcut in evidence to change the theme.

I downloaded the AppImage for Linux, running on PopOS 22.04.

It's unclear what version of Notes I have because the About Notes menu does not say.

**Comment by johnblommers** [comment]
Did some research and found the answer to my own issue.

`~/.config/Awesomeness/Settings.ini`  contains a line we can edit to read:

`theme=Sepia`  or `Light` or `Dark`.

and the same file holds the version number which is 2.0.0.

**Comment by johnblommers** [comment]
Also if you are editing text you'll notes **`Aa`** at the top left of it. Click that for the Editor settings. I've gotten used to &#x2699;  icons for settings and missed this.

**Comment by nuttyartist** [comment]
Hi, yes, as you found out, you can change the theme via the Editor settings. Here:

![Screen Shot 2022-09-10 at 1 39 49 PM](https://user-images.githubusercontent.com/16375940/189477842-5e590c0a-8118-4bd9-9b59-eafac90c1607.png)

May I close this issue?

**Comment by johnblommers** [comment]
Do consider using a gear icon for Settings but this issue is closed.

**Comment by edwyn-amador** [comment]
Yes, same thought on better using a gear icon, I was confused because I wasn't finding the "Settings" section in order to switch the theme

**Comment by nuttyartist** [comment]
I'll consider that. Thanks!

**Comment by nuttyartist** [comment]
I'm trying to think what's the best solution for that because many users reported not finding how to style the editor. Probably a gear icon will go a long way. I don't want to put it in the 3 dots button since it will require two clicks to open rather than one, and I want it editor settings window easily accessible.

**Comment by edwyn-amador** [comment]
> I'm trying to think what's the best solution for that because many users reported not finding how to style the editor. Probably a gear icon will go a long way. I don't want to put it in the 3 dots button since it will require two clicks to open rather than one, and I want it editor settings window easily accessible.

Actually I suggest you to better use an hex nug icon, similar to this one:

![image](https://user-images.githubusercontent.com/36249854/224491797-78a7ba54-4f41-45d1-bef1-7197a8b4c602.png)

Or the outline version (which would better match with the trash bin icon there):

![image](https://user-images.githubusercontent.com/36249854/224491823-d9415fcf-c989-4faf-a234-6fa4399cc9fa.png)

It is much more minimalistic and pleasant to the eye than a cog icon, and it is understandable enough (I've seen some apps using an hex nut similar to this one for settings).

You can take a look to that icon here: https://www.flaticon.com/free-icon/nut_4487866?related_id=4487888&origin=search

**Comment by zjeffer** [comment]
Personally, I like an actual gear much more. Something like this: https://www.flaticon.com/free-icon/gear_484562 ?

**Comment by nuttyartist** [comment]
@edwyn-amador I don't think a hex nug icon is familiar enough to people. I prefer to go with a gear icon as well.

**Comment by edwyn-amador** [comment]
> @edwyn-amador I don't think a hex nug icon is familiar enough to people. I prefer to go with a gear icon as well.

Well, I don't even see it too different actually, just more easy to the eye and I personally like those apps I've seen using it and find it more creative in terms of design, but sure a gear would be fine for me as well.

**Comment by nuttyartist** [comment]
Done in #295
