### ISSUE TITLE
Remove resizing capabilities

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#31]
As for now, resizing doesn't work well.
1. It doesn't show the cursor resize state when hovering the window borders before resizing. But that's easily solvable (check on mouse move event). 
2. The problem is that resizing isn't detected when the mouse occurs to be upon widgets like scrollArea and textEdit, which take a lot of space, so resizing only works on an unpractical tiny space.

If we can't get it right and well we shouldn't do it.

Of course, we should aspire for the window manager to take care for that.
For now, only Ubuntu 14.04+ and Windows 10 are the good guys here.

**Comment by theshadowx** [comment]
I have tested with Ubuntu 16.04 and the resizing works well, even when the mouse is on the note and at the left border, the mouse changes shape, and resize the app smoothly. 

We should test it again with the code responsible for resizing disabled.

**Comment by nuttyartist** [comment]
That's good. I have tested on 14.04 and got the same results.
In my testing, just our code, without the window manager help, the resizing doesn't work on top of the noteView and textEdit.

So we should speak with other distros that their window managers doesn't support resizing on a frameless window, and/or find a way to do it on our own.

But as this issue states, we don't want to ship half-baked features, so as of right now, until we find a solution, resizing should be removed.

**Comment by nuttyartist** [comment]
Should we comment the code or completely remove it?
I think we should comment it, for the reason that we might come back to it again in the future.

**Comment by theshadowx** [comment]
Well in the both cases we can come back as we have it in the git history.
I think it's better to remove it in order to have a clean code.

**Comment by nuttyartist** [comment]
Oh right.
Removing it is.
