### ISSUE TITLE
Automatic updater doesn't seem to work on Windows

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#310]
The automatic updater doesn't seem to work on Windows.

**Comment by nuttyartist** [comment]
@diepdtnse03145 discovered the problem is that we are not shipping OpenSSL libraries with our binary.  @guihkx Do you think you can add the appropriate .dlls `libssl-1_1-x64.dll` and `libcrypto-1_1-x64.dll` for x64, and the proper ones for x86 to our packaging scheme? They should be under `QT\Tools\OpenSSL`

**Comment by guihkx** [comment]
I'll take a look.
