### ISSUE TITLE
What's new box should not be shown if the latest version is installed

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#313]
What's new box should not be shown if the latest version is installed.

**Comment by nuttyartist** [comment]
I'm unsure about this. Maybe this bug is a feature so people can come back and see the changelog of their installed version?

Or maybe we should show a proper changelog then, haha?

**Comment by bjorn** [comment]
I think we can just close this. I see no harm in showing what's new in the latest version in the update window.

**Comment by nuttyartist** [comment]
Okay, closing this and creating a new issue for the changelog.
