### ISSUE TITLE
Scaling issue in windows

### ISSUE THREAD

**Issue by jayu9493** [nuttyartist/notes#329]
OS:Windows 11
Version: 2.0.0
To recreate this issue: Normal installation no other settings have changed
![Screenshot (2)](https://user-images.githubusercontent.com/87773845/189959989-2876145d-ec03-4c74-bc79-d68727c396fd.png)
As seen in the picture there is two major problems.
1) The scaling issue after reading the issues on github i can solve this problem in linux but in windows i don't know neither the answers tells us.
2) The full screen mode is also hiding the taskbar in default although i have set taskbar to always visible. 

**Changing the scaling of my whole system makes it readable.**

**Comment by nuttyartist** [comment]
Yes, this is a known issue #39 and #164. @diepdtnse03145 reported that

> Qt doc say it will auto scale on high DPI screen. If that doesn't work for us we must scale every individual widgets manually, which is next to impossible

We still need to figure it out. I will close that issue as we already tracking this somewhere else.
