### ISSUE TITLE
Ctrl + Enter should focus the note's content

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#33]
Ctrl + Enter should focus the note's content

**Comment by theshadowx** [comment]
Isn't just Enter that focuses  the note's content ?

` new QShortcut(QKeySequence(Qt::Key_Enter), this, SLOT(setFocusOnText()));`

**Comment by nuttyartist** [comment]
In the previous master, Enter would focus the note even when ctrl is pressed too.
The thing is, people would scroll down a lot of times using ctrl + up/down, and right when they found the right note they would press Enter, so a lot of times it will happen while ctrl is pressed too and they would expect it (rightfully) to focus the note content.
