### ISSUE TITLE
Scaling of elements is not correct on HiDpi screen

### ISSUE THREAD

**Issue by p2004a** [nuttyartist/notes#331]
I've installed application on Windows 11 try it out, but it looks like scaling of elements is quite off in comparison to how it's supposed to look like according to screenshots when using HiDpi screen (scale 200%):

![notes_screen](https://user-images.githubusercontent.com/2212599/190279681-bb84725f-6cf3-4fbb-8e75-633bd07653b8.png)

The size of the icons is too small, too small spacing between elements, too small line height of elements

**Comment by nuttyartist** [comment]
Yes, this is a known issue #39 and #164. @diepdtnse03145 reported that

> Qt doc say it will auto scale on high DPI screen. If that doesn't work for us we must scale every individual widgets manually, which is next to impossible

We still need to figure it out. I will close that issue as we are already tracking this somewhere else.
