### ISSUE TITLE
[not an issue] Interview request

### ISSUE THREAD

**Issue by ph4ni** [nuttyartist/notes#337]
Hi! Got to know about this project on r/linux, and I find it really cool! Would you be interested in talking about notes on our weekly newsletter? Console by Open Source Hub is a newsletter read by thousands of open source enthusiasts and engineers every week. The process is totally asynchronous, and I make it as painless as possible. If you are interested, just send a hi to sai @ codesee.io :)

**Comment by nuttyartist** [comment]
I will, thanks (:
