### ISSUE TITLE
Extreme input delay in text editing view

### ISSUE THREAD

**Issue by Vexs** [nuttyartist/notes#339]
See attached content- strumming my keyboard as in the first row of the video, as well as holding down the X key exhibits some pretty ludicrous input delay. This seems better in the search field and similar, but still a bit slow. 
Hardware/OS:
* Windows 10
* AMD 2700x
* 32gb RAM
* Nvidia 2080ti GPU

https://user-images.githubusercontent.com/7316404/190725587-6d540e65-f1b6-4771-a127-2eee11e492f3.mp4

**Comment by nuttyartist** [comment]
This is very weird. I tried it on Windows, Linux, and macOS and never experienced that. Needs more investigation. Can you compile just a simple QTextEdit to see if the problem persists?

**Comment by masihsaeedi** [comment]
Same problem on endeavourOS kde. I have tested both aur and appimage.

**Comment by Vexs** [comment]
> Can you compile just a simple QTextEdit to see if the problem persists

Regretfully I'm not familiar with using QT enough to do so with much proficiency- but I spun it up with PyQT using [some example code](https://pythonpyqt.com/pyqt-qtextedit/) and it seemed to work without any hitches. Anecdotally I've used a handful of other QT apps in the past and this is the first I've experienced this.
