### ISSUE TITLE
Automatic updates doesn't work on Windows - can't download latest version information

### ISSUE THREAD

**Issue by yaggit** [nuttyartist/notes#342]
![image](https://user-images.githubusercontent.com/72143254/190845879-e0b64678-1a67-4788-9e80-3d70734895de.png)

**Comment by nuttyartist** [comment]
Are you running on Windows? If so, It's a known bug that Notes cannot download information from our Github repo regarding the latest version. It's very unfortunate since it means many of our existing Windows users (800K) will not get automatic updates.

**Comment by yaggit** [comment]
Yes, running on windows.

Right, that's a bug. I believe I can give it a try to resolve this issue. Would you please help me to understand the scope of this issue and how to work on this.

This can be my first open source contribution.

**Comment by nuttyartist** [comment]
Well, you'll need to make the updater work, basically, I'm not entirely sure about it, but I think the problem lay in that our app on Windows doesn't recognize/can't download the UPDATES.json file https://github.com/nuttyartist/notes/blob/dev/UPDATES.json. 

Somebody already working on this issue. Maybe try to find another issue to solve? Thanks nonetheless!

**Comment by yaggit** [comment]
okay, no problem.
