### ISSUE TITLE
Problem with window frame (Windows 11)

### ISSUE THREAD

**Issue by Hikk0o** [nuttyartist/notes#349]
A custom frame is not always replaced with a native one

https://user-images.githubusercontent.com/78872275/190868495-554c7908-9149-4dd9-a663-8b9e83df2b76.mp4

**Comment by guihkx** [comment]
Already fixed by https://github.com/nuttyartist/notes/pull/344.

**Comment by REALERvolker1** [comment]
I had that happen on Linux as well

**Comment by nuttyartist** [comment]
Hi, @Hikk0o! Thanks for reporting. @guihkx fixed these issues on his PR #344. I haven't yet merged this into the master, but if you want you can grab the Windows installer with that fix here: [64bit](https://ci.appveyor.com/project/nuttyartist/notes/builds/44806570/job/kgiml37qsnovygh6/artifacts), [32bit](https://ci.appveyor.com/project/nuttyartist/notes/builds/44806570/job/r1wofle56f2twh81/artifacts)
