### ISSUE TITLE
Creating/deleting should be more responsive

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#35]
Creating/deleting a note should be more responsive.
There is a bit of lag when creating/deleting a note.
(Independable from a number of notes there are)

**Comment by theshadowx** [comment]
Because when creating or deleting, the note is added/deleted to/from the .ini file, which cost processing time, the solution is to do the animation first and then the backend operations

**Comment by theshadowx** [comment]
I just verified that while creating a note : 

- the app get the counter from the ini file
- increment it
- add a new slot to the ini file (note_name + creation date + modification time)

and sometimes this is a waste when the new note was note modified. so it will automatically be deleted.
