### ISSUE TITLE
Make URLs clickable

### ISSUE THREAD

**Issue by udoprog** [nuttyartist/notes#353]
Application version: 2.0.0
OS: Windows 10

Clicking a URL like this on Windows 10 does not open the link in your system browser (not sure if it does on others either):

![image](https://user-images.githubusercontent.com/111092/190875549-ab8e49c8-aac1-403a-8c13-ae2e104cd7c0.png)

Right clicking should probably also give the option to copy the URL by common UX convention.

Cheers!

**Comment by nuttyartist** [comment]
Hi! This is an issue in all operating systems for now. Thanks for reporting!

**Comment by nuttyartist** [comment]
This should be fixed now due to #430. Although we still have minor improvements to make, as reported in #459.

Thanks for reporting this!
