### ISSUE TITLE
Converting codebase to Qt 6

### ISSUE THREAD

**Issue by kemier** [nuttyartist/notes#356]
macOS m1 version:12.6

compile error in 3rd party code:
```
In file included from ../3rdParty/qxt/qxtglobalshortcut.cpp:1:
In file included from ../3rdParty/qxt/qxtglobalshortcut.h:34:
../3rdParty/qxt/qxtglobal.h:200:19: error: allocating an object of abstract class type 'QxtGlobalShortcutPrivate'
        pvt = new PVT;
```

so is it ready for the compiling of new version qt?

**Comment by nuttyartist** [comment]
Hi! No, the code is not fully compatible with Qt 6 yet. I wonder if it's worth converting our codebase to Qt 6?

**Comment by bjorn** [comment]
> I wonder if it's worth converting our codebase to Qt 6?

Well, it basically has to be done because Qt 5.15 is no longer maintained for open source users (or at least no binaries are released beyond 5.15.2) and even [standard support will end in a few months](https://www.qt.io/blog/the-conversion-program-is-ending).

**Comment by txtsd** [comment]
It's worth making the codebase compatible with Qt6 now instead of later. Migrating from `qmake` to `cmake` is also recommended at the same time.

**Comment by nuttyartist** [comment]
Sounds like a good idea to me.

**Comment by zjeffer** [comment]
I'm working on a QT6 port here: https://github.com/zjeffer/notes-qt6

I managed to fix some build errors just by looking at documentation and updating the code. There are many errors left to fix. I noticed the 3rdParty code also isn't QT6-compatible, should we fork and update those projects as well? Or look for replacements?

**Comment by nuttyartist** [comment]
That's awesome. If you find some 3rd party libraries that fit the bill, suggest them here. But maybe forking is better since we already incorporated and battle-tested them in production?

**Comment by zjeffer** [comment]
I will investigate which ones can be easily forked. 

As for the main project, do we need to add a version check for every change, so that everything still works with QT5, or should we move completely to QT6?

**Comment by nuttyartist** [comment]
My opinion is to move completely to QT6. What about others? @bjorn?

Since with self-contained packages there is no problem, what about when distributing our packages as .deb for example, let's say Ubuntu systems with older versions of Qt, will the package manager know the right dependencies to install?

**Comment by nuttyartist** [comment]
I didn't know that QT6 only works on these platforms. I would definitely still want to support the same platforms you support with Tiled. So maybe we can have two versions, for now, QT6 for recent platforms and QT5 for the older ones.

@bjorn The rest of the tips are sound.

**Comment by danfe** [comment]
> I recently raised the minimum supported Qt from 5.6 to 5.12, which allows still supporting macOS 10.12, Ubuntu 16.04 (in theory) and Windows 7

This is the right thing to do.  Most distributions had already caught up to Qt 5.12 and even with Qt6 available, Qt5 is still being default Qt version e.g. in FreeBSD.
