### ISSUE TITLE
Notes should be spaced differently...

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#36]
Maybe we should space the notes a bit more for a clearer look, so they are more easily readable and distinguishable. Talking about the space between titleLabel to dateLabel to the separator line. If you look closely they are spaced differently in these two versions.

(Left the proposed way, Right the current way)

![selection_001](https://cloud.githubusercontent.com/assets/16375940/14227974/5843efd2-f911-11e5-95da-013950429ada.png)

**Comment by nuttyartist** [comment]
The current way of spacing is better.

**Comment by theshadowx** [comment]
Does this problem still appear ?

**Comment by nuttyartist** [comment]
Yes. I checked and what should be done is just to increase in 1px the space between dateLabel and the separator line.

**Comment by theshadowx** [comment]
In which OS this problem happens ?

**Comment by nuttyartist** [comment]
After testing on Linux, Mac and Windows it seems like the problems affect all of them in different ways, maybe because they are using different fonts and they are rendered differently? Anyway, I'll continue testing to see what action to take.

**Comment by theshadowx** [comment]
Normally there should be a space between the scrollbar and the selected rectangle in order to preserve symmetry for scrollbar, this is how it is coded :  

https://github.com/nuttyartist/notes/blob/dev/src/noteview.cpp#L263-L275

```
    connect(this->verticalScrollBar(), &QScrollBar::rangeChanged,[this](int min, int max){
        Q_UNUSED(min)

        NoteWidgetDelegate* delegate = static_cast<NoteWidgetDelegate*>(itemDelegate());
        if(delegate != Q_NULLPTR){
            if(max > 0){
                delegate->setRowRightOffset(2);
            }else{
                delegate->setRowRightOffset(0);
            }
            viewport()->update();
        }
    });
```

**Comment by nuttyartist** [comment]
That's good.
I'm talking about a completely different thing, I should have clarified. This issue is about the space between titleLabel to dateLabel to the separator line. If you look closely they are spaced differently in these two versions.

**Comment by theshadowx** [comment]
ah, I think it should have been better to make it as a new issue. but what's done is done.

From the picture there is 2px diff for title between the two apps

**Comment by theshadowx** [comment]
is this issue still present in the recent version ?

**Comment by nuttyartist** [comment]
Yes, it is. I tell you what, the things is all I need is a simple way to set the space between **1**. `titleLabel` and the `top of the note`. between **2**. `titleLabel` and `dateLabel`. and between **3**. the `dateLabel` and the `seprateLine`.

I also thought about your recommendation for one font we'll embed and use across all platforms, which will unify the app across platforms and will add uniqueness to the app. But nevertheless, the important thing is an easy way to set the space between these elements.

**Comment by nuttyartist** [comment]
I can't iterate on the positions of the items (mainly their 'y' axis), while this problem is still unsolved. Changing one parameter will make the others work inconsistently. I really can't figure out how to make this work. It's best if it would be like I've written above. 

@theshadowx can you do something about it?

**Comment by theshadowx** [comment]
have a look at dev:
https://github.com/theshadowx/notes/blob/dev/src/notewidgetdelegate.cpp#L166-L167

you can now easily modify the space between title and date and the space on top of the title

**Comment by nuttyartist** [comment]
It works excellently. I could now iterate and find the right values, which you can change to:
```
rowHeight(42)
topOffsetY = 5;
spaceY = 1;
```
And then send a pull request :)

Only one thing, I think there is a problem with Elementary OS (Freya, again). These values work great for Ubuntu 16.4 and Windows 7, but on Elementary OS Freya it looks a bit different. Here are some images:

![ubuntu 16 14](https://cloud.githubusercontent.com/assets/16375940/17935568/76c254d8-6a24-11e6-98dc-3c921593ef60.png)
![windows 7](https://cloud.githubusercontent.com/assets/16375940/17935575/8000923a-6a24-11e6-916a-034f1d04a912.png)
![elementary os freya](https://cloud.githubusercontent.com/assets/16375940/17935579/823ab238-6a24-11e6-858a-2a73345154e3.png)

I think it's just some specific issue for that version of the distro, why do you think it happens?

**Comment by theshadowx** [comment]
could you enlighten me, I don't see where is the issue

**Comment by nuttyartist** [comment]
The spaces between the elements in the noteView are the same on both Ubuntu 16.04 and Windows 7, but on Elementary OS Freya the spaces are different. And of course, they all ran from the same source. So it's most be some kind of a problem with Freya I think.

**Comment by theshadowx** [comment]
I don't know what can be done.

**Comment by nuttyartist** [comment]
I think it's fine, it works well on all the os's I tested on, except just Freya. If we'll have a problem along the way we'll tackle it. You can send a pull request.
