### ISSUE TITLE
Request: .clang-format file

### ISSUE THREAD

**Issue by zjeffer** [nuttyartist/notes#387]
I noticed this repo doesn't have a .clang-format file. It would be great if this was added, doing so would ensure every contributor uploads code with the same formatting.

**Comment by nuttyartist** [comment]
Good idea; I only learned about it now because you mentioned it.

**Comment by zjeffer** [comment]
There's a clang-format file based on the Qt Coding Style (https://wiki.qt.io/Qt_Coding_Style#clang-format), I'll make a PR to include this file after merging the QT6 migration.

**Comment by nuttyartist** [comment]
> There's a clang-format file based on the Qt Coding Style (https://wiki.qt.io/Qt_Coding_Style#clang-format), I'll make a PR to include this file after merging the QT6 migration.

👍
