### ISSUE TITLE
QMarkdownTextEdit headers color should be the same color as text

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#389]
The headers' color should be the same as the text color.

![Screen Shot 2022-10-04 at 2 18 00 PM](https://user-images.githubusercontent.com/16375940/193817210-ac005f60-9265-470e-8df2-77b0ba1f2ff6.png)

**Comment by zjeffer** [comment]
This fixes it: https://github.com/pbek/qmarkdowntextedit/compare/develop...zjeffer:qmarkdowntextedit:develop

I think you should maybe create your own fork of qmarkdowntextedit, as there will probably be changes you want to make in the future to this repo.

**Comment by bjorn** [comment]
> I think you should maybe create your own fork of qmarkdowntextedit, as there will probably be changes you want to make in the future to this repo.

Might be better to avoid maintaining our own fork, if the original is well maintained and accepts any needed options. In this particular case, it actually already provides a `MarkdownHighlighter::setTextFormat`, which could be used to override the default header formats.

**Comment by zjeffer** [comment]
Great! I'll look into this.
