### ISSUE TITLE
Windows + N keyboard shortcut + Tray icon + Settings UI ...  Improvements

### ISSUE THREAD

**Issue by edwyn-amador** [nuttyartist/notes#391]
Hello, so this shortcut can't be used on Windows 11 at least, as this one seems to be reserved to the Calendar, whenever I press the combination it opens up the calendar and not able to quickly open the app nor even re-mapping this keyboard hotkey.

Now, regarding to the tray icon, please implement the functionality to open the app with double clicking the icon, it is not working (at least not in Win 11).

Regarding the settings, is not really intuitive with that icon, I was having a hard time trying to find the "Settings" section, please consider replacing it with a gear/controls icon which is a standard in terms of UX (In terms of desin I would prefer the gear)

Extra: Would you consider to implement a cloud feature? if not by using a server of your own, maybe an integration to make it possible to sync/save in Google Drive at least. It would be really useful to be able to retrieve all notes on a different computer and even better if these can be synced in real-time.

Other than that, I am really amazed on the work that you have done with app! I just discovered it through Betalist.

**Comment by nuttyartist** [comment]
Hey! Thanks for your many good suggestions.

I re-opened an issue regarding changing the Aa icon to a gear icon.

I will definitely create an issue about double-clicking the tray icon.

Also, I will create a new issue that will allow changing the keyboard shortcuts.

Regarding cloud syncing, you can change the location of your database to where your Google Drive folder is. But it's not ideal as it's a database based compared to an arbitrary folder (a bunch of .txt files) as some said a clash of syncing might disrupt the entire database, but I haven't tested this.

Thanks for the kind words!
