### ISSUE TITLE
UI improvements for scaling

### ISSUE THREAD

**Issue by MrGKanev** [nuttyartist/notes#392]
OS: Windows 11
Version: 2.0.0

When I was testing Notes to see if it was for me I had a few UI problems when writing notes.
* right click there is a white line going straight from top to bottom
* we only see half of the row of text from the note when multiple notes

Everything is connected with Windows scaling as far as I can see. When testing it was done on a 4k display and 125% scaling. When it was disabled everything looked as it should. (I think)

Screenshot: https://ibb.co/hBnJ6PG

**Comment by nuttyartist** [comment]
Yes, this problem is reported in #39 We will try our best to fix this for our next release. I will close this now as we are tracking this in #39.
