### ISSUE TITLE
Double-clicking the tray icon (or 1 click on macOS) should show Notes

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#393]
Double-clicking the tray icon (or 1 click on macOS) should show Notes.

**Comment by guihkx** [comment]
I think this was (somewhat) accomplished by #451?

**Comment by bjorn** [comment]
Yeah, I this can be closed, even if the implementation is the other way around, with it taking 1 click on Windows, and two clicks on macOS due to #458. ;-)

**Comment by nuttyartist** [comment]
It works with one click on macOS for me. An yes we can close this (:
