### ISSUE TITLE
Thanks for making it.

### ISSUE THREAD

**Issue by newterminator** [nuttyartist/notes#40]
I had been searching for a notes app like this for the longest time for the linux platform. I just wanted to write that when I found it mentioned at [omgubuntu.co.uk](http://www.omgubuntu.co.uk/2016/03/get-notes-simple-note-taking-app-linux), I was elated to try it out. 

I am sure you are already aware that on eOS freya 0.3.2 the new and delete icons don't show up, but nevertheless it works as described. 

It is amazing looking and being cross platform and open source it's like having the cake with all the icing and cherries on top.

**Comment by nuttyartist** [comment]
Hi there @newterminator!

Thanks for your kind words, it really gets us motivated to keep moving forward.
The issue you described got fixed here #24, and it's going to be available on the next release.
Before the new release, I will contact you to test if everything works well on your machine (and others).

There are some major inventions going on with the development of the next release. Most of it is a refinement of the core experience. We really want to enhance, amplify and perfect everything that we do. @theshadowx revolutionizing the code in his MV branch, making the entire experience more fluid, fast and reliable using the Model-View architecture, and a lot of other improvements.

Looking to the future, there are incredible features planned. So we really are moving toward something bigger and much better at empowering the people using Notes.

**Comment by newterminator** [comment]
Hi @nuttyartist ,
I had been away for the weekend. Well this app has a real potential to grow in user base. The cleanliness, and simple UI, and the ability to save all the notes locally is amazing. And also the guiding principles for the development of the app are amazing. 

I have started using notes everyday on both my linux machines, and I am really happy with it. Like I said earlier I had been looking for a dedicated notes app since the beginning of the year. I tried Cherry (works but the UI needs help, and couldn't get it to run on Mac OS X), Springseed (which looked good but version 2.0 does not work) and Tomboy (not the best user experience). 

I started using Sublime Text and having text files to keep notes. But still I didn't stop looking from time to time to find something better. And then I found your notes app. 

The feature that I am most looking forward to have is the "Folders" as marked in the notes future versions page, so as to better organize the notes.

Also the app is fast and lean; I saw the ram usage on the gnome task manager and it uses less memory than the Scratch app on eOS with similar amount of plain text. 

Thanks once again for making it, and looking forward to all the future versions (also thanks for mentioning the fix to the icons issue, and sure I will gladly check out new releases).

**Comment by nuttyartist** [comment]
I'm glad you liked it.
There would be more to like in the time to come.

Also, as you might have noticed, there are no shadows on the window on eOS Freya. I talked with the Elementary folks and It's going to work on the next version - Elementary Loki (A bug in the upstream window manager - Mutter got fixed), so it would look more like it was intended to be.

**Comment by newterminator** [comment]
Hey @nuttyartist 
Yeah I noticed the shadow not being there, but the core product is so good, that not having these extra nice things on the side especially in the first few versions is no big deal. And I am also looking forward to Loki !!!
