### ISSUE TITLE
Dark Theme + Windows Taskbar Icon Click + Caret Cursor issues

### ISSUE THREAD

**Issue by edwyn-amador** [nuttyartist/notes#400]
Me again😅

Just want to report some issues, regarding the dark theme:

![image](https://user-images.githubusercontent.com/36249854/194938838-ec0db693-bcda-4dd0-9eb3-f3fb0b02870f.png)

The minimize and maximize icons are not properly visible until onMouseHover.

Also regarding this section:

![image](https://user-images.githubusercontent.com/36249854/194941308-01dbc167-10bb-454b-a3d2-a121d19a97a3.png)

The content is not visible when the window loses focus:

![image](https://user-images.githubusercontent.com/36249854/194941427-92783e3f-d06f-4de4-ad64-46704fa7ac14.png)

Regarding the Windows taskbar icon click issue, is not minimizing/restoring when performing a click (unless using the native window frame).

![image](https://user-images.githubusercontent.com/36249854/194939653-1b70c7af-59a4-408a-8469-edeb2148f406.png)

As for the caret cursor issue, sometimes when the caret cursor is at the end and the user starts typing just before sending the text the app moves the caret cursor all the way to the top (similar to performing a PgUp + Home keys) and so the text is send at the beginning of everything.

![image](https://user-images.githubusercontent.com/36249854/194940248-e3de8dca-1348-4def-96f2-b9d0d3c1104f.png)
![image](https://user-images.githubusercontent.com/36249854/194940443-4db1db41-cc23-4d63-bfc1-5c491d9b85b9.png)

Just haven't tested in which scenarios this happen exactly, but it seems that in order to reproduce this would require losing focus in the editor/text area and getting focus back.

Also happen whenever the content is automatically saved, after saving, it moves the caret cursor position to the beginning.

**Comment by nuttyartist** [comment]
> Regarding the Windows taskbar icon click issue, is not minimizing/restoring when performing a click (unless using the native window frame).

We already opened an issue for that here #393, or do you mean something else?

> Also happen whenever the content is automatically saved, after saving, it moves the caret cursor position to the beginning.

Can you submit a video/GIF please?

To summarize:

- [ ] Minimize and maximize icons are not properly visible until onMouseHover
- [ ] notesList content is not visible when app is unfocused
- [ ] The cursor thing

**Comment by edwyn-amador** [comment]
> We already opened an issue for that here #393, or do you mean something else?

Yes, I am referring to the Windows Taskbar section, not the Windows Tray section, the Windows Tray is where the icon shows when the app is running in background, but the Taskbar section is where apps icons is shown when the app is running in foreground, as on the screenshot I show previously.

Please see: https://interactrapp.com/share/6345c7ba1b733

> Can you submit a video/GIF please?

Yup, here it is: https://interactrapp.com/share/6345c82300d3a

**Comment by nuttyartist** [comment]
Oh, very good catch! I opened a new issue for the Taskbar issue. https://github.com/nuttyartist/notes/issues/402

I couldn't reproduce the second issue on my Mac. I will test it on Windows very soon and report back.

Thanks a lot for catching these small but very annoying things! I bet many users experience the same, so it's very appreciated. What I find good about refining those many small issues is that on the next app we develop using Qt and the same utilities (or others building upon us) we'll already have a more refined experience.

**Comment by nuttyartist** [comment]
I wasn't able to reproduce the cursor issue on Windows:

![short](https://user-images.githubusercontent.com/16375940/195581777-e47dd04d-a426-4446-963c-cfc898da34d3.gif)

**Comment by edwyn-amador** [comment]
> I wasn't able to reproduce the cursor issue on Windows:
> 
> ![short](https://user-images.githubusercontent.com/16375940/195581777-e47dd04d-a426-4446-963c-cfc898da34d3.gif) [ ![short](https://user-images.githubusercontent.com/16375940/195581777-e47dd04d-a426-4446-963c-cfc898da34d3.gif) ](https://user-images.githubusercontent.com/16375940/195581777-e47dd04d-a426-4446-963c-cfc898da34d3.gif) [ ](https://user-images.githubusercontent.com/16375940/195581777-e47dd04d-a426-4446-963c-cfc898da34d3.gif)

I see, maybe try to wait for some time for the save to ocurr (when it shows the date in the top), that's when this issue happens as long as I have detected

**Comment by nuttyartist** [comment]
Done in #589
