### ISSUE TITLE
Migrate from qmake to CMake

### ISSUE THREAD

**Issue by zjeffer** [nuttyartist/notes#408]
With the conversion to QT6 (#386), it is also a good idea to migrate from `qmake` to CMake, as that is the recommended way to build QT6 projects. It should also be compatible with QT5, all the way down to 5.9

- Migrate to CMake
- Update build workflows to reflect this change
- Update build instructions in README
- ...

More info: https://doc.qt.io/qt-6/qt6-buildsystem.html

**Comment by guihkx** [comment]
Maybe helpful: https://code.qt.io/cgit/qt/qtbase.git/tree/util/cmake/pro2cmake.py

**Comment by zjeffer** [comment]
Closed with #421
