### ISSUE TITLE
Replace Q_OS_LINUX in the code with Q_OS_UNIX

### ISSUE THREAD

**Issue by danfe** [nuttyartist/notes#410]
This should be no-op on GNU/Linux while simplifying packaging for other Unix-like systems, *BSD, et al.  While explicit FreeBSD support had been added in eda71ec, IMHO it should be generalized.

**Comment by bjorn** [comment]
When doing this change, care should be taken that `Q_OS_UNIX` will also be defined on macOS, which may mean some code should be reordered such that `Q_OS_MACOS` is checked first where necessary.

**Comment by danfe** [comment]
> care should be taken that `Q_OS_UNIX` will also be defined on macOS

Fair enough.  Still, going with `Q_OS_UNIX` and occasional exceptions for macOS should yield more portable code.
