### ISSUE TITLE
Text cursor pops back to the top of the note when heading out of frame

### ISSUE THREAD

**Issue by novagitzone** [nuttyartist/notes#424]
OS: Windows 11 home
Version: 2.0.0
To recreate this issue: Normal installation with all default settings. Happens in both windowed and full screen

Hello, apologies if the title sounds confusing. Here what I mean:

![NotesAppBug1](https://user-images.githubusercontent.com/111399446/202572037-9e10cae1-b07c-480b-8540-bd9eacfbf72a.gif)

As you can see, when I get to the bottom edge, instead of going further down, the cursor pops back up towards the top.

If I also keep doing the same activity however, the text goes further down as intended and does not pop back to the top of the note.

![NotesAppBug2](https://user-images.githubusercontent.com/111399446/202573282-f35aae4f-a559-43bf-b636-e213867b761f.gif)

Any help would be appreciated

**Comment by nuttyartist** [comment]
That's weird. I think someone already reported that issue, but I can't seem to find it. It seems like it happens only on Windows for now.

**Comment by guihkx** [comment]
This also affects Linux, so it's likely that it affects macOS too (although I haven't checked myself).

**Comment by DAW-GUN** [comment]
Confirming this bug. I could reproduce it consistently on the first line of a note by starting with numbers.
For example, I try to start a note by typing "9876", the "9" gets typed, then the cursor moves back to the beginning and the "876" gets typed, so I end up with "8769." I often use Notes for jotting down phone numbers and so this really messes up the phone numbers if I'm not paying attention.

**Comment by nuttyartist** [comment]
@DAW-GUN Can you please grab the latest executable from GitHub Action and report if this problem still occurring for you?

**Comment by DAW-GUN** [comment]
Will do. And mini-update: the problem is not occurring on my gaming laptop - only my old work laptop. I'll report back after testing the new executable tomorrow.

**Comment by DAW-GUN** [comment]
> @DAW-GUN Can you please grab the latest executable from GitHub Action and report if this problem still occurring for you?

I can confirm that the latest build has squashed this bug. Great job, guys!
