### ISSUE TITLE
Huge performance difference between compiled executable from Github Actions and local machine

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#425]
There's a huge performance difference between an executable created by Github Actions (Qt 6.2.4) and one I compiled on my local machine (Qt 6.4) in the form of the time it takes to load notes.

Here's a comparison:

Compiled on my local machine:
![local](https://user-images.githubusercontent.com/16375940/205631313-fd8d0cb3-35ec-4f7f-9b44-20c107d6c0b7.gif)
Compiled on GitHub Actions:
![github](https://user-images.githubusercontent.com/16375940/205631029-348a4752-d15d-4013-99a7-d938043d1723.gif)

You can see it takes much more longer to load all the 4124 notes.

@guihkx any clue?

**Comment by guihkx** [comment]
Whoa, the difference is huge. I could try bumping the Qt version to see if it'd help, but let's try to make sure this is unrelated to the macOS build (which I'm quite unfamiliar with, and I can't really test it since I don't own a Mac).

Would it be possible for you to do this comparison between a local Windows build and the build we provide via Actions?

**Comment by zjeffer** [comment]
Build type = debug while it should be release, I guess?

**Comment by guihkx** [comment]
Shouldn't be it:

https://github.com/nuttyartist/notes/blob/c53a421b83b0a9142df0386ff9e47bf7f228e66c/.github/workflows/macos.yml#L70-L72

**Comment by zjeffer** [comment]
Ah, I was looking at the homebrew build. No clue, then.

**Comment by nuttyartist** [comment]
> Whoa, the difference is huge. I could try bumping the Qt version to see if it'd help, but let's try to make sure this is unrelated to the macOS build (which I'm quite unfamiliar with, and I can't really test it since I don't own a Mac).
> 
> Would it be possible for you to do this comparison between a local Windows build and the build we provide via Actions?

I'll not get my hands on a Windows machine until after a week. But we can start by bumping the version and seeing if there's any difference.

**Comment by guihkx** [comment]
Sure. Do you have any preference for what Qt version to use? I initially went with 6.2 because it's a LTS release...

Also, can you share your notes db so I can try to reproduce this on Linux?

Thanks.

**Comment by guihkx** [comment]
I found [this blog post](https://www.qt.io/blog/qt-6.2-lts-released) regarding the 6.2 LTS release:

>Qt 6.2 is also the first release of Qt 6 that will be long-term supported by The Qt Company **for Qt commercial customers**.

But for "regular users", these updates can be delayed up to 12 months according to [this email](https://mail.kde.org/pipermail/kde-community/2020q2/006098.html) I found. :/

In this case, I think we should just use the latest Qt version for our official releases (currently 6.4.1).

Any thoughts on this?

**Comment by nuttyartist** [comment]
The latest release seems good to me. Try bumping it to Qt 6.2.4, so we can see if the problem is coming from there or not.

And unfortunately my notes.db is a private one. I assume any db populated with the same size as mine (~6mb) should work.

**Comment by guihkx** [comment]
>Try bumping it to Qt 6.2.4

The CI is already using 6.2.4.

Let's try 6.3.2 first, and if you don't see any improvements, we'll try 6.4.1.

**Comment by nuttyartist** [comment]
Yep, seems to fix the issue.

**Comment by guihkx** [comment]
I think I was able to *somewhat* reproduce this on my Linux desktop, with 10k entries on Notes.

Although I feel like the slowness I experienced with Qt 6.2.4 is much less severe than yours. But at the same time, my eyes tell me that there is an obvious improvement after updating to Qt 6.3.2.

- Sample 10k entries Notes backup (for testing): [notes-10k-entries.zip](https://github.com/nuttyartist/notes/files/10225926/notes-10k-entries.zip)

---

###  My results on Linux:

#### Qt 6.2.4

https://user-images.githubusercontent.com/626206/207550856-accf144d-6dc0-4495-ba54-5a47dadfc318.mp4

#### Qt 6.3.2

https://user-images.githubusercontent.com/626206/207550905-a705b1b2-9fc6-4ad8-bdcd-433d526507b1.mp4

So I'll assume this is also affects Windows and merge #427.

**Comment by nuttyartist** [comment]
Hmm, I don't see much of a performance difference. Maybe the issue is more about the content size and less about the number of notes. Or maybe you have a faster GPU/CPU so the difference is less noticeable?

**Comment by guihkx** [comment]
I did some more testing, and my results indicate that this issue only affected macOS and was fixed somewhere in Qt 6.3.x.

First, here are some comparison videos I did on Windows 10 (I personally see no difference between the two):

### Qt 6.2.4

https://user-images.githubusercontent.com/626206/207985565-23c72b83-ae29-41a3-a70a-df5132e22717.mp4

### Qt 6.3.2

https://user-images.githubusercontent.com/626206/207985588-96e5caf0-ef8e-4090-bdd0-6879e9b716a4.mp4

Then, I was able to (painfully) install macOS Big Sur on a virtual machine, and while I'm aware of the performance penalty of virtualization, I just wanted to see if I'd be able to notice any performance improvements whatsoever.

You be the judge... lol:

### Qt 6.2.4

https://user-images.githubusercontent.com/626206/207988272-4e16a676-a9aa-484b-ba89-e740a2343f28.mp4

### Qt 6.3.2

https://user-images.githubusercontent.com/626206/207988293-8df30f3c-d22e-44ef-8126-efa909d8dec1.mp4

**Comment by nuttyartist** [comment]
Aha! Good catch! Maybe Qt introduced a macOS-related bug and then fixed it?

Is it just me, or is virtualized macOS faster than your non-virtualized Windows? 🤔

**Comment by guihkx** [comment]
Sadly, yes I think so... 🤷‍♂️

**Comment by nuttyartist** [comment]
> Sadly, yes I think so... 🤷‍♂️

I wonder what causes the huge gap there...

**Comment by guihkx** [comment]
No clue, unfortunately. This kind of debugging goes beyond my knowledge, especially on Windows.
