### ISSUE TITLE
[Proposition] All pull requests should be made to the dev branch

### ISSUE THREAD

**Issue by theshadowx** [nuttyartist/notes#43]
As now a dev branch exists in the original repository, I propose that the master branch should be protected meaning that just @nuttyartist will have the power to make pull request or merge to the master branch.

All persons contributing to this project should work on dev branch, and when willing to pull request they would do it just to dev branch or other non-master branch. This way we prevent that the git tree would be confusing and messed up.

**Comment by nuttyartist** [comment]
I agree, I think it's a good idea that the master would represent only stable and tested versions.
dev should be our playground.
Also, we might want to open specific branches for specific future features.

**Comment by theshadowx** [comment]
Here is how to enable branch restrictions
https://help.github.com/articles/enabling-branch-restrictions/

And when tests are done, it's better to require status check, not just for the master but also for test branch : 
https://help.github.com/articles/about-required-status-checks/
https://help.github.com/articles/enabling-required-status-checks/

**Comment by nuttyartist** [comment]
I changed the default branch to dev. I made the master protected.

Restrictions didn't show up in the options.
And we'll require status check for both branches when #42 is complete.
