### ISSUE TITLE
CI: Set additional CMake properties for macOS builds

### ISSUE THREAD

**Issue by guihkx** [nuttyartist/notes#442]
Warnings from the build step:

```
CMake Warning (dev) in CMakeLists.txt:
  uninitialized variable 'MACOSX_BUNDLE_INFO_STRING'
-- Generating done
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Build files have been written to: /Users/runner/work/notes/notes/build

CMake Warning (dev) in CMakeLists.txt:
  uninitialized variable 'MACOSX_BUNDLE_GUI_IDENTIFIER'
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  uninitialized variable 'MACOSX_BUNDLE_LONG_VERSION_STRING'
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  uninitialized variable 'MACOSX_BUNDLE_BUNDLE_NAME'
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  uninitialized variable 'MACOSX_BUNDLE_SHORT_VERSION_STRING'
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  uninitialized variable 'MACOSX_BUNDLE_BUNDLE_VERSION'
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  uninitialized variable 'MACOSX_BUNDLE_COPYRIGHT'
This warning is for project developers.  Use -Wno-dev to suppress it.
```

CMake documentation: https://cmake.org/cmake/help/v3.10/prop_tgt/MACOSX_BUNDLE_INFO_PLIST.html

@nuttyartist What should we use for [`MACOSX_BUNDLE_GUI_IDENTIFIER`](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier)?

As we [discussed previously](https://github.com/nuttyartist/notes/pull/345#issuecomment-1252813362), the app id I ended up using for our [future Flatpak app](https://github.com/guihkx/flatpak-app-notes) is: `io.github.nuttyartist.notes`.

Do you want to re-use that same app id, or use a different one?

**Comment by guihkx** [comment]
Aside: In the discussion I linked, I actually said I was going to use `com.github.nuttyartist.notes`, and not `io.github.nuttyartist.notes`.

But that was before recent changes to [Flatpak naming rules](https://docs.flatpak.org/en/latest/conventions.html#application-ids), which now state the following:

>For some practical examples of bad IDs:
>
>* `com.github.foo.Bar`:
>
>    While a project may be hosted on GitHub it does not have any control over the `github.com` domain. Instead you should use `io.github` as shown above.

**Comment by nuttyartist** [comment]
The same one should be fine `io.github.nuttyartist.notes`. Thanks! 👍
