### ISSUE TITLE
Clicking on system tray icon should trigger show/focus main window

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#452]
As @Yasand123 said,

> Left clicking on the tray icon doesn't restore the window, you'd have to right click to bring up the context menu and then click on Show notes.

Left-clicking on the system tray icon should trigger show/focus main window.
Should clicking again (after the window is showing) hide the window? I don't think so.

**Comment by guihkx** [comment]
I also don't have strong feelings about what the preferred behavior should be.

I decided to toggle the visibility in #451, because a few Qt apps that I use daily, do that: KeePassXC, qBittorrent, RSS Guard.

But just let me know if you think we should not hide the window, and I'll tweak my PR.

**Comment by zjeffer** [comment]
I'm leaning more towards hiding the window when clicking the tray icon when the window is open. 

Someone who doesn't expect that workflow wouldn't left click the tray icon anyway, and people who do expect their windows to hide will be happy it works the way they expect. I'm one of the latter people :)

**Comment by nuttyartist** [comment]
Yes, I'm siding with hiding the window. It seems like most of the apps running on my tray are doing this as well.
