### ISSUE TITLE
Not rendering strikethrough when included korean spacing.

### ISSUE THREAD

**Issue by knifepjk** [nuttyartist/notes#457]
As you can see not rendering strikethrough when included korean spacing.
![image](https://user-images.githubusercontent.com/84360102/215373730-1ec060f6-cc79-4e7c-b6e2-c59256ea2b34.png)

**Comment by nuttyartist** [comment]
Hi! Thanks for reporting! We'll look into that.

**Comment by guihkx** [comment]
Can you please share that note in text format instead of an image? Thank you.

**Comment by knifepjk** [comment]
Hi! Here some text.

```
# 첫번째 노트

## 두번째 노트

### 제목
~한글 테스트~

~한글~

~~테스트~~
~~ 한글테스트~~

~~취소선 띄어쓰기~~

~~HELLO WORLD~~
```

**Comment by guihkx** [comment]
I can reproduce this using the 2.0.0 release on Windows 7, but not anymore on our nightly builds.

Can you please download a nightly Windows build from [here](https://github.com/nuttyartist/notes/actions/runs/4102179903) (Qt 5 or Qt 6, doesn't matter), test it, and report back?

Thanks!

**Comment by knifepjk** [comment]
Testing on a nightly build showed what I would expect. 👍
