### ISSUE TITLE
Show Icon of Notes in notification Area (systray)

### ISSUE THREAD

**Issue by theshadowx** [nuttyartist/notes#46]
instead of showing the app in task bar, I think it would be better to add an icon of the app in notification area. 

When the user clicks on 'X' in the app, it won't quit, just be hidden, and when the user would like to summon it, he/she click on the icon in the notification area, and then choose "show" to make the app appear, and in order to quit, he/she chooses "quit"

**Comment by nuttyartist** [comment]
I like the idea. I think what we should do is this:

When you hit '-' -> 'minimize', the app will minimize into the taskbar.
Why you hit 'x' -> 'close', the app will get hidden, and be available to show in two ways:

1. Through the system tray icon - left-clicking on it, or right-clicking on it and choosing "Show Notes".
2. Through a key shortcut like "Super + N" that would let the user create a new note from anywhere on the computer instantly - which is great.

Closing Notes would be by right-clicking on the system tray icon and choosing "Quit".
Notes also should start on the computer start-up. (Or at least have the option for that).

I will add this issue to our future releases milestones when will start working on them.

**Comment by alium** [comment]
Icon in systray will be super!

**Comment by theshadowx** [comment]
take a look at this : https://github.com/theshadowx/notes/tree/SysTray


![selection_201](https://cloud.githubusercontent.com/assets/976569/15221832/fabe28f0-1864-11e6-9565-4d065eb7fec0.jpg)

**Comment by alium** [comment]
@theshadowx:
tested and works :-)
Can you do it so, that when you click on the icon in the tray  will be application minimalized and click And with the new clicks the application will appear again?

**Comment by theshadowx** [comment]
@alium which OS are you using? we have some issue about icon not showing on in som OSes

**Comment by alium** [comment]
@theshadowx: I use Archlinux x86_64 and KDE Plasma 5.6.4 (notes is  compiled with Qt 5.6.0 )

**Comment by theshadowx** [comment]
@nuttyartist 
> Through a key shortcut like "Super + N" that would let the user create a new note from anywhere on the computer instantly - which is great.

I just checked about this, unfortunately Qt doesn't offer this kind of option.

The options that are available for shortcut : (http://doc.qt.io/qt-5/qt.html#ShortcutContext-enum)

- Qt::WidgetShortcut : The shortcut is active when its parent widget has focus.
- Qt::WidgetWithChildrenShortcut : The shortcut is active when its parent widget, or any of its children has focus. Children which are top-level widgets, except pop-ups, are not affected by this shortcut context.
- Qt::WindowShortcut : The shortcut is active when its parent widget is a logical subwidget of the active top-level window.
- Qt::ApplicationShortcut : The shortcut is active when one of the applications windows are active.

**Comment by nuttyartist** [comment]
So I guess we should do it in an os specific way, cause it's a really powerful feature that will help people to capture their thoughts right away.

**Comment by theshadowx** [comment]
I think buy using XCB library : libxcb (linux) it would be possible to grab the key from window manager.

**Comment by nuttyartist** [comment]
Seems like someone already did that, and it works for all major os's:

http://libqxt.bitbucket.org/doc/tip/qxtglobalshortcut.html
https://github.com/hluk/CopyQ/tree/master/qxt

**Comment by theshadowx** [comment]
I've seen the libxqt, but the problem is the fact using a big library for just shortcut.

Oh great the part we need was extracted from the whole lib !!! cool

**Comment by nuttyartist** [comment]
Haha yea
