### ISSUE TITLE
[Bug] Window buttons appears when any of the sidebar is toggled hide then show

### ISSUE THREAD

**Issue by CarterSnich** [nuttyartist/notes#465]
When you hide the folder tree or the notes list, then show it again, the window buttons (close, minimize, expand) appear even on the native window frame.

# Steps to reproduce
1. Open Notes (make sure sidebars are shown).
2. Use native window frame.
3. Hide the folder tree or the notes list.
4. Show the sidebar you hide.

![vokoscreenNG-2023-02-08_15-11-15](https://user-images.githubusercontent.com/52433531/217465805-27907d10-6f67-4b9c-8e34-0877bdbd018e.gif)

Version: 2.0.0
OS: Manjaro Linux 
Kernel: 5.15.89-1-MANJARO
DE: Plasma 5.26.5
WM: KWin

**Comment by guihkx** [comment]
Thanks for reporting, but this was already fixed by #344.

If you want, feel free to grab our development AppImage [from here](https://github.com/nuttyartist/notes/actions/workflows/linux.yml) and test it.
