### ISSUE TITLE
Inactive colors should be changed when changing color theme

### ISSUE THREAD

**Issue by zjeffer** [nuttyartist/notes#467]
Currently, when the window is not focused, the notes list looks like this in dark mode:

![image](https://user-images.githubusercontent.com/4633209/217637333-02bc331b-f429-464f-bb1c-cb9235055c89.png)

The white text in the selected note item is not visible because the inactive color is light gray (`207, 207, 207`). We should change the color of inactive items when changing themes. This same color is used in many places, so instead of changing it everywhere one by one, we should develop a more general solution.

**Comment by nuttyartist** [comment]
Oh good catch.

**Comment by guihkx** [comment]
Mildly related, but the links on the 'about' window should also use a better color for the dark theme:

![image](https://user-images.githubusercontent.com/626206/218238266-3b54a44d-6931-4215-96cd-3afa088b2058.png)
