### ISSUE TITLE
'Trash' and 'New' icons not shown

### ISSUE THREAD

**Issue by dplanella** [nuttyartist/notes#47]
On Ubuntu 16.04, the icons to create or delete a note do not seem to be loaded. See attached screenshot:

![captura de 2016-04-23 08-26-50](https://cloud.githubusercontent.com/assets/1689781/14759740/9bdafe94-092d-11e6-9030-2b8f157fc845.png)

**Comment by theshadowx** [comment]
Have you used the debian installer ? if that so, this issue is known  ( #24 ) and fixed in dev branch.

Could you please try the dev branch ?

Thanks

**Comment by nuttyartist** [comment]
What @theshadowx said.^

If you can't test the dev branch, we will let you know when the 0.9.0 will be ready so you can grab an installer and test it out.

**Comment by dplanella** [comment]
I tried both the Debian build and I built from source, but I hadn't noticed the dev branch. I'll give it a go there, thanks!

**Comment by dplanella** [comment]
Proper fix now submitted as https://github.com/nuttyartist/notes/pull/48
