### ISSUE TITLE
Resizing the window causes the width of the 'All Notes' panel to be reset

### ISSUE THREAD

**Issue by guihkx** [nuttyartist/notes#482]
I'm not sure if this is supposed to be intended behavior, but after we adjust the width of the 'All Notes' panel and then resize the window, the width gets reset:

https://user-images.githubusercontent.com/626206/219869627-b73252be-9733-4877-912a-bb25b704dce7.mp4

<br>

Should be reproducible on all platforms.

Feel free to close if this is intended behavior.

**Comment by zjeffer** [comment]
This happens with the 2.0.0 release as well. I'm not sure if it's intended, but I also think it shouldn't work like this. Not sure what the best solution is, though.

**Comment by nuttyartist** [comment]
Oyy, this is definitely not the intended behavior. Only the text editor should change in size.

**Comment by zjeffer** [comment]
This happens to both the left and middle pane btw, not just the All Notes pane.

After some more debugging I found that the splitter sizes get reset to the value that's in the settings, even before the resizeEvent method is called.
