### ISSUE TITLE
[Regression] [Linux] Window resizing is broken in frameless mode

### ISSUE THREAD

**Issue by guihkx** [nuttyartist/notes#483]
Window resizing in v1.5.0 (frameless mode):

https://user-images.githubusercontent.com/626206/219870703-41d77515-b652-43bd-a2e4-1997e93eed0f.mp4

<br>

Window resizing in v2.0.0 or `dev` (frameless mode):

https://user-images.githubusercontent.com/626206/219870792-bab25c1f-5d6c-4e2d-8a7c-4f8ca2db5eda.mp4

<br>

As you can see, we can't resize the window in v2.0.0 like we could in v1.5.0.

Because frameless mode is the default experience, we should probably fix this before releasing 2.1.0.

PS: This is unrelated to #454.

**Comment by nuttyartist** [comment]
Did we remove @theshadowx's code that did custom resizing?

**Comment by guihkx** [comment]
I haven't tried looking at that specifically, but I did try inspecting mouse move events in `ui->frame`, but for some reason they aren't being fired at all.

**Comment by guihkx** [comment]
Attempted to run a git bisect:

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
```

2a12e5f0dd924043443ae63de232f2928b08c630
3008e0c67a2df3d0cfe82864cf2cc3ed24796b2f
851bbaae6d5be627b077a46fdbf189e9182edd67
77df54658eaeb52c0d38f6a67f2779e998db7f90
f5ffee5915ecc43b367e61c58ac8da4f8d8beafe
109a310f8968f982edb89e1bc66b7b7903938ea4
edbf28792caa5d3dae3663964b3d9f2ee65e5896
6a15f426bbfe17fa5ec6ebe6a4dbd68bba2ce43e
755667efe27bd3d996fe12e9652b1ca9eb85d5ed
85c8f0ef39ade4b6b669a066d68c70f09ccfc55a
966e3d24f90fee4837099aa50ae78871c2e50873
ddd79edf077158e0e62cc2b432f669e60a7d9bfb

```
We cannot bisect more!
```

I could not build on any of these commits ...

**Comment by guihkx** [comment]
Oh, I think I've got it. After reverting some changes from this commit (they were mostly margin-related):

https://github.com/nuttyartist/notes/commit/ddd79edf077158e0e62cc2b432f669e60a7d9bfb

I can now resize the window on Linux again:

https://user-images.githubusercontent.com/626206/219931626-e593b93e-cf25-45dc-9137-e5d766b3c2d1.mp4

<br>

It's not immediately obvious to me if reverting those will break something else though, so do you remember exactly the reason behind those changes? I can't seem to find it on the pull request (#295) or the commits itself...

**Comment by nuttyartist** [comment]
Damn, I can't remember. I should have been more verbose in my commit message 😅. I think the margins made it look weird on some distros or something about the shadow. But I'll have to look again on Linux. I'll spin a Linux machine and test it today in a few hours.
