### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by passionate2023** [nuttyartist/notes#484]
Hi,

Is it possible to host this in Web and access from anywhere like web app?

Is there a chance of making it as web app?

Thanks

**Comment by nuttyartist** [comment]
Hi!

I'm not sure it's going to be easy. You can currently sync your notes (although maybe nor very reliably?) using dropbox or some other services.

We have plans to work on a mobile app tho. So that should cover most operating systems but not the web.

**Comment by guihkx** [comment]
Duplicated of #453
