### ISSUE TITLE
The app version should also be added to the About window

### ISSUE THREAD

**Issue by guihkx** [nuttyartist/notes#485]
Right now, the only way for users to check what version of Notes they're running, is by opening the update checker.

However, after #474 was added, we can now build Notes without any update checking feature, leaving users with no other place to check what version of Notes they're running.

My suggestion would be adding that information to the About window.

Perhaps another easy and nice addition would be adding what Qt version was Notes built against, and also what Qt version we're currently using to run Notes.

**Comment by nuttyartist** [comment]
Sounds good.
