### ISSUE TITLE
Maximized window overlaps desktop environment

### ISSUE THREAD

**Issue by Tomoms** [nuttyartist/notes#49]
On Ubuntu 16.04, I have installed Notes as a snap app. When I maximize a window of this program, it overlaps Unity's dash and the top menu bar, basically it goes fullscreen.

**Comment by nuttyartist** [comment]
If you maximized it using the green button that's the way it was intended - to go fullscreen.
If you want just to maximize it you can double click on some blank area at the top of the app or use the Ctrl + Shift + L shortcut.

**Comment by Tomoms** [comment]
Wow! I didn't knew this, sorry.
Thanks for replying.

**Comment by nuttyartist** [comment]
No problem, hope you enjoy using the app.
