### ISSUE TITLE
We can drag the window by grabbing on places other than the "title bar"

### ISSUE THREAD

**Issue by guihkx** [nuttyartist/notes#494]
Another episode of "note sure if this is a bug or intended behavior" 😄 

I'm not sure if this is Linux specific, but right now in frameless mode we can grab and drag the window from places other than the "title bar":

https://user-images.githubusercontent.com/626206/220690891-613bed70-9adf-49ed-b9c8-a5b9bb530232.mp4

<br>

Does that look correct? Or should we only be able to move the window by grabbing the title bar? The part I highlighted in red here:

![image](https://user-images.githubusercontent.com/626206/220690734-da7ca8ee-f6f4-4bb0-a01d-54dbd5ae9a0e.png)

**Comment by bjorn** [comment]
Personally, I think the behavior is fine given that there is no clear separate between "title bar" and the rest of the window.

**Comment by guihkx** [comment]
Yeah, it's fine, I think.

But we should still probably disable that behavior when using native window decorations, no?

**Comment by bjorn** [comment]
> But we should still probably disable that behavior when using native window decorations, no?

Yeah, I guess so too.

**Comment by nuttyartist** [comment]
It used to be the intended behavior but I don't think that's correct. It's better we allow moving only from the top part you highlighted.

> But we should still probably disable that behavior when using native window decorations, no?

Yes, definitely.

**Comment by guihkx** [comment]
>But we should still probably disable that behavior when using native window decorations, no?

I just noticed that this one has been fixed by accident in 095a6137d86d22a775c2f2bb8a40cb4029c53a9d, nice. :)

>It's better we allow moving only from the top part you highlighted.

Okay, I'll try to fix that.
