### ISSUE TITLE
Issues with Windows build for 2.1.0

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#496]
I'm testing the Windows build now. While there aren't major issues, here are some points:

~1. Clicking on the Notes icon in the task manager doesn't seem to minimize it back to the task manager (although system tray works well). I forgot if it's a known problem or not.~ EDIT: doesn't seem like a problem anymore.
2. Some windows have a question mark button on their title bar:
![Screen Shot 2023-02-23 at 11 00 05 AM](https://user-images.githubusercontent.com/16375940/220871397-a7721c5c-4367-4bf2-ac84-76eef78d76f6.png)
![Screen Shot 2023-02-23 at 11 04 31 AM](https://user-images.githubusercontent.com/16375940/220871408-13c23b37-cf6a-44d2-98e4-75f0ce8e5a4a.png)
3. Many styling issues. Many buttons look extremely old. See the scroller in the Updater window above and the About window. And the tick box in the updater window. Also here in these buttons and context menu:
![Screen Shot 2023-02-23 at 11 05 26 AM](https://user-images.githubusercontent.com/16375940/220871822-dd71f67a-3b81-4ca0-a828-4d240db97856.png)
![Screen Shot 2023-02-23 at 11 09 30 AM](https://user-images.githubusercontent.com/16375940/220871831-5d97b7e2-e789-4f86-a178-7a63361398c1.png)

Is it only solved by custom styling?

BTW, I'm getting an error trying to compile Notes. I want to test a couple of things (making sure updater works, some styling things, etc...). Any idea how can I solve this?

![Screen Shot 2023-02-23 at 11 34 41 AM](https://user-images.githubusercontent.com/16375940/220871996-a9f89ecb-b046-4d64-8873-467868eb09be.png)

**Comment by bjorn** [comment]
> 2. Some windows have a question mark button on their title bar:

I guess you were testing with Qt 5 builds? Since this question mark should be disabled by default in Qt 6. For Qt 5 builds, we can get rid of it by setting an application attribute:
```c++
#if QT_VERSION < QT_VERSION_CHECK(6, 0, 0)
    QCoreApplication::setAttribute(Qt::AA_DisableWindowContextHelpButton);
#endif
```
(Not sure what is our minimum Qt version, but this attribute is available since Qt 5.10 - before that, the flag had to be disabled for each window separately)

> 3. Many styling issues. Many buttons look extremely old. See the scroller in the Updater window above and the About window. And the tick box in the updater window. Also here in these buttons and context menu:

Looks like we're not shipping the Windows Vista style plugin, which should be in `plugins\styles\qwindowsvistastyle.dll`.

> BTW, I'm getting an error trying to compile Notes. I want to test a couple of things (making sure updater works, some styling things, etc...). Any idea how can I solve this?

Not sure why CMake can't find the compiler. Is a suitable compiler selected in the selected Kit (see Projects > Manage Kits)?

**Comment by nuttyartist** [comment]
> I guess you were testing with Qt 5 builds?

You're right, this doesn't occur with the Qt6 build.
![Screen Shot 2023-02-24 at 2 39 10 PM](https://user-images.githubusercontent.com/16375940/221185636-66678075-5bee-4443-9336-d54010a4024c.png)
![Screen Shot 2023-02-24 at 2 37 31 PM](https://user-images.githubusercontent.com/16375940/221185638-9611aa5b-b27c-46c2-9ff6-c504e513f8b2.png)

![Screen Shot 2023-02-24 at 2 37 44 PM](https://user-images.githubusercontent.com/16375940/221185633-160ae897-a1f5-480e-a90c-dbbad027becc.png)

But I used the installer to install the app, why did it pick the Qt5 build over Qt6?

> For Qt 5 builds, we can get rid of it by setting an application attribute:

That's should be better.

> Not sure why CMake can't find the compiler. Is a suitable compiler selected in the selected Kit (see Projects > Manage Kits)?

I reinstalled Qt with Mingw and now everything works fine. I tested the updater and everything seems to work well.

**Comment by guihkx** [comment]
>But I used the installer to install the app, why did it pick the Qt5 build over Qt6?

That seems wrong. The Qt 5 build should only be installed on 32-bit Windows (or Windows 7).

**Comment by nuttyartist** [comment]
That's weird, then... Can you reproduce the issue?

**Comment by guihkx** [comment]
I can, actually... I'll send a PR to fix it.

**Comment by nuttyartist** [comment]
We can close this due to #502 :)
