### ISSUE TITLE
Question: Notes data file(s) on Windows

### ISSUE THREAD

**Issue by apulley** [nuttyartist/notes#51]
Apologies if this isn't the right forum, but would there be a directory on Windows that would have the notes data so I could copy it over to a new machine?

Thx! (Love the app!)

**Comment by nuttyartist** [comment]
It's should be in:
C:\Users\user\AppData\Roaming\Awesomeness

**Comment by nuttyartist** [comment]
Did it solve your problem?

**Comment by apulley** [comment]
I got it now .. this was perfect. Thank you!
