### ISSUE TITLE
MAC OS window buttons on WINDOWS

### ISSUE THREAD

**Issue by Oppa-YA** [nuttyartist/notes#527]
Seriously guys, when i opened the program I have a good laugh. Thanks for that.
Who decided to make mac OS interface left side buttons on windows version?
I never seen a single program that use left side buttons on windows.
Can you please use standard windows GUI? Thank you.

**Comment by zjeffer** [comment]
Hi, thanks for your feedback.

This has already been changed in the latest master: https://github.com/nuttyartist/notes/pull/526. This will be fixed in the next release.

For now, you can change the window to use native decorations in settings (top right) -> view -> use native window frame.

**Comment by Oppa-YA** [comment]
Thank you for answer!  I found a settings now. Would be cool to have a dark theme too.

**Comment by zjeffer** [comment]
Dark theme can be found in the menu when clicking the Aa button on the top left of the editor window. We have an open issue to improve this: https://github.com/nuttyartist/notes/issues/523

**Comment by nuttyartist** [comment]
Yes, like @zjeffer you can change the theme by clicking this button here:

![Screen Shot 2023-03-13 at 11 07 23 AM](https://user-images.githubusercontent.com/16375940/224656376-4cac8efd-fc31-4603-b772-73a49e844de7.png)
