### ISSUE TITLE
folders tree not showing up at all (elementary os)

### ISSUE THREAD

**Issue by ramardoautistin** [nuttyartist/notes#531]
the app was working great yesterday, but when i started up this morning the folders tree wasn't showing up at all, no matter how much i clicked the icon. i opened the settings and it appears that the app is indeed showing and hiding the folders, it's just that the ui simply doesn't reflect that. i restarted my computer and the problem persisted. please help! i love the app in general and i hope this is easily fixable :)

![it's stuck](https://user-images.githubusercontent.com/128057719/225640427-05c3cc32-1604-45be-a7cc-9a078b5fd4a4.png)

**Comment by nuttyartist** [comment]
That's very weird. Have you tried using the keyboard shortcut <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>J</kbd>?
If it doesn't work, you can 
1. De-select menu->Hide to tray. (on ElementaryOS apps don't live on the tray so it's just confusing to have it on)
2. Quit the app. 
3. Run the app again.

If this doesn't work:
1. Quit the app.
2. Remove `~/.config/Awesomeness/Settings.ini` (This file doesn't contain any data of your notes so it's safe to delete, but make sure not to delete `notes.db`).
3. Start Notes again.

Let me know if the problem still persists.

**Comment by ramardoautistin** [comment]
just tried searching for that file but i'm not really sure where it could be. i copied that path and also searched for the settings file individually but it's not showing up. where are the notes app files supposed to be in my file system? (sorry i'm really new to this)

**Comment by nuttyartist** [comment]
@ramardoautistin Don't worry, we've all been newbies sometimes. You can open the file explorer in Elementary and go to your `user` folder. Then, you will need to enable the option to show hidden files. I'm not sure what's the keyboard shortcut for that on Elementary but I think it's <kbd>Ctrl</kbd> + <kbd>H</kbd>. Then go to `.config/Awesomeness` you should see inside the `Settings.ini` file.

**Comment by ramardoautistin** [comment]
just tried but there are no hidden files at all inside my user folder... lol

**Comment by guihkx** [comment]
Oh, you probably installed it using our Flatpak package.

The `Settings.ini` file should be in `/home/yourself/.var/app/io.github.nuttyartist.notes/config/Awesomeness` instead.

However, I think this is a bug that should be investigated.

It'd be great if you could reproduce the problem again on a clean config (and then share the exact reproduction steps with us).

**Comment by bjorn** [comment]
I would suggest, before removing that file, to make a copy, because it could be useful in reproducing the problem.

**Comment by ramardoautistin** [comment]
no idea how i would exactly reproduce the problem, however i'll share my current settings which probably produced the bug:

https://drive.google.com/file/d/1-WsskW2YDwRz9b2Em77SojpgHXHcIndA/view?usp=sharing

after deleting that it works just fine again, so thank you very much!

**Comment by ramardoautistin** [comment]
great, thanks!!

**Comment by bjorn** [comment]
Let's keep the issue open until it's fixed. :-)
