### ISSUE TITLE
Confirm Dialog on Pressing Delete

### ISSUE THREAD

**Issue by newterminator** [nuttyartist/notes#54]
Hi,
I just wanted to mention to have a dialog pop-up to confirm a deletion. I just deleted one important note as I was hovering over the notes app while getting to an another window and accidentally hit the delete button.

**Comment by nuttyartist** [comment]
Hey @newterminator,

We actually believe that users should delete notes fast and restore those as fast.

I do know how it feels. While developing Notes I lost a lot of notes myself, it feels like part of your brain vanished. But I have great news for you. While we don't yet offer an easy way to restore notes (we will implement trash and folders in future versions), we created a file (database) to store all the the deleted notes, cause we though people may expirience what happend to you. You can find it in: /home/ruby/.config/Awesomeness/Trash.ini
(Back it up before accessing)

While you can't see its content in Notes, you can search in the file for your lost note.

Update on your situation.
Hope everything goes fine.

**Comment by theshadowx** [comment]
Maybe we should add a trash section where it would be possible to restore the removed notes.

**Comment by nuttyartist** [comment]
Sure, in the folders view there will be a 'Trash' folder.

**Comment by newterminator** [comment]
Hey @nuttyartist , Thanks for getting back to me. And a huge relief that by your guidance I was able to get that note back from the database location. 

Yeah I believe your vision of having a quick deletion coupled with a 'Trash '  folder will be awesome. So even if the button is hit by accident there is also a quick recovery. Super good!

Looking forward to the future releases. I actually keep opening get-notes.com to check for a newer version every 5-6 days.

**Comment by newterminator** [comment]
Hey @nuttyartist , A big THANK YOU to all you guys involved in releasing 0.9 version. The new and delete icons are there, and also the close and minimize buttons look better on this one. Just awesome.

**Comment by nuttyartist** [comment]
Glad you like it. A really big shout-out to the various contributors.
Thanks.

**Comment by lovebdsobuj** [comment]
Which version will have **Trash folder** feature?

**Comment by nuttyartist** [comment]
@lovebdsobuj The one after the next release (1.0.0).

**Comment by lovebdsobuj** [comment]
That will be very good.

_Off-Topic:_
Search function should search `title` & `note` text. @nuttyartist

**Comment by theshadowx** [comment]
@lovebdsobuj coud you please add an issue about the feature you want to be added

**Comment by nuttyartist** [comment]
@lovebdsobuj Yes, please create a new issue for that matter.

The **title** is just the fist line of the **note's text**. And the search function searches the entire of the note's text, so it searches both the **title** and **note's text**. If that doesn't answer your question, you may open a new issue and we'll discuss there.
