### ISSUE TITLE
privacy policy?

### ISSUE THREAD

**Issue by crimsonduelist** [nuttyartist/notes#553]
Any data collected?

**Comment by guihkx** [comment]
No user data is collected by the app whatsoever.

However, I think this information should be properly documented, and probably added to the website too.

**Comment by nuttyartist** [comment]
Like @guihkx said, our app doesn't collect any data.

Our website (get-notes.com) in contrast, does because I use Google Ads and Google Analytics there (this is why there's a privacy policy there).

> However, I think this information should be properly documented, and probably added to the website too.

More than this?

![Screen Shot 2023-03-19 at 5 48 45 PM](https://user-images.githubusercontent.com/16375940/226187712-8edadad8-0479-4318-a3e6-22e0c0e2ba9e.png)

**Comment by guihkx** [comment]
LOL.

But I was thinking more of adding this information to the dedicated Privacy Policy page, which already exists: https://www.get-notes.com/privacy-policy

**Comment by nuttyartist** [comment]
This privacy policy only exists for the website. I think legally (and probably morally as well), if we don't track anything at all in our app (which we don't) then there's no need for a privacy policy.

**Comment by guihkx** [comment]
It's your call, but I disagree. I've seen open source projects with a Privacy Policy page, where they just state they don't collect nor track anything.

I think it's more about avoiding ambiguity and potentially confusing users (like this thread, or [this one](https://github.com/nuttyartist/notes/discussions/530)).

**Comment by nuttyartist** [comment]
Fair point. Let's create a short privacy policy file and add it to `/docs` and link it in `README`.

**Comment by guihkx** [comment]
As of 2.2.0, a Privacy Policy was introduced:

- https://www.get-notes.com/notes-app-terms-privacy-policy

Now I think it's just a matter of referencing it on useful places, like the README and inside the app.

We already reference it inside the app (in the Pro Activation window), but maybe it'd make more sense to have it referenced in the about window as well?

**Comment by nuttyartist** [comment]
> We already reference it inside the app (in the Pro Activation window), but maybe it'd make more sense to have it referenced in the about window as well?

Yep, totally agree. Both In the About window and README.
