### ISSUE TITLE
Build not outputting exe

### ISSUE THREAD

**Issue by fruitTheory** [nuttyartist/notes#555]
Not sure what's going, system is windows
cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
-- Trying to find Qt 6...
-- Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR)
-- Success! Configuration details:
-- App name: Notes
-- App version: 2.1.0
-- Qt version: 6.5.0
-- Update checker: ON
-- Build type: Release
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Programming/Git/notes/build

--install build --prefix build
-- Install configuration: "Release"
CMake Error at build/cmake_install.cmake:36 (file):
file INSTALL cannot find "C:/Programming/Git/notes/build/Notes.exe": No error.

Has same issue building to different directory as well, any ideas?

**Comment by guihkx** [comment]
Oops. I forgot to add to the Windows and macOS documentations the command to actually build the program... lol

After configuring the project with `cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release`, you have to build with:

```
cmake --build build
```
