### ISSUE TITLE
How to embed an image

### ISSUE THREAD

**Issue by Rasterisko** [nuttyartist/notes#557]
Hello!

Is there a way to put an image in a note?

Thanks!

**Comment by nuttyartist** [comment]
Hi! Not yet, but it's on our roadmap, see #317. Right now if you drag a picture to the editor you will see a link to the picture, that if you click it will open the picture.

**Comment by nuttyartist** [comment]
I'll close this since we're tracking this on #317.

**Comment by zjeffer** [comment]
Forgot to close? ;)
