### ISSUE TITLE
CTRL+SHIFT+(+) and F11 doesn't work

### ISSUE THREAD

**Issue by ShockedCoder** [nuttyartist/notes#568]
I try to increase the size of the header, and after that, I try to exit fullscreen only to realize F11 and Esc don't work at all.
https://user-images.githubusercontent.com/40272709/230957973-87fa16e5-c2e8-424a-9d28-4e543489056f.mp4

EDIT: The scrolling suddenly started working after I turned the native window frame off and on again.

**Comment by zjeffer** [comment]
Which platform are you using? And which Qt version?

Increasing/decreasing the header size works for me. As for the fullscreen shortcut, it should be Ctrl + Shift + F. I'll look into adding F11 as an alternative.

**Comment by zjeffer** [comment]
(reopening to see if header size adjustment issue is fixed)

**Comment by ShockedCoder** [comment]
> Which platform are you using? And which Qt version?

Linux. The Qt version of the app depends on which version the program prefers, since I still have both Qt5 and Qt6 installed, because of some old programs that still need Qt5.

Sorry for the late reply.

**Comment by zjeffer** [comment]
> The Qt version of the app depends on which version the program prefers, since I still have both Qt5 and Qt6 installed, because of some old programs that still need Qt5. 

You can see the Qt version the app is running with at the bottom of the About window, which can be found by clicking the 3 dots in the upper right corner of the app, and then clicking "About Notes"

**Comment by ShockedCoder** [comment]
Oh right, the version is 6.4.3 then. 
![image](https://user-images.githubusercontent.com/40272709/232250569-5e77b398-606e-4c1e-a78b-5b8a58c4dbbb.png)

**Comment by zjeffer** [comment]
I can think of four things that are causing this issue:

1. Something is wrong with the app itself
2. You're pressing the correct buttons, but they are getting caught before they reach the Notes app (i.e. your OS or another program is catching them)
3. You're pressing the correct buttons, but your OS is translating them differently (maybe the CTRL+SHIFT combination causes the + and - to translate to something else). What's your keyboard layout?
4. You're pressing the wrong buttons

**Comment by ShockedCoder** [comment]
1. Unless something went wrong in building it I don't think that's it
2. I checked the system key-binds and didn't find anything conflicting. (Maybe a key-bind detector program of sorts would help with figuring that out?)
3. My keyboard layout is Finnish, and considering how the - works perfectly I don't think it's that
4. I doubt it

**Comment by zjeffer** [comment]
You can try the `xev` tool to see what your keyboard is typing. Install it and run it with `xev -event keyboard`. 


I just noticed that for me, increasing and decreasing works with these buttons (QWERTY keyboard):

![image](https://user-images.githubusercontent.com/4633209/232251773-5c728397-4f49-4418-8005-0d0dd4ab439b.png)

But increasing doesn't work with the numpad buttons, only decreasing. I'll look into why this happens.

**Comment by ShockedCoder** [comment]
I ran `xev -event keyboard` and got this
![image](https://user-images.githubusercontent.com/40272709/232251859-aacee91f-3ed9-4ed4-8ace-9ff35714b3b6.png)

**Comment by zjeffer** [comment]
Found it, see the pull request ^

As for how xev works, you put your cursor in the white window, and start pressing buttons. The output will appear in the terminal you're running xev from.

**Comment by ShockedCoder** [comment]
Looking at `xev` output it didn't seem like anything was intercepting it, so that's cleared off, ig.

I'll pull the commit and see if it's fixed

**Comment by zjeffer** [comment]
You can wait until the Github Action is done if you don't want to compile it yourself: it will produce AppImages that you can run to test.

**Comment by ShockedCoder** [comment]
It works :+1:

**Comment by nuttyartist** [comment]
Yay, thanks @zjeffer!
