### ISSUE TITLE
Question: auto-save options?

### ISSUE THREAD

**Issue by apulley** [nuttyartist/notes#57]
It would might nice to throttle the auto-save somehow. It's anecdotal for now, but I believe it might be indirectly causing performance issues in my specific situation.

**Comment by theshadowx** [comment]
what problems do you have with auto-save? could you please specify the specifications of your PC.

Thanks

**Comment by apulley** [comment]
I believe I have a anti-virus that's being triggered by the auto-save ... I'll investigate and follow up here. Thx for the quick response.

**Comment by nuttyartist** [comment]
What's the current situation?

**Comment by nuttyartist** [comment]
Waiting for response...
