### ISSUE TITLE
Website Images Look off on iPhone SE 2nd Gen

### ISSUE THREAD

**Issue by maxmunzel** [nuttyartist/notes#573]
![IMG_0749](https://user-images.githubusercontent.com/5411096/232252080-e7034f7c-e3dd-4ba0-9e7c-317f3e259966.png)
Hi!

The app looks great, but on my iPhone the images render slightly stretched horizontally. This makes the typography look kind of goofy.

Should be easy to fix and give this app the representation it deserves.

Best

Max

**Comment by nuttyartist** [comment]
Thanks for the heads up! I will see what I can do for now. I'm planning to re-design the website soon.
