### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#59]
We should support automatic updates on Windows.
It should be fairly easy according to Inno Setup: http://www.jrsoftware.org/ishelp/index.php?topic=technotes
##

**Comment by theshadowx** [comment]
appveyor.com allows to compile and deploy the app for Windows each time there is a build. it's like Travis-CI but for Windows.

After compiling, it can send the exe to github, there is also a feature to use some tools for packaging for windows and send the resulted executable to github

**Comment by nuttyartist** [comment]
That's cool, looks promising. I authorized it and I will set it up (Seems to be fairly easy) later.

**Comment by alex-spataru** [comment]
I have a library that allows the application to check and download for updates automatically, regardless of the platform. It does that by downloading a JSON file that specifies the latest version and the download link for each platform. 

Let me know if you want me to integrate your application with my library :)

**Comment by nuttyartist** [comment]
Hey alex,

Your QSimpleUpdater looks cool. It's mechanism is pretty similar to what we want to make. We want AppVeyor to package our app when committing to master and create the Inno Setup executable, and to create something like your QSimpleUpdater to check for new version and if there are any it will download the build AppVeyor created and install the app silently like said [here](http://www.jrsoftware.org/ishelp/index.php?topic=technotes).

We want to strive on getting the most natural and native way of updating our app for users. So we'll stick with that approach only on Windows. (For Linux, we want to upload it to the official repos #60). 

It'll be great if you could implement that. You are welcome to chat with us on [Gitter](https://github.com/nuttyartist/notes) for better discussion.

**Comment by alex-spataru** [comment]
@nuttyartist Thanks! I will begin integrating the QSimpleUpdater with your project, once I have that, I will customize the install command to fit the needs of this project.

**Comment by nuttyartist** [comment]
@alex-spataru Sounds great.

**Comment by theshadowx** [comment]
QSimpleUpdater should be used just for windows, as it may break the other type of package management

**Comment by alex-spataru** [comment]
@theshadowx I will take your request into account. Do you plan to use a different update mechanism for OS X? Or should I disable the QSimpleUpdater only when compiling for Linux?

**Comment by theshadowx** [comment]
I think it would be better if you implement it as if there is no constraint and then will see when it should be activated

**Comment by nuttyartist** [comment]
@alex-spataru The update mechanism with QSimpleUpdater should be only for Windows. On MacOS we should aspire to upload our app to the Mac store so people could update it through that. It requires us to register as Apple developers so it requires a bit of cash and a Mac computer (If I remember correctly).

**Comment by theshadowx** [comment]
@nuttyartist  does it require cash even if the app is free ?

**Comment by nuttyartist** [comment]
Yes. https://developer.apple.com/support/compare-memberships/

**Comment by theshadowx** [comment]
I don't think so : 

> If you’re looking to develop apps for Apple platforms, download the Xcode developer tools, SDKs, and resources for free on the Xcode downloads page. Program membership is not required. If you don’t already have an Apple ID, you can create one here.

**Comment by nuttyartist** [comment]
Yes, but to distribute it through the Aapp Store and to have a developer ID you have to pay. see the chart at the bottom.

**Comment by theshadowx** [comment]
sad :(

**Comment by nuttyartist** [comment]
haha, we'll find a way to do it one way or another.

**Comment by nuttyartist** [comment]
Automatic updates, done simple and elegantly will allow our users to get the latest version into their hands flawlessly, and for us to distribute our app with greatest features instantly.

The way it should work is like this:
- The app checks when running the app, or in the background if it's already running (on very large intervals) if there is a newer version. 
- If there's a newer version, the "updateWindow" will pop up.
- You can access the "updateWindow" in anytime by clicking on the (future) 3 dots button, and by choosing "Check For Updates".
- The "updateWindow" will show the current version installed, and: 1. If there is a new version it will show the version number, What's new (change log), and the "Update" button will be clickable. 2. If there isn't a new version it will show "Everything is up-to-date". 3. It will show "There is an internet connection problem" if there is one.

Things to note:
- I guess the app will check for a new version in the [Updates.json](https://github.com/nuttyartist/notes/blob/dev/UPDATES.json) file from the Github repo?
- When committing for a new release - in the master branch, AppVeyour will take to compile and package it into an installer. (I checked and there are some problems running the installed artifact, @theshadowx can you investigate?)
- The app will download the artifact (the resulting installer) from the link specified in the Updates.json file and install it through the commands [here](http://www.jrsoftware.org/ishelp/index.php?topic=technotes).

Do you have suggestions? Corrections?

@alex-spataru You seem qualified for this, I'm sure you can do a good job. What do you say, will you do it? You can always ask me or @theshadowx for info and we'll be glad to help.

**Comment by alex-spataru** [comment]
I can do that, basically everything is already supplied by the QSimpleUpdater, including the update windows and the changelogs. I just need to show if there is a network problem.

You may want to try the [QSimpleUpdater Example App](https://github.com/alex-spataru/QSimpleUpdater/tree/master/tutorial), which allows you to toggle the different options of the library and see what it does. Let me know if the dialogs presented by the QSimpleUpdater are good enough, or if we should re-implement/change the update dialogs for this project.

**Comment by nuttyartist** [comment]
Yes, the update dialog should be done a bit differently. Much simpler. There should be only one dialog, nothing else pop-ups. The user click the (future) 3 dots button and the dialog shows up, or when a new version is detected, the dialog will show up.

The title of the dialog (the label) will always show the status - one of these: **1**. "New version available". **2**. "Everything is up-to-date". **3**. "There is an internet connection problem".

The dialog will have 2 buttons: "Close" and "Update".
The Update button will be clickable only in scenario 1.

On scenario **1**:
- It will show the version number of the newer version.
- It will show "What's new:" and the content of the change log will follow underneath. 
- If the user clicks on "Update" it will show the progress bar, it will download the newer version and install it right away, silently, and re-open the app with the new version.

On scenario **2** & **3**:
- Only the title will be shown and only the "Close" button will be interactable.

On **all** the scenarios:
- It will show the "Current version:" with the number of the currently installed version.

**Comment by theshadowx** [comment]
@nuttyartist what is the problem with appveyor artifact ?

**Comment by theshadowx** [comment]
By the way, what about windows app store

**Comment by nuttyartist** [comment]
@theshadowx When installing the app using the latest artifact, and then running the app, I got some errors of missing DLL's.

mm.. didn't think about that. I bet stupid Microsoft won't handle updates better than us. The only reason I see for uploading Notes to the store is that people will be able to discover it. But who use that store anyway? I haven't used Windows 10 regularly, so I need to play around with it to see how good/bad it is.

**Comment by alex-spataru** [comment]
@nuttyartist What DLLs are missing? You may need to run `windeployqt` to get the app to run on Windows.

**Comment by theshadowx** [comment]
dll of visual studio runtime

**Comment by nuttyartist** [comment]
@alex-spataru It does [run](https://github.com/nuttyartist/notes/blob/dev/appveyor.yml#L45) `windeployqt`.

@theshadowx I don't remember I needed to add those when I packaged it manually.

**Comment by theshadowx** [comment]
because you have it in the PATH, so I think it wasn't necessary to be added

**Comment by nuttyartist** [comment]
ah ok.

**Comment by theshadowx** [comment]
@nuttyartist I have fixed the problem for artifact missing dll [here](https://github.com/theshadowx/notes/commit/2549773ca4d37f884d48b8d567b116d8c3ba5438)

**Comment by nuttyartist** [comment]
@theshadowx Awesome, it works well now. Can you send a pull request?
