### ISSUE TITLE
Haiku port

### ISSUE THREAD

**Issue by Begasus** [nuttyartist/notes#590]
Quick note that Notes has been added to haikuports repository and is available for 32bit and 64bit Haiku installations, thanks for the lovely app!

![Notes](https://github.com/nuttyartist/notes/assets/16057090/6bb17d64-f635-422f-8f30-a55ac93786f2)

**Comment by Begasus** [comment]
PS, as it just for letting you know it's here, this can be closed. :)

**Comment by zjeffer** [comment]
Cool! I'd never heard of Haiku OS before, looks interesting! Thanks for letting us know.

**Comment by guihkx** [comment]
That's awesome!

**Comment by nuttyartist** [comment]
Awesome! Thank you, @Begasus.

Just a reminder that you can switch to native window decoration by clicking the 3-dots-button->View->Use native window frame. Maybe it'll fit better in Haiku that way (this will be the default setting from next release).

**Comment by Begasus** [comment]
Thanks, looking much better now :)

![Notes-2 1 0](https://github.com/nuttyartist/notes/assets/16057090/db1df800-7d86-4b71-8363-b7ba5d0091ee)
