### ISSUE TITLE
Text contrast in Sepia theme is weak

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#600]
As @Stefanoko reported in #599, the contrast between the text color and Sepia theme color is weak. We need to find a better color.

**Comment by Stefanoko** [comment]
Thanks for taking this into consideration.
The inverse color of the Sepia background were a dark blue, something like RGB 4,15,38 or #040F26.

I would not mind the bluish hue at all, but for other users, it might ruin the Sepia look.

Whatever you come up with, I am sure it will provide better contrast than the current colors.

**Comment by nuttyartist** [comment]
Done in #601
