### ISSUE TITLE
Windows version 2.1 does not detect availability of version 2.2.

### ISSUE THREAD

**Issue by vlasky** [nuttyartist/notes#606]
I had to manually download the installation package from GitHub and run it.

**Comment by nuttyartist** [comment]
Working now?

**Comment by vlasky** [comment]
Sort of. It now detects version 2.2, but after I perform the update, the version is still 2.1.0+g536a350 and it tells me once again that new version 2.2 is available.

**Comment by nuttyartist** [comment]
Yes, what an unfortunate mistake on my part. We'll resole this as soon as possible.
