### ISSUE TITLE
Note counters in folder list always 0

### ISSUE THREAD

**Issue by movrajr** [nuttyartist/notes#608]
![image](https://github.com/nuttyartist/notes/assets/6113256/37991269-cb53-4dbb-8511-22039145417f)

**Comment by zjeffer** [comment]
Weird, is this on Windows? I don't have this bug. 

Could you send us your notes.db file? For Windows, this should be under `<USER>/AppData/Roaming/Awesomeness/notes.db`.

**Comment by nuttyartist** [comment]
I have a feeling that's related to a corrupted database. Can you try first backing up your notes as @zjeffer said in `<USER>/AppData/Roaming/Awesomeness/notes.db`. Save a copy of that file somewhere safe. Then, in Notes, export your notes to `.nbk` file by going to `Gear icon -> Import/Export Notes -> Export` then save it somewhere. Delete the content of `<USER>/AppData/Roaming/Awesomeness/notes.db` (but please make sure you saved a copy somewhere first). Now quit Notes and import the `.nbk` file you saved. By going to `Gear icon -> Import/Export Notes -> Import `.

Let me know if it fixes the problem.

**Comment by movrajr** [comment]
It's on Windows. After restarting Notes the counters are updated, but when adding new notes the counters won't change again.

**Comment by nuttyartist** [comment]
Have you tried what I wrote?

**Comment by movrajr** [comment]
In the process of doing that.

**Comment by movrajr** [comment]
It worked! 

I was actually just writing a two cents on a different issue where I mention a deleted note due to a duplication bug in a pre-2.0 version. The database may well have been corrupted back then.

**Comment by nuttyartist** [comment]
Yes, I remember I had similar issues and this solved them. Glad it worked (:
