### ISSUE TITLE
Option to disable the confetti upon completing all tasks in a column in kanban mode

### ISSUE THREAD

**Issue by Delta-official** [nuttyartist/notes#619]
It's very distracting and i can imagine that there can be some accessibility issues regarding it

**Comment by nuttyartist** [comment]
Alrighty, I'll make this optional in next version. Do you think it should be opt in (meaning off by default)?

Thanks for the feedback!

**Comment by Delta-official** [comment]
I imagine that would be for the best

**Comment by nuttyartist** [comment]
Gotcha. Thanks! If other people want to approve/dissaprove please do.
