### ISSUE TITLE
Icons not showing properly

### ISSUE THREAD

**Issue by ghost** [nuttyartist/notes#620]
![Screenshot_20230729_215044](https://github.com/nuttyartist/notes/assets/140826895/648ce147-235c-4e7d-9515-d2582287c512)
This happens if compiled from source, and also in the Appimages (both Qt5 and Qt6).
Running on KDE Plasma 5.27.6, Xorg, Arch Linux.

**Comment by zjeffer** [comment]
Happens to me too, also on Arch Linux, running Hyprland.

I haven't found a cause yet. The appimage works fine if you want to use that instead.

**Comment by nuttyartist** [comment]
Is there any way I can reproduce this in Fedore with Gnome or PopOS? If not, is it possible with Kubuntu?

**Comment by samegit3** [comment]
I just tested with Fedora and Kubuntu, both don't have the problem.

**Comment by guihkx** [comment]
I'm on also on Arch and the icons show up just fine here.

Can you attach a text file here with the output of:

```
$ QT_LOGGING_RULES='qt.text.font.*=true' notes
```

**Comment by zjeffer** [comment]
[notes-fonts.log](https://github.com/nuttyartist/notes/files/12209461/notes-fonts.log)

**Comment by guihkx** [comment]
In your logs, every time the app requests for the `Font Awesome 6 Free Solid` font (which we bundle), for some reason Qt returns `Font Awesome 6 Free`:

```
qt.text.font.match: QFontDatabasePrivate::match
  request:
    family: Font Awesome 6 Free Solid [-- any --], script: 2
    styleName: -- any --
    weight: 400, style: 0
    stretch: 0
    pixelSize: 17
    pitch: *
qt.text.font.match:   REMARK: looking for best foundry for family 'Font Awesome 6 Free' [1]
qt.text.font.match:           looking for matching style in foundry 'AWSM' 2
qt.text.font.match:           best style has distance 0x0
qt.text.font.match:           found smoothly scalable font (17 pixels)
qt.text.font.match:           found a match: score 0 best score so far ffffffff
```

On my logs, we see this instead:

```
qt.text.font.match: QFontDatabasePrivate::match
  request:
    family: Font Awesome 6 Free Solid [-- any --], script: 2
    styleName: -- any --
    weight: 400, style: 0
    stretch: 0
    pixelSize: 17
    pitch: *
qt.text.font.match:   REMARK: looking for best foundry for family 'Font Awesome 6 Free Solid' [1]
qt.text.font.match:           looking for matching style in foundry 'AWSM' 1
qt.text.font.match:           best style has distance 0x32
qt.text.font.match:           found smoothly scalable font (17 pixels)
qt.text.font.match:           found a match: score 2000 best score so far ffffffff
```

I'm not *exactly* sure what causes that, but at the top of your logs we see this, which might be an indication:

```
qt.text.font.db: Adding font: familyName "Font Awesome 6 Free" stylename "Regular" weight 400 style QFont::StyleNormal pixelSize 0 antialiased true fixed false
qt.text.font.db: Registering alias "Font Awesome 6 Free Regular" to family "Font Awesome 6 Free"
```

**Comment by nuttyartist** [comment]
Very good research! Maybe `Font Awesome 6 Free Regular` clashes with `Font Awesome 6 Free Solid`? It's hard for me to see why tho. Maybe we can just change the name of the fonts?

**Comment by zjeffer** [comment]
The problem seems to stem from the `otf-font-awesome` and `ttf-font-awesome` packages. Uninstalling both of them fixes the issue @samegit3 

`otf-font-awesome` is an optional dependency for Waybar. Would be nice if we could find a way to force specific fonts in Notes, without having to uninstall these packages.

**Comment by samegit3** [comment]
I had `ttf-font-awesome`, uninstalling it seems to fix the problem.
