### ISSUE TITLE
QML windows don't work on Ubuntu 23.04

### ISSUE THREAD

**Issue by zjeffer** [nuttyartist/notes#624]
The Kanban and Editor settings are completely empty and white. I'm probably missing a dependency but I can't find which. Here's the output when running the latest master (compiled from source) on Ubuntu 23.04:

```
qrc:/qt/qml/EditorSettings.qml:228:21: Type FontChooserButton unavailable 
                         FontChooserButton { 
                         ^
qrc:/qt/qml/FontChooserButton.qml:113:5: Type ComboBox unavailable 
         ComboBox { 
         ^
qrc:/qt-project.org/imports/QtQuick/Controls/Material/ComboBox.qml:5:1: module "QtQuick.Window" is not installed 
     import QtQuick.Window 
     ^
qrc:/qt/qml/kanbanMain.qml:5:1: module "QtQuick.Layouts" is not installed 
     import QtQuick.Layouts 2.12 
     ^
```

I tried the instructions from [this PR](https://github.com/nuttyartist/notes/pull/615), but it still doesn't work.

**Comment by guihkx** [comment]
Just to clarify something: You were able to build from source using only the packages listed in the "Build dependencies" column, right?

**Comment by zjeffer** [comment]
I don't remember if I installed both the build dependencies and the runtime dependencies and *then* compiled, or if I compiled before installing the runtime dependencies. I can't really check right now because this was on my work computer.

Which apt package should contain these QML modules?

**Comment by guihkx** [comment]
>Which apt package should contain these QML modules?

Probably `qml6-module-qtquick-layouts` and `qml6-module-qtquick-window`
