### ISSUE TITLE
Explosive memory allocation when moving around window on Sway

### ISSUE THREAD

**Issue by badosu** [nuttyartist/notes#632]
I'm using manjaro-sway without much configuration (pretty much out of the box experience).

If I move the window to separate workspaces or do any operation that changes the window layout it freezes and starts allocation memory to a point I get oom freeze (recovering after the os kills notes).

Version I'm using is 2.2.0 packaged from here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=notes

**Comment by nuttyartist** [comment]
Can you try doing the same once without getting into the Kanban view and without clicking the 3 dots button and another time with and check if there's a difference?

Also, can you test on our AppImages? both the Qt6 and Qt5 versions. That would really help diagnoise the problem.

**Comment by zjeffer** [comment]
I assume this is the same issue as #611 ?

**Comment by nuttyartist** [comment]
Oh I thought #611 is only a CPU issue, not memory. If that's the case then we can close this.

**Comment by badosu** [comment]
> Can you try doing the same once without getting into the Kanban view and without clicking the 3 dots button and another time with and check if there's a difference?

I was able to reproduce it without getting into kanban view, by making it a float window and moving it by dragging the mouse. There might be other mechanisms to reproduce it (I don't remember dragging the last time)

**Comment by badosu** [comment]
Will check out the appimages later.

**Comment by nuttyartist** [comment]
> Will check out the appimages later.

Can you check if it's the same issue as #611? Does the same happens when you maximize and restore the size of your app?

**Comment by badosu** [comment]
Using the [qt5 image](https://github.com/nuttyartist/notes/releases/download/v2.2.0/Notes_2.2.0-Qt5.15.2-x86_64.AppImage):

```
./Downloads/Notes_2.2.0-Qt5.15.2-x86_64.AppImage                                                                                                                              ✔  6s  
kf.windowsystem: Could not find any platform plugin
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
```

I installed `qt5-base qt5-declarative qt5-quick3d qt5-xcb-private-headers`

**Comment by badosu** [comment]
Exact same issue for the [qt6 image](https://github.com/nuttyartist/notes/releases/download/v2.2.0/Notes_2.2.0-Qt6.4.3-x86_64.AppImage)

**Comment by zjeffer** [comment]
Sadly we haven't found a way to include wayland support in the appimages. You should be able to run it with `notes --platform xcb`.

**Comment by badosu** [comment]
With `--platform xcb` the appimages don't reproduce the problem (although I didn't try too hard), I was still able to reproduce on my locally installed notes with this option.

**Comment by zjeffer** [comment]
Yep, sounds like the same issue as #611. The issue is in the Qt6.5 release. 

Closing as a duplicate. Thanks for reporting!

**Comment by badosu** [comment]
Thanks for the fast response!
