### ISSUE TITLE
Add to Homebrew Casks

### ISSUE THREAD

**Issue by bkmystim** [nuttyartist/notes#635]
Hey I would really appreciate if someone finds time to add your awesome app to homebrew-casks.

Thanks for developing this OpenSource note taking app.

**Comment by nuttyartist** [comment]
I just thought about it the other day. That would be neat.

**Comment by cawbrey** [comment]
I added the current version to homebrew-cask.

You should now be able to install with: `brew install notes-better`

And here's the associated PR: https://github.com/Homebrew/homebrew-cask/pull/161646#event-11160007508
