### ISSUE TITLE
Make the option for the window to be Always on top

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#65]
Should we do it?
If so, how we can do it without cluttering the interface? We are not going to have settings panel so we got to think on another way. 

In future releases, there will be a three-dot-button to activate some features, but I don't want to clutter it so we'll see how everything look, when I'll upload my design proposition in [wiki/Design](https://github.com/nuttyartist/notes/wiki/Design) soon.

**Comment by theshadowx** [comment]
I'm thinking about something that looks like this but not with the same button design

![pin on top](http://www.techsupportalert.com/files/images/FileBox-On-Top.jpg)

**Comment by nuttyartist** [comment]
I think this kind of integrated menu bar not suite Notes because it doesn't go well with the design, it is a waste of vertical space, and it can make the app clutter with many options that will ruin its simplicity.

Yet, if our app wasn't cross-platform and would only run on os's with global menu bars like Ubuntu Unity and OS X etc... then taking that approach will be good because it's part of the os, so it doesn't clutter the app and not wasting free vertical space.

But we are aiming for supporting many os's so we gonna need to look for other option.

**Comment by theshadowx** [comment]
it's not the menu which I'm showing here but the pin near '-' .

which its form is modified depending on whether app is pinned or not.

**Comment by nuttyartist** [comment]
Ohh. Buttons like that near the + and trash button are very valuable, the user use them frequently, and the option for Always on top is really not high enough to put it in a button, it's a feature that its place is in some sort of menu that people discover. So I suggest we put it the 3 dot button in the future and also create a keyboard shortcut for this and update the ones on the website.

Also, putting notes Always on top, a.k.a pinning them on your screen, is mostly relevant for kind of sticky notes, so a good place to put a button like you showed might be when you double click a note (or right click and choose...) and open it in a separate window, this might be a good place to show the Pin Button.

**Comment by nuttyartist** [comment]
We gonna drop it because it doesn't work well.

**Comment by nuttyartist** [comment]
We should really have that option. We can do it in our (View -> Always on top) menu.

**Comment by nuttyartist** [comment]
Solved #181.
