### ISSUE TITLE
DPI issues - 150% size Windows 10 

### ISSUE THREAD

**Issue by foudamo** [nuttyartist/notes#66]
I love this tool - but I have an issue with the DPI where it doesn't scale properly (it displays too small, and the text in the left-side menu is on top of each other) 

I tried to disable the DPI settings from the compatibility issues, but that didn't work. 

<img width="373" alt="notes-dpi" src="https://cloud.githubusercontent.com/assets/6817956/15640283/7a910fdc-2604-11e6-9a13-515619c8a099.PNG">

Any suggestions?

**Comment by nuttyartist** [comment]
Hey foudamo, this is truly not the way it should look like.

What is the resolution of the display you're using?
And what operating system are you using?

Thanks for reporting!

**Comment by foudamo** [comment]
I have the Thinkpad Yoga SP1 - it should be 1920x1080
and I am on Windows 10 x64

**Comment by nuttyartist** [comment]
I'm not sure if the source of you problem is your resolution (and that we don't support High-DPI displays [yet](https://github.com/nuttyartist/notes/issues/39)) or just something in the fonts size. 

@theshadowx What do you think?

**Comment by theshadowx** [comment]
I think the problem comes from the fact that "points" was used instead of "pixels" as font unit [here](https://github.com/nuttyartist/notes/blob/dev/src/notewidgetdelegate.cpp#L11-L12)

```
m_titleFont(QFont(QStringLiteral("Liberation Sans"), 10,QFont::Bold)),
m_dateFont(QFont(QStringLiteral("Liberation Sans"), 8)),
```

As the constructor QFont
```
QFont::QFont(const QString &family, int pointSize = -1, int weight = -1, bool italic = false)
```

By using the pointSize the font height will be modified depending on dpi of the screen, whereas pixel stays the same in every  screen.

I think there should be a way to take in consideration the screen dpi when specifying the font size going to be used.

**Comment by nuttyartist** [comment]
If pixels stays the same in every screen, changing our code from points to pixels will solve the problem?
It seems to me like it isn't that easy, and like you said there should be some consideration to the screen resolution etc...

**Comment by foudamo** [comment]
I am not much of a developer here - but I think if you switch from points to pixels it will partially solve the problem - as what will happen in the case of High-DPI displays is the app will display in high quality but with very small and unusable UI, and you will be able to turn off the "high scaling of dpi" for the app to display with usable normal size but have a blurry UI. 

If you don't know what I am talking about Adobe Photoshop had a similar issue: http://www.danantonielli.com/adobe-app-scaling-on-high-dpi-displays-fix/

**Comment by theshadowx** [comment]
@foudamo using pixels will also bring some problems. the laptop used in the website has a screen 13.3" high-resolution QHD+ (3200 x 1800), so using pixels => the text is going to be too small as there are lot of pixels in small area.

**Comment by nuttyartist** [comment]
> @foudamo using pixels will also bring some problems. the laptop used in the website has a screen 13.3" high-resolution QHD+ (3200 x 1800), so using pixels => the text is going to be too small as there are lot of pixels in small area.

Right. Nevertheless, we'll take care for supporting High-DPI screens in #39.
But @foudamo, come to [Gitter](https://gitter.im/nuttyartist/notes) and we'll see if compiling for you a version that uses pixels rather than points will temporarily solve your problem.
