### ISSUE TITLE
Kanban view not present

### ISSUE THREAD

**Issue by josearnal** [nuttyartist/notes#669]
I built the latest version on Alma Linux using the instructions found [here](https://github.com/nuttyartist/notes/blob/master/docs/build_on_linux.md). However, I don't see a way to turn on Kanban view, and Ctrl-Shift-K does nothing.

Below is the output from running cmake
```
-- Trying to find Qt 6...
-- Could not find Qt 6, will try Qt 5 next...
-- Success! Configuration details:
-- App name: Notes
-- App version: 2.2.1
-- Qt version: 5.15.2
-- Update checker: ON
-- Pro Version: ON
-- Build type: Release
-- Configuring done
-- Generating done
```

**Comment by zjeffer** [comment]
> Could not find Qt 6, will try Qt 5 next...

I think you need Qt6 for Kanban view to work.

**Comment by nuttyartist** [comment]
> I think you need Qt6 for Kanban view to work.

That is right.

**Comment by guihkx** [comment]
Closing this one, as per the two posts above.
