### ISSUE TITLE
Add changelog for 2.3.0 to Debian's `changelog` file

### ISSUE THREAD

**Issue by guihkx** [nuttyartist/notes#687]
Here's a commit that can be used as reference on how to do it:

https://github.com/nuttyartist/notes/commit/6976f77030a0df17463a1ce7d71e4ee66c10ec14#diff-71cd9b5068bb1c41424581cd8b7d86934d0662c81d2b42b222b0f9bc060c98f9

**Comment by nuttyartist** [comment]
https://github.com/nuttyartist/notes/pull/688
