### ISSUE TITLE
High CPU usage when hovering over folders & tags

### ISSUE THREAD

**Issue by zjeffer** [nuttyartist/notes#689]
On latest git version, running with Qt 6.7.2 on Hyprland. Happens on both native Wayland and XWayland.

Watch the CPU usage of Notes on the right.
* On idle, notes uses 0% CPU.
* Hovering over text in the editor uses 5-10%
* Hovering over the list of notes uses 5-10%
* Hovering over `All notes` and `Trash` uses 0-5%
* Hovering over the folders and tags uses 30-50%

https://github.com/user-attachments/assets/f42009fb-358d-4e17-a685-4e4806fd1989

**Comment by guihkx** [comment]
I looked into this a bit and the root cause seems to be a call to `setStyleSheet()` inside a paint event handler, which causes infinite paint recursion (at least on the tags panel).

I could observe high CPU activity just by leaving the mouse cursor stationary over a tag:

https://github.com/user-attachments/assets/a1d8116c-0691-43a6-a46e-308b5ce76d2d

Line 143 below calls `updateDelegate()`:

https://github.com/nuttyartist/notes/blob/75c876ed96c7da64bbe98cd44cd590e91f364712/src/tagtreedelegateeditor.cpp#L141-L172

Which in turn will always call `setStyleSheet()` (in either line 128 or 133), and therefore triggering a new paint event:

https://github.com/nuttyartist/notes/blob/75c876ed96c7da64bbe98cd44cd590e91f364712/src/tagtreedelegateeditor.cpp#L121-L139

I tried some things to try to avoid that recursion, but I'm still a GUI n00b so none of them worked. :sweat:

**Comment by zjeffer** [comment]
Maybe the 'selected' items can be handled through pure CSS pseudoclasses instead of setting the stylesheet every time?

**Comment by zjeffer** [comment]
Basically what I did here might also be possible in the TagTreeDelegateEditor: https://github.com/nuttyartist/notes/pull/567

**Comment by guihkx** [comment]
> Maybe the 'selected' items can be handled through pure CSS pseudoclasses instead of setting the stylesheet every time?

Maybe, but wouldn't that also trigger a repaint event when the classes changed?

I'm also not sure we can get rid of the paint event handler easily because it does some other stuff as well...

**Comment by guihkx** [comment]
Is this too stupid?

```diff
diff --git a/src/tagtreedelegateeditor.cpp b/src/tagtreedelegateeditor.cpp
index a6e6d2b..0722fc3 100644
--- a/src/tagtreedelegateeditor.cpp
+++ b/src/tagtreedelegateeditor.cpp
@@ -123,23 +123,29 @@ void TagTreeDelegateEditor::updateDelegate()
     auto displayName = m_index.data(NodeItem::Roles::DisplayText).toString();
     QFontMetrics fm(m_titleFont);
     displayName = fm.elidedText(displayName, Qt::ElideRight, m_label->contentsRect().width());
+    QString ss;
 
     if (m_view->selectionModel()->selectedIndexes().contains(m_index)) {
-        m_label->setStyleSheet(QStringLiteral("QLabel{color: rgb(%1, %2, %3);}")
-                                       .arg(QString::number(m_titleSelectedColor.red()),
-                                            QString::number(m_titleSelectedColor.green()),
-                                            QString::number(m_titleSelectedColor.blue())));
+        ss = QStringLiteral("QLabel{color: rgb(%1, %2, %3);}")
+                     .arg(QString::number(m_titleSelectedColor.red()),
+                          QString::number(m_titleSelectedColor.green()),
+                          QString::number(m_titleSelectedColor.blue()));
     } else {
-        m_label->setStyleSheet(QStringLiteral("QLabel{color: rgb(%1, %2, %3);}")
-                                       .arg(QString::number(m_titleColor.red()),
-                                            QString::number(m_titleColor.green()),
-                                            QString::number(m_titleColor.blue())));
+        ss = QStringLiteral("QLabel{color: rgb(%1, %2, %3);}")
+                     .arg(QString::number(m_titleColor.red()),
+                          QString::number(m_titleColor.green()),
+                          QString::number(m_titleColor.blue()));
     }
     m_label->setText(displayName);
+
+    if (m_label->styleSheet() != ss) {
+        m_label->setStyleSheet(ss);
+    }
 }
 
 void TagTreeDelegateEditor::paintEvent(QPaintEvent *event)
 {
+    qDebug() << "Tag hovered";
     updateDelegate();
     QPainter painter(this);
     if (m_view->selectionModel()->selectedIndexes().contains(m_index)) {
```

It doesn't seem to break anything visually, and avoids the paint recursion:

https://github.com/user-attachments/assets/9e30529d-d35c-42d8-85fa-f7ebbeeaf5f9

**Comment by zjeffer** [comment]
That might be a nice quick fix :smile: 

I think we can merge that already and afterwards keep looking for a better fix that maybe doesn't set the stylesheet at all inside the `updateDelegate` function?

**Comment by guihkx** [comment]
Agreed. I'll investigate the folders panel next and if the same "fix" I made for the tags panel applies, I'll open a PR.

**Comment by nuttyartist** [comment]
Wow, what a great catch! Can't believe I haven't noticed that before. It uses almost 100% of one CPU core on my machine. I want to take a look at that...

**Comment by nuttyartist** [comment]
@guihkx I just tested your fix on the folders panel as well, seems to work! Awesome!

**Comment by guihkx** [comment]
Nice! :)

I'm actually finishing to write the commit message and I'll send a PR for review soon!
