### ISSUE TITLE
ctrl+s keybinding for strikethrough is confusing

### ISSUE THREAD

**Issue by Ivo-Evans** [nuttyartist/notes#693]
First of all, thanks for making Notes, it's extremely useful.

Currently pressing `ctrl` and `s` adds a strikethrough to the selected text, or if none is selected, the word the cursor is on. I think the ctrl-s keybinding should be reserved, rather than used for something that modifies the text. 

Although there's no need to save manually in Notes, users will likely expect ctrl-s to save the text, not to change it. For example, I was using Notes to write a precise Markdown document including SQL, and when I pressed ctrl-s to save the document, I initially thought that Notes was editing my SQL on save.

I think it would make most sense if ctrl-s forced a save, or if it just did nothing.

**Comment by nuttyartist** [comment]
Completely agree!

I will change the keyboard shortcut to `Ctrl + Shift + X` (this seems to be the standard in some applications I tested). Will that work?

And yes, there's no need for ctrl-s to save, since Notes saves your data automatically.

**Comment by Ivo-Evans** [comment]
Yeah that sounds like a sensible binding to me!

**Comment by nuttyartist** [comment]
Done in https://github.com/nuttyartist/notes/pull/694

**Comment by guihkx** [comment]
@nuttyartist Can you please also update [docs/keyboard_shortcuts.md](https://github.com/nuttyartist/notes/blob/master/docs/keyboard_shortcuts.md)? Thanks.

**Comment by nuttyartist** [comment]
Whoops, forgot about that. Sure.
