### ISSUE TITLE
All my notes disappeared

### ISSUE THREAD

**Issue by CaroleChe** [nuttyartist/notes#706]
When I opened the application this morning, there were 0 notes, whereas I had notes that were saved correctly for several months. Could I find the files somewhere in my computer?

**Comment by nuttyartist** [comment]
Hi, this is very odd? Can you share a picture of your About window? Simply go to Settings->About Notes.

What operating system do you use?

**Comment by CaroleChe** [comment]
Hi, thanks for your answer. I am on Ubuntu 20.04.
Is that picture you want? Sorry it's in French
![Capture d’écran de 2024-10-04 12-35-21](https://github.com/user-attachments/assets/8fefd44f-658d-4f39-930c-ccbbc6657921)

**Comment by guihkx** [comment]
@CaroleChe He means a screenshot [like this one](https://github.com/user-attachments/assets/0ecb5bfd-847e-451e-aea8-fa8a1ada3ba2).

However, since you're using Ubuntu, it's likely that you've installed Notes from the Snap Store.

Can you post the output of this command:

```
du -b ~/snap/notes/current/.config/Awesomeness/notes.db
```

That command tell us the current size of the Notes database.

**Comment by CaroleChe** [comment]
Sorry to answer only now, but I was in vacation. 

The command line gives :
24576	/home/carole/snap/notes/current/.config/Awesomeness/notes.db
So it is not empty, right?

In the About Notes, it is writen:
Version: 2.3.1+g0b13300
Notes was founded by [Ruby Mamistvalove](https://rubymamistvalove.com/), to create an elegant yet powerful cross-platform and open-source note-taking app.
[Notes Website](https://www.notes-foss.com/)
[Source code on Github](https://github.com/nuttyartist/notes)
[Terms and Privacy Policy](https://www.notes-foss.com/notes-app-terms-privacy-policy)

Acknowledgments
This project couldn't have come this far without the help of these amazing people:

Programmers:
Alex Spataru
Ali Diouri
David Planella
Diep Ngoc
Guilherme Silva
Thorbjørn Lindeijer
Tuur Vanhoutte
Waqar Ahmed

Designers:
Kevin Doyle

And to the many of our beloved users who keep sending us feedback, you are an essential force in helping us improve, thank you!

Notes makes use of the following third-party libraries:

QMarkdownTextEdit
QAutostart
QXT

Notes makes use of the following open source fonts:

Roboto
Source Sans Pro
Trykker
Mate
iA Writer Mono
iA Writer Duo
iA Writer Quattro
Font Awesome
Material Symbols

Qt version: 6.2.4 (built with 6.2.4)

**Comment by CaroleChe** [comment]
There is that at the third location:
32768	/home/carole/snap/notes/122/.config/Awesomeness/notes.db
24576	/home/carole/snap/notes/176/.config/Awesomeness/notes.db
32768	/home/carole/snap/notes/6/.config/Awesomeness/notes.db

Luckily, I've saved all my files few days ago, I must retrieve my notes. Maybe I should avoid the snap store...

**Comment by nuttyartist** [comment]
> Luckily, I've saved all my files few days ago, I must retrieve my notes. Maybe I should avoid the snap store...

So, do you have a backup of your home folder? If so, you should probably be able to restore from there.

It's so odd that suddenly all your notes disappeared. Did it happen with other apps as well?

**Comment by CaroleChe** [comment]
Yes, that's it, I have a backup. No, it didn't happen with any other app...

**Comment by guihkx** [comment]
I have to look into how (and why) snap creates different databases for each app revision:

>32768 /home/carole/snap/notes/122/.config/Awesomeness/notes.db
>32768 /home/carole/snap/notes/6/.config/Awesomeness/notes.db

These two have ~32 KiB, so that's likely where your notes are. 

I think I just have to understand why snap chose to create a new database file instead of using that one...

**Comment by CaroleChe** [comment]
Here is my snap list:
![image](https://github.com/user-attachments/assets/46911f05-4aef-4ed7-b961-78a714f848bb)

**Comment by CaroleChe** [comment]
Hello,

What should I do to restore the notes in the application? I've copied the files of  /home/carole/snap/notes/6/.config/Awesomeness in /home/carole/snap/notes/current/.config/Awesomeness/notes.db, but it didn't work.

**Comment by CaroleChe** [comment]
Hello, no, it doesn't work. But at least, I can see my notes in the file .ini.

**Comment by nuttyartist** [comment]
> Hello, no, it doesn't work. But at least, I can see my notes in the file .ini.

I think I understand now. The `.ini` is called `oldNotes.ini`? Here's what you should do if the `.ini` contains your notes:

1. Close all instances of Notes.
2. Copy that `.ini` and save a backup of it somewhere.
3. Inside the `Awesomeness` folders (I'm not sure which one your app is using, so maybe do it for all of them), you should remove all the `notes.db` (make sure you don't need it, or at least backup this file as well) and `settings.ini` files.
4. Copy & paste `oldNotes.ini` into `Awesomeness` folder and rename it to `notes.ini`.
5. Launch Notes.
6. This should load all your old notes and migrate them into the new database version.

Please let me know if it worked.

**Comment by CaroleChe** [comment]
That worked !

**Comment by nuttyartist** [comment]
Great news! I'll close this issue now.
