### ISSUE TITLE
Deleted notes don't get deleted after a crash, or when quitting the app forcefully.

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#72]
To solve that problem `deleteNoteFromDataBase()` should be called from `deleteNote()`, and this should be added to `deleteNoteFromDataBase()` (to make sure):

```C++
m_notesDatabase->sync();
m_trashDatabase->sync();
```

I didn't do it because I didn't knew where to put `deleteNoteFromDataBase()` inside `deleteNote()`.
Should it be in "isFromUser" or not? 
Is there something more that needs to be done?
@theshadowx

**Comment by theshadowx** [comment]
That's true. The idea, behind the way it was coded, is to read/write from/to database as minimum as possible.

Each time the user delete a note, it goes to the m_deletedNotesModel, when the user quit the the app at this moment, the notes are removed from note database and added to the trash database

**Comment by nuttyartist** [comment]
But why? If the notes are deleted they should be saved right away to the trash, so the user (supposedly) can restore them from there. The thing is if the user deleted his notes, he wants them to be deleted. If he did this mistakenly or just have second thoughts about it, he (again, supposedly in the future) can restore it easily.

**Comment by theshadowx** [comment]
this can be done with the current state. if the user has mistakenly deleted a note, it is possible to restore the note from trashModel.

From my point of view, the use of settings as if it is a database is not good, because I think it wasn't meant to be used as that.

My proposal is instead of using settings as mean to store notes and deleted notes, we add a database like sqlite, and we manage it from another thread.

**Comment by nuttyartist** [comment]
Yes, I truly agree. QSettings is really no the way to go about storing the notes databases. We should use QSettings only for the Settings database. I would open a new issue for that and set it for the 1.0.0 milestone, so we'll prepare a good ground in 1.0.0 for future versions.

The point of this current 'issue' is just to make sure that when a user deleted a note, it is deleted and going to the trash database. The user should feel safe that when he's going to turn the computer app or launch the app it will look exactly like it was the last time he saw it (the point of auto save). And if anything mistakenly happened to his files he could easily restore it from the trash.

**Comment by theshadowx** [comment]
The notes are always accessible, whether there was a crash, or the user quitted the app.

- in the case there was a crash, when the user relaunch the app, the deleted notes will be shown as if they weren't deleted.
- in case the user quit the app, the database will be updated (deleted notes : notes database --> trash database) 

here is where the magic happen ;) : https://github.com/nuttyartist/notes/blob/dev/src/mainwindow.cpp#L1144-L1153

```
void MainWindow::QuitApplication ()
{
    //QApplication::quit();
    for (int i=0; i<m_deletedNotesModel->rowCount(); i++) {
        QModelIndex index = m_deletedNotesModel->index(i);
        deleteNoteFromDataBase(index);
    }

    MainWindow::close();
}
```

When we setup a truly database, at this time, we can try to update the database as soon as there is modification in the notes.

**Comment by nuttyartist** [comment]
> The notes are always accessible, whether there was a crash, or the user quitted the app.

I get that. But this:

> in the case there was a crash, when the user relaunch the app, the deleted notes will be shown as if they weren't deleted.

Isn't good. This is what needs to be done:

> we can try to update the database as soon as there is modification in the notes.

I get the idea of reading and writing as minimum as possible from/to the databases, it's a great and appreciated thing to strive for optimum efficiency, yet it shouldn't be on top of the user experience and the way the app should work.

**Comment by theshadowx** [comment]
You're right, but handling the efficiency will let the application works smoothly and the user experience would be great.

Anyway, when the database is established, I think we won't have to care about this problem.

**Comment by nuttyartist** [comment]
Ok. I will close this one and create a new issue for the database.
