### ISSUE TITLE
Create a better way to store and manage notes. Better database.

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#73]
SQLite? Qt SQL?

**Comment by theshadowx** [comment]
Qt has a driver for sqlite3.

why using sqlite ? because it's portable (the database is stored in a file), it doesn't need a server and it is easy to manage it.

**Comment by nuttyartist** [comment]
Sounds like good points. SQLite it is. (:

**Comment by MBuchaus** [comment]
Flat text file no database at all    ensure compatability  with all sync methods  and interoperability

**Comment by nuttyartist** [comment]
@MBuchaus We don't want compatibility with other services. We want to create the simplest way of doing syncing, one that will work so well and "in the background" the users won't have to think about it - all their notes are just there, across all of their devices.

To do that we are going to have a simple syncing mechanism like of simplenote. And our notes will be in a database because it will allow us to better manage and manipulate the notes.

**Comment by MBuchaus** [comment]
Well you've made it really simple for me.   No flat file where I can encrypt and use my files.  I'll stick with qownnotes  vim and gpg.   I won't even need to try yours

**Comment by nuttyartist** [comment]
Well you see, we have a strategy of making decisions based on the user experience first. In everything we do, we think of how it will fit into our cohesive larger vision. We want to empower people to do great things. So our app is the bridge for us to make this come true. And it should be done simply and elegantly, getting out of the way of our users, so they could do what matters for them.

You can please some of the people, some of the time. The thing is, I do care for encryption, so I'm gonna add it to our wishlist, yet it needs to be done under the umbrella of our vision. It should be done in a way that any user could use it no matter is background in technology.

This is the way we do things here. We start "with what incredible feature can we give to the user", not with "what technology there is that we can shove into our app". And we'll keep on doing that.

**Comment by nuttyartist** [comment]
@theshadowx How is it going with that? Should I put this in a future release?

**Comment by theshadowx** [comment]
I think it's done. check https://github.com/theshadowx/notes/tree/DataBase

**Comment by nuttyartist** [comment]
@theshadowx You're a superstar! That's exactly how I wanted it to be. Great.

 In my testing, I didn't encounter any problems, except for some lagging when deleting a note.
And, well, I have a huge amount of notes (something in the area of 500-600), so I guess it was rightfully a bit slow (but not  that much) so that's fine.

And also,  I just want to check if all of my notes were migrated successfully in their entire, although I have a feeling it went successfully. 

I think it's ready for a pull request. Just why there is the lag when deleting notes?

**Comment by theshadowx** [comment]
a software that I use for sqlite db : sqliteman

it is a good software for checking sqlite db and it is in Ubuntu repository

**Comment by nuttyartist** [comment]
@theshadowx I will check it, thanks (:
