### ISSUE TITLE
RPM and Flatpack packaging

### ISSUE THREAD

**Issue by williamjmorenor** [nuttyartist/notes#79]
Hello

I have this app and as Fedora packager I would like to work in the packaging os notes as RPM and Flatpack, but before I wan to ask is there is somebody working on this task already?

**Comment by nuttyartist** [comment]
Hey @williamjmorenor 

No there isn't someone working on these. It would be great if you could do that.

- You should put the files needed for the rpm and flatpack inside a new folder [here](https://github.com/nuttyartist/notes/tree/dev/packaging/linux).
- You should create a script that will automatically generate these packages separately.

I am closing this issue, and refer you this issue: #13.

Thanks
