### ISSUE TITLE
Better app icon

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#8]
What needs to be done is:
- [x] An updated icon that fits the recent design changes (the blueish theme).

To apply the high resolutions (mentioned above^) accordingly in each os:

- [x] Linux (deb)
- [x] Linux (snap)
- [x] Windows
- [x] Mac

**Comment by gkbrk** [comment]
I made [this](https://i.imgur.com/o84Ovva.png) in Inkscape. Not sure if it looks good, not a designer :smile_cat:

**Comment by nuttyartist** [comment]
Well, it doesn't look better than the current icon, so we gonna keep on trying.
Just to make it more constructive:

1. It looks like an iPhone app icon and less desktop suitable.
2. The name of the app shouldn't be in the icon. Most of the time the name of the app is placed with the icon on the launcher/files manager so there is no need for it.
3. Overall, it doesn't look polish and complete.

You are more than welcome to keep iterating and sharing your designs.

**Comment by gkbrk** [comment]
Aww, that's the best I got. Let's hope someone who can design stuff makes a new logo for this.

**Comment by nuttyartist** [comment]
@KevDoy working on changing the icon to fit the new design.
