### ISSUE TITLE
location of notes?

### ISSUE THREAD

**Issue by dddw** [nuttyartist/notes#80]
In which files are the notes stored in various OSes?
I'd like to backup them from time to time.

**Comment by nuttyartist** [comment]
Hey @dddw,

the location of the notes for the various os's is:

Windows: C:\Users\user\AppData\Roaming\Awesomeness
Linux: /home/user/.config/Awesomeness/ or /home/snap/notes/x1/.config/Awesomeness (for Ubuntu 16.04)
On Mac it should be in  /home/.config/Awesomeness/ But I haven't tessted that.

**Comment by dddw** [comment]
mac path is indeed in /home/USER/.config/Awesomeness
