### ISSUE TITLE
Highlight searched words inside the note editor when searching. [15$]

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#81]
We should highlight the searched words inside the editor when doing a search.
We may also want to go right to the first searched word found in the editor on each selected note.

After the PR #198, two things remaining:

- [x] Decide on a yellow shade. EDIT: the current one is good.
- [x] Go right to the first searched word found in the editor on each selected note. The found string should be displayed in the middle of the editor.

**Comment by nuttyartist** [comment]
After the PR #198, two things remaining:

- [ ] Decide on a yellow shade.
- [ ] Go right to the first searched word found in the editor on each selected note.

**Comment by nuttyartist** [comment]
@b00f Is there a way you can make the editor go to the first highlighted word for each selected note when searching if it's not already visible?

**Comment by b00f** [comment]
I couldn't find a way to move scroll bar. I don't know yet the answer.

**Comment by nuttyartist** [comment]
I know you can change the scrollbar value using QScrollBar setValue. Now we need to find a way to get the Y position of a line (that the highlighted text is found in). Then we'll need a way to check if this position is visible to the user. If not we should set the scrollbar value to the position, else, there's nothing to do since it's visible.

**Comment by b00f** [comment]
I did one day work on it. I couldn't get the scroll bar position. I am not sure if there is a way or not.
I am afraid to tell but I can't work on it again.
Maybe you can check the google for a good solution.

**Comment by nuttyartist** [comment]
Done.

**Comment by nuttyartist** [comment]
@Waqar144 you can claim your bounty here: https://www.bountysource.com/issues/36332307-highlight-searched-words-inside-the-note-editor-when-searching-15

**Comment by Waqar144** [comment]
> @Waqar144 you can claim your bounty here: https://www.bountysource.com/issues/36332307-highlight-searched-words-inside-the-note-editor-when-searching-15

Thanks :)
