### ISSUE TITLE
Folders and Tags [$2000 - Hired]

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#87]
# Folders and Tags

Nested folders (folders inside folders) are a powerful way to manage and organize notes.
Tags allow you to connect different notes across different folders (say, you want to filter all notes that require high/low mental work, or all notes that need editing, or things to do while at home, etc).

The design should be like in this picture:

![Notes 2 0 and future 001](https://user-images.githubusercontent.com/16375940/132942803-af7de3fc-335b-482f-b97f-8762150cc6e1.png)

### Folders:

- [ ] Database: if database structure needs to be changed, make sure to do proper migration on the app's startup. check if it's an old version (less than 2.0.0) of the app, if so, create a loader that doesn't allow interacting with the app until it's finished (it should be pretty instant but still). And rename old database to "oldNotes.db". Also, take care of when a user import/restore his notes from an old version. And export his notes as well.
- [ ] `All Notes`, `Trash`, and `Notes`. `Notes` is the default folder of Notes. It can't be deleted or renamed.  'All Notes' shows all the notes across all folders. Whenever `All Notes` is selected, inside the noteView, we should add the name of the folder each note resides in. `Trash` is where all the deleted notes go to.
- [ ] All migrated notes from the old version should go to the "Notes" folder.
- [ ] If someone creates a new note when selecting "All Notes" then it should create the new note inside the default "Notes" folder.
- [ ] Deleting a note from the trash folder show a message that the note will be deleted permanently.
- [ ] The entire view should be scrollable together.
- [ ] The user should be able to drag notes and drop them into the folders.
- [ ] The user should be able to reorder folders by dragging them.
- [ ] Creating a new folder would be done using the + icon depicted in the picture, or a shortcut key.
- [ ] Hovering over a folder will show up a 3 dots button (depicted on the picture) that will open a contextual menu.
- [ ] Right-clicking on a folder will open the same contextual menu.
- [ ] The contextual menu will have the options: Rename Folder, Delete Folder | Separator | Add Subfolder
- [ ] The user could also change the name of a folder by clicking on it and an input field will be revealed.
- [ ] When a folder is deleted all of its notes and its subfolders' notes are deleted. (There should be a message before deleting a folder saying "Are you sure you want to delete this folder? All notes and any subfolders will be deleted."). When deleted, all the notes of the folder and its subfolders notes will be in the trash, yet under no folders - Trash won't show folders it will have just all the deleted notes, so when restoring they will get restored into the general "Notes" folder, or wherever the user drags them to (If you have a good idea on how to restore folders while preserving simplicity you're welcome to suggest).
- [ ] The user needs to be able to drag notes and folders to the Trash folder (but not to All Notes).

### Tags:

While folders are hierarchical meaning they are nested inside each other, tags provide a universal organization between notes that works between different folders. Say you have a folder of Homework->Math->note and another folder Poems->note You can assign to both of these notes the tag "Needs-editing". This way, when you want to know what texts you need to refine and work on you can just select the tags and see the appropriate notes rather than looking at each nested folder.

- [ ] If a note has tags associated with it, they should appear in the note inside the notesList (as depicted in the picture above).
- [ ] Also, they should appear below textEdit
- [ ] Contextual menu both when hovered as in folders or when right clicking. Options: Change color, Delete Tag, Clear Selection
- [ ] User can create tags in the tags panel by clicking the + icon.
- [ ] User assign a tag to a note by dragging the note to a tag
- [ ] Or when right-clicking on a note inside the notesList, there will be options as in the pictures depicted here: https://imgur.com/a/vtQg6ZN

### Pinned notes:

Another feature good to have is the ability to pin different notes in different folders. A mockup for how it should look is below (basically, pinned notes are always at the top of the list, a small box with pin icon and "Pinned" label is showing up at the top, and the line seperator of a note height is increased to 2 points).

- [ ] You pin a note by right clicking on a note from the notesList and a context menu opens with these options: Delete | Seperator | Pin Note | Seperator | Move to -> [Folders] | Seperator | New Note.
- [ ] If a note is already pinned you unpin it by right clicking and instead of `Pin Note` it should show `Unpin Note'.

![Notes 2 0 and future 002](https://user-images.githubusercontent.com/16375940/132942812-766760cb-cfc6-474c-9ea1-02c187a8f93c.png)

If you have any more questions/clarification, please ask. Any suggestions are welcome.

**Comment by newterminator** [comment]
@nuttyartist I agree100% on the folders feature. Especially the drag and drop notes into folders ability as you described. If notes could be released with this feature even by itself in like 1.1 version (after the completion of version 1.0), it will be a great step forward.

**Comment by nuttyartist** [comment]
Yeah, this is a feature I'm looking forward to the most. I have about 500 notes, so I can't wait to orginize everything to have a much clearer view. And yesd, we plan to ship it on the version that would come after 1.0.0.

**Comment by newterminator** [comment]
Yes I have the same issue of having several notes (probably around 100-150) and want to organize them better for quick retrieval. BTW, Thanks @nuttyartist for your continued effort in this project.

**Comment by nuttyartist** [comment]
Sure. Yet the fullest thanks needs to be given to these wonderful people: @theshadowx, @alex-spataru, @dplanella, @KevDoy.

**Comment by newterminator** [comment]
I do wanna extend my thanks to @theshadowx , @alex-spataru , @dplanella , and @KevDoy for all your work in this project, and extending notes further.

**Comment by nuttyartist** [comment]
@theshadowx, Looking forward to you merging between your `Folders WIP` branch and the `dev` branch.

**Comment by crazyStewie** [comment]
I am starting to work on this, and a doubt arose. When importing notes from a version of the software that didn't support folders, should they become 'folderless', and only appear on the 'all notes' section, or should they be put in a 'default' folder?

**Comment by laurens94** [comment]
If with importing you mean upgrading to a new version, a new folder should be created (called ‘Notes’) where all notes are put into. That default folder could then be removed by the user.

If you’re talking about an import feature where the user already made folders and is importing notes from a different version, the user should be asked in which folder he wants to place the notes.

**Comment by nuttyartist** [comment]
Hey, @crazyStewie. Thanks for wanting to contribute! Right now it seems like there are two people working on this. You and @theshadowx.

@theshadowx Can you share current status? If you progressed a lot it might be redundant for somebody else to start working on this.

@crazyStewie Regarding your question, all the notes should be imported to a "Notes" folder, that is not deletable, unlike @laurens94 said.

> If you’re talking about an import feature where the user already made folders and is importing notes from a different version, the user should be asked in which folder he wants to place the notes.

👍

**Comment by theshadowx** [comment]
@nuttyartist there is already a  branch for it working correctly, the issue is that it has passed a lot of time since then, many things have been modified, thus merging is not possible for now.

so things has to start from the latest version of dev. but before the development elsewhere should be frozen, because many things are going to be modified to include this feature.

**Comment by nuttyartist** [comment]
Okay, gotcha. Do you think we can merge #233, #235, #237, release a new version 1.5.0, and afterward we'll stop everything until you'll finish working on 2.0.0?

**Comment by Waqar144** [comment]
#237 can be merged easily. It won't cause any issues.
#233 will probably cause merge conflicts.

**Comment by nuttyartist** [comment]
@theshadowx, @Waqar144, @bjorn Does someone want to take the implementation for this to his hands?

**Comment by theshadowx** [comment]
I nominate myself ;)

**Comment by nuttyartist** [comment]
@theshadowx Awesome!! (:

Be sure to look at the [project](https://github.com/nuttyartist/notes/projects/3) to see issues that might be affected by this.

**Comment by nuttyartist** [comment]
Hey, @theshadowx! Any progress on this?

**Comment by theshadowx** [comment]
@nuttyartist I was busy these last days, but I'm free now.
Updates will reported during this week.

**Comment by nuttyartist** [comment]
@theshadowx Awesome (;

**Comment by alphashuro** [comment]
@theshadowx are you still working on this or should I take a stab at it?

**Comment by theshadowx** [comment]
Hi @alphashuro 
I m still working on it.

**Comment by nuttyartist** [comment]
Hey @theshadowx, is there any way we can see the progress on your repo?

**Comment by theshadowx** [comment]
I'll try to add a branch this weekend

**Comment by nuttyartist** [comment]
Okay 👍

**Comment by nuttyartist** [comment]
> I'll try to add a branch this weekend

Hey, @theshadowx how is it going?

**Comment by nuttyartist** [comment]
Hey, @theshadowx it's been a month and a half since you nominated yourself and still haven't shared any progress yet. Soon, if nothing changes, I'll give the green light for other developers to solve this issue.

**Comment by theshadowx** [comment]
@nuttyartist I'm still working on it,  I know it's been a while, don't worry it will be done :)

**Comment by nuttyartist** [comment]
Okay, then :)

**Comment by nuttyartist** [comment]
@theshadowx How's it going?

**Comment by nuttyartist** [comment]
@alphashuro Still want to take a stab at it?

**Comment by alphashuro** [comment]
> @alphashuro Still want to take a stab at it?

I no longer have enough time unfortunately, but if I become free again I'll let you know!

**Comment by theshadowx** [comment]
@nuttyartist I'm still in :)
I know I took a lot of time, but it's in the plan to be done this year.

**Comment by nuttyartist** [comment]
> > @alphashuro Still want to take a stab at it?
> 
> I no longer have enough time unfortunately, but if I become free again I'll let you know!

@alphashuro Okay.

> @nuttyartist I'm still in :)
> I know I took a lot of time, but it's in the plan to be done this year.

That's good to hear. If there's something I can do to help you move faster, please let me know.

**Comment by akud82** [comment]
It's actual?

**Comment by nuttyartist** [comment]
@akud82 Hi, do you mean if the bounty is real? If so, yes it is. Do you want to work on this issue?

**Comment by akud82** [comment]
@nuttyartist Hi, I think this issue is not so difficult. I've ready to start. The only thing to think about is to try to do without migration, I'm afraid that alter sqlite database may cause a broken db.
FYI: https://sqlite.org/forum/forumpost/21c7b443aa

**Comment by nuttyartist** [comment]
@akud82 You mean migrating the current db to the new version with folders? Yes. You can take a look at how @theshadowx did the migration from the previous version to our current version here:

https://github.com/nuttyartist/notes/blob/dev/src/mainwindow.cpp#L125

**Comment by akud82** [comment]
Will be ready soon, in a couple of days.
![image](https://user-images.githubusercontent.com/10120128/117503842-9bdd7500-af92-11eb-80cb-b56c2f3c411a.png)

**Comment by nuttyartist** [comment]
@akud82 Awesome! I'm curious to test it! Do you have a repo link?

**Comment by akud82** [comment]
> @akud82 Awesome! I'm curious to test it!

https://github.com/akud82/notes/tree/folders-tags-wip

Not implemented yet
- [ ] Copy & Paste
- [ ] Remove all notes from folder
- [ ] Tags

How should tags work? Not description. How to add/remove tag to note.

**Comment by akud82** [comment]
I took the liberty of changing icons. New icons more clearer.

**Comment by nuttyartist** [comment]
>https://github.com/akud82/notes/tree/folders-tags-wip

Great, I'm looking forward to testing it later today.

While folders are hierarchical meaning they are nested inside each other, tags provide a **universal** organization between notes that works between different folders. Say you have a folder of Homework->Math->note and another folder Poems->note You can assign to both of these notes the tag "Needs-editing". This way, when you want to know what texts you need to refine and work on you can just select the tags and see the appropriate notes rather than looking at each nested folder. Let me know if you got it.

**Comment by akud82** [comment]
I got it. Today folders is not support nesting, only one level, bit it’s possible to implement. I thought that folders should have one level, like in macos notes. About tags. I’m want to understand user experience to assign tags and create new tags, how should it work on selection generally clear.

**Comment by akud82** [comment]
I am convinced that the folders hierarchy is overrated, and it is no needed for nesting. Plain structures are better for use. If you need hierarchy as you said, you can use underscore (4ex: Folder1, Folder1_Subforlder1, Folder1_Subfolder2).  User experience will be changed dramatically. But I do not insist. But If you insist that you want to support the hierarchy, simply let me know. I fix it, but I will wait for your specs for UX, and I will need to decide supported nesting level. Also, we will need to add a context menu to control nested folders.

**Comment by nuttyartist** [comment]
* I had annoying problems with my Mac machine today (I uninstalled Xcode back then and now I can't install it back), so tomorrow I'll put some Linux machine on a stick and test it there. I did successfully complied and ran it on a Windows machine (and it looked good) but I didn't have time to play around and test how everything works. So wait for tomorrow for an in-depth review.

macOS Notes does support nested folders:

![Screen Shot 2021-05-11 at 12 54 31 AM](https://user-images.githubusercontent.com/16375940/117729415-7602db00-b1f3-11eb-9dff-05e69a2feb35.png)

And yes, I inssist on hierrachy. When you have 1000 notes (or more) you want to have a way to hierarchically organize them. Our brains are very good at making sense of complexity by using hierarchical structures. Folders+Tags together is a logical and powerful combination:  Folders - hierarchal organization, Tags - global organization.

I understand it can be confusing explaining UX in words, regarding how Tags should work. We can do a video chat if you want (creating a video mockup will take time). I'll nonetheless try to explain how tags should work in words:

I'm looking at [this mockup](https://user-images.githubusercontent.com/16375940/71641592-35ae5700-2ca7-11ea-83aa-c15d13fff5b9.png).
You create a tag by clicking on the '+' button on the left pane near the Tags label. Then, when you are inside a note, you can assign this note to one or more existing tags by starting to type the name of the tag inside the area at the bottom of the note (a short list with likely results should pop up). I will suggest to also let users create a new tag by just typing a tag's name that doesn't exist yet and after clicking Enter it will add it to the tags list on the left pane. Another option to assign a tag to a note is by dragging the note to a tag on the left pane (and then showing the result at the bottom of the note).

When selecting a tag/s on the left pane it should filter and show only the notes with the selected tag/s inside the current folder. Say if I'm in "Story 1" and I want to see all the chapters that need editing I can choose the "needs-editing" tag and see them right away. But let's say I want to see all my chapters that need editing in all my stories, I can click on the "Stories" folder and then choose the "needs-editing" tag. If I want to see all my *notes* that need editing, same principle, I can choose the "All Notes" folder and then choose the "needs-editing" tag.

Let me know if something isn't clear or if you have more questions.

Thanks!

**Comment by akud82** [comment]
fyi
![image](https://user-images.githubusercontent.com/10120128/117803239-75a42780-b267-11eb-9d2b-b54137b24f56.png)

**Comment by nuttyartist** [comment]
Okay, I just finished reviewing your build. It's really awesome! 

Things to note/change/add:

- "All items" should be changed to "All Notes"
- Show the number of notes in a folder near the folder label in the middle pane using a small label like in the [mockup](https://user-images.githubusercontent.com/16375940/71641592-35ae5700-2ca7-11ea-83aa-c15d13fff5b9.png).
- We should have a default "Notes" folder that can't be deleted.
- If someone create a new note when selecting "All items" (should be "All Notes") then it should create the new note inside the default "Notes" folder. 
- All migrated notes from old version should go to the "Notes" folder.
- There needs to be a trash icon near the plus icon of the "Folders" label to delete the selected folder (except when "Notes" selected, then the icon should be gray).
- When clicking on creating a new folder, make the focus on renaming the folder, not on the editor.
- "Trash" label in the center doesn't seem aligned to the middle (Forgot to take a picture).
- When creating a new note there's a pin icon. What does it mean? Does it have some functionality?
- Need a functionality to reorder folders by dragging them.
- Migration is fast. But did you put a loading bar when migrating or not? It migrated my 3600 notes so fast I couldn't tell. But I guess some people would have slower computers, so we should add a loading bar just in case.
- We need to be able to drag and drop folders to the Trash folder (not into "All Notes" though)
- There is a bug that happens only after migrating the notes from the old version. After migration, if I create new folders and new notes in them, quit the app, and then start it again, the folders are gone, while the notes I added are inside "All items". Then, if I click on creating a new folder, somehow it adds them back one by one. I created a video to show.
https://user-images.githubusercontent.com/16375940/117989751-3f3cda00-b345-11eb-9355-1b672966a90f.mp4
- There is a bug where if I click on a folder with 1 note, it animates it like it animated creating a new note. It shouldn't do that. You can see it in the video above as well.
- Creating a new note on an empty folder seems like a good thing since it guides the user to create a note. One thing that doesn't work is when you click the trash icon to delete an empty note it keep creating a new one. It doesn't happen if I just click on the notes's list, the note is deleted and not coming back, like it should.
https://user-images.githubusercontent.com/16375940/117990591-f76a8280-b345-11eb-9d48-ada061362cde.mp4
- It will be good to show the folder of the note when in "All Notes" like in here:
![Screen Shot 2021-05-12 at 5 20 25 PM](https://user-images.githubusercontent.com/16375940/117991315-9a230100-b346-11eb-84fa-0141ff3e07a5.png)


And of course:

- Nested folders. Can be created by right-clicking on a folder in the context menu with (- Rename, - Add subfolder, - Add folder /-----/ - Delete folder), or by dragging and dropping a folder into another one.
- Tags. Should work as I explained to you above. Maybe it would be useful to add them also to the notes list, like in this picture.
![Screenshot from 2021-05-12 14 24 42](https://user-images.githubusercontent.com/16375940/117990554-efaade00-b345-11eb-9e89-8bd8ac9474ed.png)


Everything else works amazing! Drag and drop of notes to folders works great! I'm so surprised! Looking forward to test your changes! I'm really excited about this feature, and I know many other users are also.

**Comment by akud82** [comment]
Thank you for your review. I'll be back in during one week with the progress report. I thought that amount of work will be smaller and now I a little limited in time. You will have to wait a bit cause quite a lot to do.

**Comment by nuttyartist** [comment]
@akud82 Great! I'm looking forward to this!

And ok about the migration 👍

**Comment by nuttyartist** [comment]
Bounty updated :)

https://www.bountysource.com/issues/37086741-folders-and-tags-550

**Comment by akud82** [comment]
Thanks! Will be planed to continued and finished at next week after weekend.

**Comment by nuttyartist** [comment]
Awesome (:

**Comment by nuttyartist** [comment]
@akud82 How's it going?

**Comment by fifa87** [comment]
How are you? I am Avinash. I have read your issuses on Upwork. I am very interesting your project. I have submitted a proposal on upwork, Can i work for you? Best Regards.

**Comment by fifa87** [comment]
If you want test me, i can take and implement one small part of your project.

**Comment by fifa87** [comment]
How are you. Thank you for your upwork's message. I am waiting for your selection. I hope to join into your project.

**Comment by nuttyartist** [comment]
Someone is already hired for this job.

**Comment by abebeos** [comment]
What is the status here? I noticed PR #302 which seems near-complete.

Would like to use this tool (without folders/nodes it makes no sense to me)

**Comment by nuttyartist** [comment]
> What is the status here? I noticed PR #302 which seems near-complete.
> 
> Would like to use this tool (without folders/nodes it makes no sense to me)

Hopefully, we'll merge the PR very soon.

**Comment by nuttyartist** [comment]
Done in #302.
