### ISSUE TITLE
for  deb installer 32/64 packages are empty 

### ISSUE THREAD

**Issue by evaletolab** [nuttyartist/notes#91]
Hello, I'm trying to install notes on ubuntu 16.04 from both ubuntu store and direct download without success. The package size is ~64kb that seems to small.

**Comment by nuttyartist** [comment]
That's weird. Do you have a 32bit or 64bit system? What error message do you get? What happens when you try to install? I would really like to assist you in solving that problem.

**Comment by evaletolab** [comment]
I have ubuntu 16.04 64bit
There is no error, all packages for debian/ubuntu are empty,
### notes-app_1.4+14.10.20140711-0ubuntu1_amd64.deb (size: 99kb )
![image](https://cloud.githubusercontent.com/assets/1422935/18176104/857e8f40-7074-11e6-86b0-7ee7e38a9f6f.png)

**Comment by theshadowx** [comment]
Hi @evaletolab 

I think the package, you mentioned it, is not related to this repo.

**Comment by nuttyartist** [comment]
Yeah, why did you mentioned two different packages?

**notes-app_1.4+14.10.20140711-0ubuntu1_amd64.deb (size: 99kb )
notes_0.9.0_amd64.deb (size: 68kb)**

Only the second one is our note-taking app.

**Comment by evaletolab** [comment]
Hi @theshadowx ,

Sorry for this mistake ! The file, notes-app_1.4+14.10.20140711-0ubuntu1_amd64.deb (size: 99kb ) was from ubuntu store as Notes (notes-app) application name and in fact it is an other application. But, from the [download section in the website](http://www.get-notes.com/linux-download-debian-ubuntu) there is a notice to install Notes from the Ubuntu Software Store, I did the installation too quickly. In my opinion this notice is not specific enough.
![image](https://cloud.githubusercontent.com/assets/1422935/18180733/6de24e58-7088-11e6-8db3-82ab93f5d408.png)

The second file, notes_0.9.0_amd64.deb (size: 68kb) doesn't contains binaries. 
Cheers :)

**Comment by theshadowx** [comment]
@evaletolab no problem
I have looked up the notes app in ubuntu archive, unfortunately there isn't there yet. 
Also I have downloaded the deb package from the website and installed it  without any issue.

try to install the package from terminal : 
```
$ sudo dpkg -i notes_0.9.0_amd64.deb
```

So if there is any error it will be printed.

Cheers

**Comment by evaletolab** [comment]
I don't know what I did wrong. it works perfectly!
I am really sorry for this misunderstanding.  Cheers, 1000 thanks for Notes!
