### ISSUE TITLE
Notes titles doesn't get trimmed in noteView

### ISSUE THREAD

**Issue by nuttyartist** [nuttyartist/notes#92]
The text of the notes titles doesn't get trimmed.
@theshadowx Can you have a look?

**Comment by theshadowx** [comment]
could you show me a picture of that

**Comment by nuttyartist** [comment]
Sure.

![boo2](https://cloud.githubusercontent.com/assets/16375940/18327081/78d2b9b0-7551-11e6-86d4-90b6695a1b78.png)
